import {z} from "zod";
import {database,bucket,record,checkOrigin,failure,HttpError,now} from "@/lib/server";
import {generateDifyImage} from "@/lib/dify-media";
import {publicConfig,saveMedia,stageImageDownload,retryImageDownload} from "@/lib/ark";
import {visualPrompt} from "@/lib/poster-contract";
import {streamJson} from "@/lib/stream-json";
const input=z.object({project_id:z.string().min(1),slot:z.number().int().min(0).max(3)});
export async function GET(req:Request,{params}:{params:Promise<{id:string}>}){try{const r=await record((await params).id,new URL(req.url).searchParams.get("project_id")||"");if(r.type!=="poster_batch")throw new HttpError(404,"海报任务不存在");const slots=[];for(let slot=0;slot<4;slot++){const m=await database().prepare("SELECT data FROM records WHERE id=?").bind(r.id+"-"+slot).first<any>();slots.push(m?{slot,...JSON.parse(m.data)}:{slot,status:"pending"})}return Response.json({id:r.id,...r.data,slots})}catch(e){return failure(e)}}
async function runSlot(req:Request,{params}:{params:Promise<{id:string}>}){let mediaId="",data:any,submitted=false;try{checkOrigin(req);const b=input.parse(await req.json()),r=await record((await params).id,b.project_id);if(r.type!=="poster_batch"||r.data.status!=="ready"||!r.data.brief.consent)throw new HttpError(400,"海报任务尚未准备好。");const project=await database().prepare("SELECT revision FROM projects WHERE id=?").bind(b.project_id).first<any>();if(project.revision!==r.data.brief.project_revision)throw new HttpError(409,"项目已更新，请核对当前任务。");mediaId=r.id+"-"+b.slot;const old=await database().prepare("SELECT data FROM records WHERE id=?").bind(mediaId).first<any>();if(old)return Response.json({id:mediaId,slot:b.slot,...JSON.parse(old.data)});const ref=await bucket().get("_private/poster-reference/"+r.id),snap=ref?await ref.json<any>():null;if(snap?.project_id!==b.project_id)throw new HttpError(503,"IP参考快照暂不可用。");const c=await publicConfig(),prompt=visualPrompt(r.data.brief,r.data.visual_prompt,b.slot),t=now();data={kind:"image",batch_id:r.id,slot:b.slot,status:"submitting",prompt,model:c.image_model,reference_id:r.data.brief.asset_id,provider:"dify-ark",review_status:"awaiting_review",user_brief_id:r.id};const inserted=await database().prepare("INSERT OR IGNORE INTO records (id,project_id,type,data,revision,created_at,updated_at) VALUES (?,?,'media',?,1,?,?)").bind(mediaId,b.project_id,JSON.stringify(data),t,t).run();if(!inserted.meta.changes)return Response.json({status:"submitting",id:mediaId},{status:202});submitted=true;const run=await generateDifyImage({project_id:b.project_id,request_id:mediaId,prompt,approved_run_id:r.id,reference_image:snap.image||undefined,consent:true},c.image_model);Object.assign(data,{status:"download_pending",workflow_run_id:run.workflow_run_id,elapsed:run.elapsed});await stageImageDownload(mediaId,b.project_id,run.result.data[0].url);await saveMedia(mediaId,data);try{data.asset_id=await retryImageDownload(mediaId,b.project_id);data.status="succeeded"}catch{data.error="图片已生成但保存失败，可重试保存原图，不会重新生成。"}await saveMedia(mediaId,data);return Response.json({id:mediaId,...data},{status:201})}catch(e){if(mediaId&&data&&submitted){data.status="unknown";data.error="生成结果未确认，请核对Dify原运行，不能重复提交此张。";await saveMedia(mediaId,data).catch(()=>{})}return failure(e)}}

export async function POST(req:Request,context:{params:Promise<{id:string}>}){return req.headers.get("X-WOO-Stream")==="1"?streamJson(()=>runSlot(req,context)):runSlot(req,context)}
