import {activitySchema,activityTemplates} from '@/lib/activity';
import {initializeMaterials,materialRecord} from '@/lib/materials-server';
import {selectMaterial} from '@/lib/materials';
import {unifiedTaskRows} from '@/lib/unified-tasks';
import {z} from 'zod';
import {database,projectExists,projectSchema,checkOrigin,failure,now,HttpError} from '@/lib/server';
export async function POST(req:Request){try{checkOrigin(req);const b=projectSchema.extend({template_id:z.enum(['blank','music','challenge','graduation']).default('blank'),copy_from:z.string().max(100).default(''),activity:activitySchema.optional()}).parse(await req.json());const d=projectSchema.parse(b),id=crypto.randomUUID(),t=now(),db=database(),template=activityTemplates[b.template_id];let tasks:any[]=[],lines:any[]=[];if(b.copy_from){await projectExists(b.copy_from);tasks=(await unifiedTaskRows(b.copy_from)).map(r=>({title:r.data.title,lane:r.data.lane,phase:r.data.phase,channel:r.data.channel||'',notes:'从已有项目复用任务结构，请确认本次执行要求。'}));const previous=await db.prepare("SELECT data FROM records WHERE project_id=? AND type='procurement'").bind(b.copy_from).first<any>();lines=previous?JSON.parse(previous.data).lines.map((l:any)=>({...l,shipping:0,notes:'复用物料需求；价格、规格和借用可用性需要本次重新确认。'})):[];d.source_note='复用项目安排，历史成果与实际执行状态不复制。';}else{tasks=template.tasks.map(([lane,title])=>({title,lane,phase:'预热',channel:'',notes:'模板建议，请按本次活动调整。'}));if(template.materials.length){await initializeMaterials();for(const key of template.materials){const m=await materialRecord('material-'+key);if(m.data.active)lines.push({...selectMaterial(m.id,m.data),notes:'模板建议；需求数量初始为1，请按本次活动调整并核对报价。'})}}if(template.roles.length)d.brief+=(d.brief?'\n':'')+'建议岗位（待安排）：'+template.roles.join('、');}
const statements:any[]=[db.prepare('INSERT INTO projects (id,name,brand,school,goal,brief,source_note,reference_budget,revision,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,1,?,?)').bind(id,d.name,d.brand,d.school,d.goal,d.brief,d.source_note,d.reference_budget,t,t),db.prepare("INSERT INTO records VALUES (?,?,'activity_settings',?,1,?,?)").bind('activity-'+id,id,JSON.stringify(b.activity||{event_name:d.name,time:'',place:'',contact:'',mandatory:''}),t,t)];for(const task of tasks)statements.push(db.prepare("INSERT INTO records VALUES (?,?,'task',?,1,?,?)").bind(crypto.randomUUID(),id,JSON.stringify({...task,status:'todo',owner:'',due:'',source:b.copy_from?'复制安排（待确认）':'活动模板（待调整）'}),t,t));if(lines.length)statements.push(db.prepare("INSERT INTO records VALUES (?,?,'procurement',?,1,?,?)").bind('procurement-'+id,id,JSON.stringify({name:d.name+' · 配套物料',lines}),t,t));await db.batch(statements);return Response.json({id},{status:201})}catch(e){return failure(e)}}
export async function PATCH(req:Request){try{checkOrigin(req);const body=projectSchema.extend({id:z.string().min(1),revision:z.number().int().positive()}).parse(await req.json());const d=projectSchema.parse(body);const r=await database().prepare('UPDATE projects SET name=?,brand=?,school=?,goal=?,brief=?,source_note=?,reference_budget=?,revision=revision+1,updated_at=? WHERE id=? AND revision=?').bind(d.name,d.brand,d.school,d.goal,d.brief,d.source_note,d.reference_budget,now(),String(body.id),Number(body.revision)).run();if(!r.meta.changes)throw new HttpError(409,'项目已在其他窗口更新，请刷新后重试。');return Response.json({ok:true})}catch(e){return failure(e)}}
