'use client';
import { useEffect,useRef,useState,useCallback,lazy,Suspense } from 'react';
import { LayoutDashboard,ClipboardList,Clapperboard,FolderOpen,Wallet,Bot,Plus,Search,Check,Download,Upload,FileText,Image as ImageIcon,CalendarDays,MoreHorizontal,X,CheckCircle2,AlertCircle,ChevronRight,SlidersHorizontal,RefreshCw,Pencil,Trash2,Link2,ArrowUpRight,Layers,Menu,Radio,Flag,BookOpen,Sparkles,Copy,Loader2 } from 'lucide-react';
import {activityTemplates} from '@/lib/activity';
import ActivityInformation from '@/components/activity-information';
const TaskViews=lazy(()=>import('@/components/task-views'));
const CloseoutOverview=lazy(()=>import('@/components/closeout-overview'));
import {isEarlyConcept} from '@/lib/closeout-baseline';
const ProjectExecution=lazy(()=>import('@/components/project-execution'));
import ProjectProductionOverview from '@/components/project-production-overview';
const MemberPool=lazy(()=>import('@/components/member-pool'));
const MediaWorkbench=lazy(()=>import('@/components/media-workbench'));
const CopywritingWorkbench=lazy(()=>import('@/components/copywriting-workbench'));
const MaterialWorkbench=lazy(()=>import('@/components/material-workbench'));
import {procurementTotals} from '@/lib/materials';
const PosterWorkbench=lazy(()=>import('@/components/poster-workbench'));
const AgentWorkbench=lazy(()=>import('@/components/agent-workbench'));
import {Project,Item,agents,taskStatuses,contentStatuses,contentKinds,assetCategories,plannedCents,money} from '@/lib/model';
const pages=[{id:'overview',name:'项目总览',icon:LayoutDashboard},{id:'execution',name:'项目执行',icon:ClipboardList},{id:'assets',name:'资料资产管理',icon:FolderOpen}];
const titles:Record<string,string>={overview:'项目总览',execution:'项目执行',assets:'资料资产管理',tasks:'执行任务看板',content:'本项目内容记录',budget:'物料准备与预算',team:'人员安排',online:'线上宣发安排',offline:'线下宣发安排',poster:'线上海报创作',offlinePoster:'线下海报制作',copy:'平台文案写作',video:'视频创作',agents:'项目策划与复盘'};
const subheads:Record<string,string>={overview:'查看当前制作、审核与执行记录。',execution:'推进本次活动的内容制作与执行。',assets:'项目资料、品牌素材与共享资源。'};
const assetSections=[['files','项目资料'],['ip','IP 数字资产'],['members','小组成员'],['materials','实体物料池']];
const sourceWarnings=['当前为合成演示资料，不代表原项目成果','播放与曝光口径不同，不加总为去重人数','真实费用与年份未知，保留待核对','初始计划不作为完成证据'];
const size=(b:number)=>b>1024*1024?(b/1024/1024).toFixed(1)+' MB':Math.ceil(b/1024)+' KB';
const status=(s:string)=>taskStatuses[s]||contentStatuses[s]||({approved:'已批准',rejected:'已驳回',awaiting_review:'待审核',confirmed:'已确认',ordered:'已订购',received:'已到货'} as any)[s]||s;
function Badge({value}:{value:string}){return <span className={'badge badge-'+value}>{status(value)}</span>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const d=ref.current;d?.showModal();return()=>d?.close()},[]);return <dialog ref={ref} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose()}} className="dialog"><header><h2>{title}</h2><button type="button" className="icon-btn" onClick={onClose} aria-label="关闭"><X size={21}/></button></header>{children}</dialog>}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={wide?'field wide':'field'}><span>{label}</span>{children}</label>}
function Empty({title,description,action}:{title:string;description:string;action?:React.ReactNode}){return <div className="empty"><Layers size={32}/><h3>{title}</h3><p>{description}</p>{action}</div>}
async function api(url:string,options?:RequestInit){const r=await fetch(url,options);const d:any=await r.json();if(!r.ok)throw new Error(d.error||'操作未完成，请重试。');return d}
const json=(method:string,data:any)=>({method,headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
export default function Workbench(){
 const [page,setPage]=useState('overview'),[projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(''),[items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[toast,setToast]=useState(''),[busy,setBusy]=useState(false),[nav,setNav]=useState(false);
 const [historyOpened,setHistoryOpened]=useState(false),[executionOpened,setExecutionOpened]=useState(false),[assetSection,setAssetSection]=useState('files'),[executionTask,setExecutionTask]=useState<{id:string;title:string}|null>(null);
 useEffect(()=>setExecutionTask(null),[projectId]);
 const [selectedId,setSelectedId]=useState(''),[assetReview,setAssetReview]=useState<Item|null>(null),[assetDecision,setAssetDecision]=useState('approved'),[assetNote,setAssetNote]=useState('');
 const [taskView,setTaskView]=useState('board'),[contextOpen,setContextOpen]=useState(false),[logsOpen,setLogsOpen]=useState(false);
 const [search,setSearch]=useState(''),[lane,setLane]=useState('all'),[kind,setKind]=useState('all'),[showConcepts,setShowConcepts]=useState(false);
 const [editor,setEditor]=useState<{type:string;item?:Item;extra?:any}|null>(null),[form,setForm]=useState<any>({}),[formError,setFormError]=useState(''),[projectEdit,setProjectEdit]=useState(false),[projectNew,setProjectNew]=useState(false),[uploading,setUploading]=useState(false),[file,setFile]=useState<File|null>(null),[confirm,setConfirm]=useState<Item|null>(null);
 const project=projects.find(p=>p.id===projectId),tasks=items.filter(r=>r.type==='task'&&!isEarlyConcept(r)),contents=items.filter(r=>r.type==='content'&&!isEarlyConcept(r)),budgets=items.filter(r=>r.type==='budget'),assets=items.filter(r=>r.type==='asset');
 const done=tasks.filter(r=>r.data.status==='done').length,progress=tasks.length?Math.round(done/tasks.length*100):0;
 const selectedProcurement=items.find(r=>r.type==='procurement'),selectionTotals=selectedProcurement?procurementTotals(selectedProcurement.data.lines||[]):null;
 const confirmedBudget=budgets.filter(b=>b.data.status!=='unverified').reduce((s,b)=>s+plannedCents(b.data),0),pendingBudget=budgets.filter(b=>b.data.status==='unverified').reduce((s,b)=>s+plannedCents(b.data),0),actuals=budgets.filter(b=>b.data.actual_amount!==null),actualBudget=actuals.reduce((s,b)=>s+Math.round(b.data.actual_amount*100),0);
 const load=useCallback(async(id?:string)=>{setLoading(true);setError('');try{const d=await api('/api/state?view=workbench'+(id?'&project='+encodeURIComponent(id):''));setProjects(d.projects);setProjectId(d.project_id);setItems(d.records)}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(t)},[toast]);
 function go(v:string,task?:{id:string;title:string}){setExecutionTask(task||null);if(v==='members'){setAssetSection('members');v='assets'}if(v==='execution')setExecutionOpened(false);else if(!['overview','assets'].includes(v))setExecutionOpened(true);setPage(v);setSearch('');setKind('all');setNav(false)}
 function newItem(type:string,extra:any={}){const defaults:any={task:{title:'',lane:'online',phase:'预热',status:'todo',owner:'',due:'',notes:'',source:'手动录入'},content:{title:'',kind:'topic',channel:'',task_id:'',status:'idea',body:'',source:'手动录入'},budget:{title:'',category:'场地搭建',quantity:1,unit:'件',unit_price:0,shipping:0,actual_amount:null,spec:'',status:'unverified',notes:'',source:'手动录入'},agent:{key:extra.key,provider:'Dify',workflow_id:'',notes:''}};setForm({...defaults[type],...extra});setFormError('');setEditor({type,extra})}
 const selectedItem=items.find(i=>i.id===selectedId);
 function edit(item:Item){setSelectedId(item.id);setForm({...item.data});setFormError('');setEditor({type:item.type,item})}
 function agentOpen(key:string){const old=items.find(i=>i.type==='agent'&&i.data.key===key);if(old)edit(old);else newItem('agent',{key})}
 async function save(e:React.FormEvent){e.preventDefault();if(!editor||!project)return;setBusy(true);setFormError('');try{let d={...form};if(editor.type==='budget'){d.quantity=Number(d.quantity);d.unit_price=Number(d.unit_price);d.shipping=Number(d.shipping);d.actual_amount=d.actual_amount===''||d.actual_amount===null?null:Number(d.actual_amount)}await api('/api/records',json(editor.item?'PATCH':'POST',{type:editor.type,project_id:project.id,...(editor.item?{id:editor.item.id,revision:editor.item.revision}:{}),data:d}));setEditor(null);setToast(editor.type==='agent'?'接入说明已保存，Agent 仍未连接':'已保存');await load(project.id)}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}}
 async function toggleTask(item:Item){setSelectedId(item.id);if(busy)return;if(item.data.status==='done'){edit(item);setForm({...item.data,status:'todo',change_reason:''});return}setBusy(true);try{await api('/api/records',json('PATCH',{id:item.id,revision:item.revision,project_id:item.project_id,data:{...item.data,status:item.data.status==='done'?'todo':'done'}}));setToast(item.data.status==='done'?'已撤销完成':'已标记完成');await load(projectId)}catch(e){setToast((e as Error).message)}finally{setBusy(false)}}
 async function remove(){if(!confirm)return;setBusy(true);setFormError('');try{await api('/api/records',json('DELETE',{id:confirm.id,revision:confirm.revision,project_id:confirm.project_id}));setConfirm(null);setToast('已删除');await load(projectId)}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}}
 function projectModal(isNew=false){setForm(isNew?{name:'',brand:'',school:'',goal:'',brief:'',source_note:'手动创建的项目',reference_budget:null,template_id:'blank',copy_from:'',time:'',place:'',contact:'',mandatory:''}:{...project,reference_budget:project?.reference_budget===null?null:(project?.reference_budget||0)/100});setFormError('');setProjectNew(isNew);setProjectEdit(true)}
 async function saveProject(e:React.FormEvent){e.preventDefault();setBusy(true);setFormError('');try{const d=await api('/api/projects',json(projectNew?'POST':'PATCH',{...form,...(projectNew?{activity:{event_name:form.name,time:form.time||'',place:form.place||'',contact:form.contact||'',mandatory:form.mandatory||''}}:{}),reference_budget:form.reference_budget===''||form.reference_budget===null?null:Math.round(Number(form.reference_budget)*100)}));setProjectEdit(false);setToast(projectNew?'项目已创建':'项目资料已保存');await load(projectNew?d.id:projectId);if(projectNew){setPage('execution');setExecutionOpened(true)}}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}}
 async function upload(e:React.FormEvent){e.preventDefault();if(!file){setFormError('请选择文件');return}if(file.size>20*1024*1024){setFormError('文件超过20MB，请拆分或压缩后上传。');return}setBusy(true);setFormError('');try{const f=new FormData();f.set('file',file);f.set('project_id',projectId);Object.entries(form).forEach(([k,v])=>f.set(k,String(v??'')));await api('/api/files',{method:'POST',body:f});setUploading(false);setToast('资料已上传');await load(projectId)}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}}
 function uploadModal(){setFile(null);setForm({title:'',category:'结案资料',origin:'结案资料',notes:''});setFormError('');setUploading(true)}
 async function reviewAsset(e:React.FormEvent){e.preventDefault();if(!assetReview)return;setBusy(true);setFormError('');try{await api('/api/files/'+assetReview.id+'/review',json('POST',{project_id:projectId,revision:assetReview.revision,decision:assetDecision,note:assetNote}));setAssetReview(null);setToast('素材审核已记录');await load(projectId)}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}}
 async function exportData(){if(!project||busy)return;setBusy(true);try{const full=await api('/api/state?project='+encodeURIComponent(project.id));download(JSON.stringify({schema_version:'1.0',exported_at:new Date().toISOString(),project:full.projects.find((p:Project)=>p.id===full.project_id),records:full.records},null,2),project.name+'_项目记录.json','application/json');setToast('完整项目记录已导出')}catch(e){setToast((e as Error).message)}finally{setBusy(false)}}
 function download(text:string,name:string,mime:string){const u=URL.createObjectURL(new Blob([text],{type:mime}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}

 const filteredTasks=(showConcepts?items.filter(r=>r.type==='task'):tasks).filter(t=>(lane==='all'||t.data.lane===lane)&&(`${t.data.title} ${t.data.owner} ${t.data.notes}`).toLowerCase().includes(search.toLowerCase()));
 const filteredContent=(showConcepts?items.filter(r=>r.type==='content'):contents).filter(c=>(kind==='all'||c.data.kind===kind)&&(`${c.data.title} ${c.data.body}`).toLowerCase().includes(search.toLowerCase()));
 const set=(k:string,v:any)=>setForm((f:any)=>({...f,[k]:v}));
 function input(k:string,placeholder='',type='text',required=false){return <input value={form[k]??''} type={type} required={required} maxLength={type==='text'?300:undefined} min={type==='number'?0:undefined} step={type==='number'?'any':undefined} onChange={e=>set(k,e.target.value)} placeholder={placeholder}/>}
 function select(k:string,opts:Record<string,string>){return <select value={form[k]??''} onChange={e=>set(k,e.target.value)}>{Object.entries(opts).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select>}
 function taskCard(t:Item){return <article key={t.id} className={'task-card '+(t.data.status==='done'?'complete':'')}><div className="card-top"><span className={'lane-label '+t.data.lane}>{t.data.lane==='online'?'线上':'线下'} · {t.data.phase}</span><button className="icon-btn" aria-label={'编辑 '+t.data.title} onClick={()=>edit(t)}><MoreHorizontal size={20}/></button></div><button className="task-title" onClick={()=>edit(t)}>{t.data.title}</button><p className="clamp-two">{t.data.notes||'还没有执行说明'}</p><div className="task-bottom"><Badge value={t.data.status}/><span>{t.data.owner||'待分配'}</span></div><div className="task-footer"><span><CalendarDays size={14}/>{t.data.due||'日期待确认'}</span><button disabled={busy} className={'check-btn '+(t.data.status==='done'?'checked':'')} onClick={()=>toggleTask(t)} aria-label={(t.data.status==='done'?'撤销完成 ':'标记完成 ')+t.data.title}>{t.data.status==='done'?<Check size={14}/>:null}</button></div></article>}
 return <div className="app-shell">
 <aside className={'sidebar '+(nav?'open':'')}><div className="brand"><div className="brand-mark">W!</div><div><strong>WOO虎</strong><span>校园营销工作台</span></div></div><div className="sidebar-section">工作空间</div><nav>{pages.map(p=><button key={p.id} onClick={()=>go(p.id)} aria-current={(p.id==='execution'&&!['overview','assets'].includes(page)||page===p.id)?'page':undefined} className={(p.id==='execution'&&!['overview','assets'].includes(page)||page===p.id)?'active':''}><p.icon size={19}/>{p.name}</button>)}</nav><div className="sidebar-bottom"><a href="/reference/demo-plan.html" download><BookOpen size={16}/> 初版设计文档</a><div className="profile"><div>W</div><span>我的工作空间<small>仅自己可见</small></span></div></div></aside>
 {nav&&<button className="nav-shade" aria-label="关闭导航" onClick={()=>setNav(false)}/>}
 <a className="skip-link" href="#workspace-main">跳到工作区</a><div className="main-shell"><header className="topbar"><div className="topbar-left"><button className="icon-btn mobile-menu" aria-label="打开导航" onClick={()=>setNav(true)}><Menu/></button><span className="breadcrumb">我的项目</span><ChevronRight size={14}/><select aria-label="选择项目" value={projectId} disabled={loading} onChange={e=>{setSelectedId('');load(e.target.value)}}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="topbar-actions"><button className="quiet context-toggle" onClick={()=>setContextOpen(v=>!v)}>项目依据</button><button className="quiet" onClick={()=>setLogsOpen(v=>!v)}>运行记录</button><button className="quiet" onClick={()=>load(projectId)} disabled={loading} aria-label="刷新"><RefreshCw size={16}/><span>{loading?'读取中':'刷新'}</span></button><button className="secondary" onClick={()=>projectModal(true)}><Plus size={16}/><span>新建项目</span></button></div></header>
 <div className="work-area"><main id="workspace-main" tabIndex={-1}><div className="page-heading"><div><h1>{titles[page]}</h1><p>{subheads[page]||project?.name}</p></div><div className="heading-actions">{page==='overview'&&<><button className="secondary" disabled={!project||busy} onClick={exportData}><Download size={16}/>导出记录</button><button className="primary" disabled={!project} onClick={()=>projectModal()}><Pencil size={16}/>编辑项目</button></>}{page==='tasks'&&<button className="primary" disabled={!project} onClick={()=>newItem('task',{lane:lane==='offline'?'offline':'online'})}><Plus size={18}/>新建任务</button>}{page==='content'&&<button className="primary" disabled={!project} onClick={()=>newItem('content',{kind:kind==='all'?'topic':kind})}><Plus size={18}/>新建内容</button>}{page==='assets'&&assetSection==='files'&&<button className="primary" disabled={!project} onClick={uploadModal}><Upload size={17}/>上传资料</button>}</div></div>
 {error&&<div role="alert" className="error-panel"><AlertCircle size={20}/><span>{error}</span><button onClick={()=>load(projectId)}>重试</button></div>}
 <Suspense fallback={<div className="panel" role="status">正在打开工作区…</div>}>{loading&&!project?<div className="loading"><Loader2 className="spin"/>正在读取项目资料…</div>:project&&<>
 {!['overview','assets'].includes(page)&&page!=='execution'&&<div className="project-execution-breadcrumb"><button className="secondary" onClick={()=>{setPage('execution');setExecutionOpened(true)}}>返回项目执行中心</button><strong>{project.name}</strong><span>{titles[page]}</span></div>}
 {page==='execution'&&!executionOpened&&<section className="project-picker-grid">{projects.map(p=><button className="project-entry" key={p.id} onClick={async()=>{await load(p.id);setExecutionOpened(true)}}><span>{p.id==='woo-original'?'历史结案项目':'活动项目'}</span><h2>{p.name}</h2><p>{p.goal||p.brief||'进入项目安排物料、人员与宣发'}</p><strong>进入执行工作台</strong></button>)}<button className="project-entry new-project-entry" onClick={()=>projectModal(true)}><Plus size={28}/><h2>创建活动项目</h2></button></section>}
 {page==='execution'&&executionOpened&&<ActivityInformation key={'activity-'+project.id+'-'+(items.find(i=>i.type==='activity_settings')?.revision||0)} project={project} items={items} onSaved={()=>load(projectId)}/>}
 {page==='execution'&&executionOpened&&<ProjectExecution key={project.id} project={project} items={items} onOpen={go} onSaved={()=>load(projectId)}/>}
 {['team','online','offline'].includes(page)&&<ProjectExecution key={project.id+'-'+page} project={project} items={items} section={page} onOpen={go} onSaved={()=>load(projectId)}/>}
 {['poster','offlinePoster','copy','video'].includes(page)&&<div className="execution-subnav"><button className="secondary" onClick={()=>go(page==='offlinePoster'?'offline':'online')}>返回{page==='offlinePoster'?'线下':'线上'}宣发安排</button>{page==='offlinePoster'&&<p className="context-note">线下海报草稿归属当前项目；印制前确认实际尺寸、出血及清晰度。</p>}</div>}
 {page==='assets'&&<div className="workspace-tabs" role="tablist" aria-label="资产管理分类">{assetSections.map(([k,n])=><button role="tab" aria-selected={assetSection===k} key={k} onClick={()=>setAssetSection(k)}>{n}</button>)}</div>}
 {page==='assets'&&assetSection==='members'&&<MemberPool/>}
 {page==='assets'&&assetSection==='materials'&&<MaterialWorkbench catalogOnly key={'pool-'+project.id} project={project} history={[]} onSaved={()=>load(projectId)} onCreateProject={()=>projectModal(true)} onEditHistory={edit}/>}
 {page==='assets'&&assetSection==='ip'&&<PosterWorkbench assetsOnly key={'ip-'+project.id} project={project} items={items} onSaved={()=>load(projectId)}/>}
 {executionTask&&['poster','offlinePoster','copy','video'].includes(page)&&<div className="project-execution-breadcrumb"><strong>当前宣发任务：{executionTask.title}</strong><span>新创作记录将自动关联此任务，发布状态仍需手动确认。</span><button className="secondary" onClick={()=>go(page==='offlinePoster'?'offline':'online')}>返回宣发安排</button></div>}
 {page==='copy'&&<CopywritingWorkbench executionTaskId={executionTask?.id} key={project.id+'-'+(executionTask?.id||'')} project={project} items={items} onSaved={()=>load(projectId)}/>}
 {page==='video'&&<MediaWorkbench executionTaskId={executionTask?.id} key={project.id+'-'+(executionTask?.id||'')} initialKind="video" project={project} items={items} onSaved={()=>load(projectId)} draft={null} onResearch={()=>go('agents')}/>}
 {page==='overview'&&<>
 <section className="campaign-banner"><div className="campaign-copy"><span className="label-dark">{project.id==='woo-original'?'已结案 / 完成版为准':'项目 / 执行跟进'}</span><h2>{project.name}</h2><p>{project.goal||'添加项目目标，开始你的下一棒。'}</p><div className="campaign-meta"><span><Flag size={15}/>{project.brand||'待填写品牌'}</span><span>{project.school||'待填写学校'}</span><button onClick={()=>go('assets')}>查看项目资料 <ChevronRight size={14}/></button></div></div>{project.id==='woo-original'&&<a href="/reference/demo-closeout.html" target="_blank" rel="noreferrer" className="plan-art" aria-label="打开最终结案报告"><img src="/reference/closeout-cover.png" alt="示例大学接力队最终结案报告封面"/><span>完成版结案 · 22页 <ArrowUpRight size={14}/></span></a>}</section>
 <ProjectProductionOverview project={project} items={items} onOpen={()=>{go('execution');setExecutionOpened(true)}}/><div className="section-heading workspace-heading"><h2>工作台记录</h2><span className="mini-label">历史成果与后续制作分别记录</span></div><div className="metrics"><div className="metric"><span>执行完成率 <ClipboardList size={17}/></span><strong>{progress}<small>%</small></strong><div className="progress-track"><i style={{width:progress+'%'}}/></div><p>{done} / {tasks.length} 项已完成</p></div><div className="metric"><span>内容制作 <Clapperboard size={17}/></span><strong>{contents.length}<small>份</small></strong><p>{contents.filter(c=>c.data.status==='published').length} 已发布 · {contents.filter(c=>c.data.status==='review').length} 待审核</p></div><div className="metric"><span>{selectionTotals?'本场已知预算':'历史计划预算'} <Wallet size={17}/></span><strong className="money-stat">{money((selectionTotals?.known_cents??confirmedBudget)/100)}</strong><p>{selectionTotals?selectionTotals.count+'项选配 · '+selectionTotals.unpriced+'项待询价':money(pendingBudget/100)+'待核对'}</p></div><div className="metric"><span>项目资料 <FolderOpen size={17}/></span><strong>{assets.length}<small>份</small></strong><p>{assets.filter(a=>a.data.origin==='结案资料').length} 份结案资料已归档</p></div></div>
 <div className="overview-grid"><section className="panel"><div className="section-heading"><h2>执行待办</h2><button className="text-btn" onClick={()=>go('tasks')}>全部任务 <ChevronRight size={15}/></button></div><div className="compact-tasks">{tasks.filter(t=>t.data.status!=='done').slice(0,5).map(t=><div className="compact-task" key={t.id}><button disabled={busy} className="check-btn" onClick={()=>toggleTask(t)} aria-label={'标记完成 '+t.data.title}/><button className="compact-name" onClick={()=>edit(t)}><strong>{t.data.title}</strong><span>{t.data.lane==='online'?'线上传播':'线下活动'} · {t.data.due||'日期待核对'}</span></button><Badge value={t.data.status}/></div>)}{(!tasks.length||done===tasks.length)&&<Empty title={tasks.length?'这一轮任务已完成':'开始第一项任务'} description="执行看板会记录每一次推进。" action={<button className="secondary" onClick={()=>newItem('task')}>新建任务</button>}/>}</div></section><section className="panel review-panel"><div className="section-heading"><h2>项目核对</h2><span className="mini-label">结案 → 核对</span></div>{project.id==='woo-original'?sourceWarnings.map((s,i)=><div className="review-item" key={s}><span>0{i+1}</span><p>{s}</p></div>):<p className="muted">从简报、任务与实际支出开始，逐步完善项目记录。</p>}<button className="secondary full" onClick={uploadModal}><Upload size={16}/>导入执行与结案资料</button></section></div>
 <div className="section-heading content-heading"><h2>内容记录</h2><button className="text-btn" onClick={()=>go('content')}>进入内容工坊 <ChevronRight size={15}/></button></div><div className="quick-types">{Object.entries(contentKinds).map(([k,v],i)=><button key={k} onClick={()=>{go('content');setKind(k)}}><span className={'type-number tone-'+i}>0{i+1}</span><strong>{v}</strong><ChevronRight size={17}/></button>)}</div>
 <section className="brief-panel"><div className="section-heading"><h2>项目简报</h2><button className="text-btn" onClick={()=>projectModal()}>编辑 <Pencil size={14}/></button></div><p className="preserve">{project.brief||'还没有项目简报。'}</p><p className="source-note"><FileText size={15}/>{project.source_note}</p></section>
 {project.id==='woo-original'&&<details className="history-evidence" onToggle={e=>{if(e.currentTarget.open)setHistoryOpened(true)}}><summary>历史结案成果与来源核对</summary>{historyOpened&&<CloseoutOverview/>}</details>}
 </>}
 {page==='tasks'&&<><label className="concept-toggle"><input type="checkbox" checked={showConcepts} onChange={e=>setShowConcepts(e.target.checked)}/>同时查看早期构想（不作为结案成果）</label><div className="toolbar"><div className="tabs">{[['all','全部任务'],['online','线上'],['offline','线下']].map(([k,v])=><button className={lane===k?'selected':''} key={k} onClick={()=>setLane(k)}>{v}<span>{k==='all'?tasks.length:tasks.filter(t=>t.data.lane===k).length}</span></button>)}</div><label className="search"><Search size={17}/><input placeholder="搜索任务、负责人" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><p className="context-note"><AlertCircle size={15}/>结案记载的执行已归档为完成；新增任务仍由你确认进度。早期构想不会计入默认进度。</p><div className="workspace-tabs" role="tablist" aria-label="任务视图">{[['list','列表'],['board','看板'],['calendar','日历']].map(([k,n])=><button role="tab" aria-selected={taskView===k} key={k} onClick={()=>setTaskView(k)}>{n}</button>)}</div>{taskView!=='board'&&<TaskViews items={filteredTasks} view={taskView} onEdit={edit} onToggle={toggleTask} busy={busy}/>} {taskView==='board'&&<div className="board">{[{name:'待开始',s:['unverified','todo'],class:'waiting'},{name:'进行中',s:['doing','review','ready'],class:'inprogress'},{name:'已完成',s:['done'],class:'finished'}].map(col=><section className={'board-column '+col.class} key={col.name}><header><h2><span className="column-line"/>{col.name}</h2><span>{filteredTasks.filter(t=>col.s.includes(t.data.status)).length}</span></header>{filteredTasks.filter(t=>col.s.includes(t.data.status)).map(taskCard)}{!filteredTasks.some(t=>col.s.includes(t.data.status))&&<div className="column-empty">{col.name==='已完成'?'完成的任务会出现在这里':'暂无任务'}</div>}<button className="add-inline" onClick={()=>newItem('task',{lane:lane==='offline'?'offline':'online',status:col.s[0]==='unverified'?'todo':col.s[0]})}><Plus size={15}/>添加任务</button></section>)}</div>}</>}
 {page==='content'&&<><label className="concept-toggle"><input type="checkbox" checked={showConcepts} onChange={e=>setShowConcepts(e.target.checked)}/>同时查看原案选题参考</label><div className="studio-strip"><Sparkles size={23}/><div><strong>你的内容生产工作台</strong><p>生成结果经你审核采纳后，会保存为这里的草稿。</p></div><button className="secondary" onClick={()=>go('online')}>进入线上宣发</button></div><div className="toolbar wrap"><div className="tabs scroll-tabs"><button className={kind==='all'?'selected':''} onClick={()=>setKind('all')}>全部</button>{Object.entries(contentKinds).map(([k,v])=><button key={k} className={kind===k?'selected':''} onClick={()=>setKind(k)}>{v}</button>)}</div><label className="search"><Search size={17}/><input placeholder="搜索内容" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="content-grid">{filteredContent.map(c=><article className="content-card" key={c.id}><div className={'content-type-header '+c.data.kind}><span>{contentKinds[c.data.kind]}</span>{c.data.kind==='poster'?<ImageIcon size={24}/>:c.data.kind.includes('script')?<Clapperboard size={24}/>:<FileText size={24}/>}</div><div className="content-card-body"><div className="card-top"><Badge value={c.data.status}/><button className="icon-btn" aria-label={'编辑 '+c.data.title} onClick={()=>edit(c)}><MoreHorizontal size={20}/></button></div><button className="content-title" onClick={()=>edit(c)}>{c.data.title}</button><p className="clamp-three">{c.data.body||'还没有内容，点击开始编辑。'}</p><div className="content-card-footer"><span>{c.data.channel||'渠道待定'}</span><button className="text-btn" onClick={()=>edit(c)}>编辑稿件 <Pencil size={14}/></button></div></div></article>)}</div>{!filteredContent.length&&<Empty title="给下一个好点子留个位置" description="新建内容卡片，选择海报、脚本或图文，保存你的第一份草稿。" action={<button className="primary" onClick={()=>newItem('content',{kind:kind==='all'?'topic':kind})}>新建内容</button>}/>}</>}
 {page==='assets'&&assetSection==='files'&&<><div className="asset-intro"><div><h2>完成版结案，优先作为项目依据。</h2><p>原始策划保留为历史构想；执行事实优先引用结案页码。</p></div><span><FolderOpen size={22}/>{assets.length} 份资料</span></div><div className="toolbar"><div className="tabs scroll-tabs">{['all','原始策划','执行资料','结案资料','其他'].map(k=><button key={k} className={kind===k?'selected':''} onClick={()=>setKind(k)}>{k==='all'?'全部资料':k}</button>)}</div></div><div className="asset-list">{assets.filter(a=>kind==='all'||a.data.origin===kind).sort((a,b)=>(a.data.origin==='结案资料'?-1:1)-(b.data.origin==='结案资料'?-1:1)).map(a=><article className="asset-row" key={a.id}><div className="file-icon"><FileText size={26}/></div><div className="asset-info"><h3>{a.data.title}</h3><p>{a.data.category} · {a.data.origin} · {size(a.data.size||0)}{a.data.review_status&&' · '+({approved:'素材已审核',rejected:'素材已退回',awaiting_review:'素材待审核'} as any)[a.data.review_status]}</p><details className="asset-notes"><summary>来源说明与资料摘要</summary><p>{a.data.notes}</p></details></div><div className="asset-actions"><button className="secondary" onClick={()=>{setSelectedId(a.id);setAssetReview(a);setAssetNote('');setAssetDecision('approved');setFormError('')}}>审核素材</button><a className="secondary" href={'/api/files/'+a.id} target="_blank" rel="noreferrer"><Download size={15}/>查看文件</a><button className="icon-btn" aria-label={'编辑资料 '+a.data.title} onClick={()=>edit(a)}><Pencil size={17}/></button>{!['a-original','a-closeout'].includes(a.id)&&<button className="icon-btn" aria-label={'删除资料 '+a.data.title} onClick={()=>{setConfirm(a);setFormError('')}}><Trash2 size={17}/></button>}</div></article>)}</div>{!assets.some(a=>kind==='all'||a.data.origin===kind)&&<Empty title="这个分类还没有资料" description="可以上传策划、图片、表格与结案材料。每个文件不超过20MB。" action={<button className="primary" onClick={uploadModal}>上传资料</button>}/>}<p className="context-note">新增附件保存为项目资产；本次生成不会自动读取新上传附件。乐虎结案及原策划已单独整理入库，新增资料请先核对摘录。</p></>}
 {page==='budget'&&<ProjectExecution key={'ready-'+project.id} project={project} items={items} section="materials" onOpen={go} onSaved={()=>load(projectId)}/>}
 {page==='budget'&&<MaterialWorkbench key={project.id} project={project} history={budgets} onSaved={()=>load(projectId)} onCreateProject={()=>projectModal(true)} onEditHistory={edit}/>}
 {['poster','offlinePoster'].includes(page)&&<PosterWorkbench executionTaskId={executionTask?.id} usage={page==='offlinePoster'?'offline':'online'} key={project.id+'-'+page+'-'+(executionTask?.id||'')} project={project} items={items} onSaved={()=>load(projectId)}/>}
 {page==='agents'&&<AgentWorkbench key={project.id} project={project} items={items} onSaved={()=>load(projectId)} onSelectRun={setSelectedId}/>}
 </>}</Suspense>
 <footer className="page-footer"><span>WOO STUDIO / CAMPUS MARKETING</span><span>策划 · 内容 · 执行 · 复盘</span></footer></main><aside className={'project-context '+(contextOpen?'open':'')} aria-label="项目资料上下文"><div className="section-heading"><h2>项目依据</h2><button className="icon-btn context-toggle" aria-label="关闭项目依据" onClick={()=>setContextOpen(false)}><X size={18}/></button></div><strong>{project?.name||'正在读取'}</strong><p className="context-note">{project?.source_note||'待确认资料来源'}</p>{project?.id==='woo-original'&&<><a href="/reference/demo-closeout.html" target="_blank" rel="noreferrer">查看最终结案报告</a><h3>保留的冲突</h3><ul>{sourceWarnings.map(w=><li key={w}>{w}</li>)}</ul></>}{selectedItem&&<section className="selected-context"><h3>当前对象</h3><strong>{selectedItem.data.title||agents.find(a=>a.key===selectedItem.data.key)?.name||selectedItem.type}</strong><p>{selectedItem.id}</p><p>记录版本 {selectedItem.revision} · {status(selectedItem.data.review_status||selectedItem.data.status||'待核对')}</p>{selectedItem.data.source&&<p>来源：{selectedItem.data.source}</p>}{selectedItem.data.source_set?.map((s:any)=><p key={s.id}>{s.id} · {s.version}{s.page?' · '+s.page:''}</p>)}</section>}<h3>资料分层</h3><ul><li>KB01 结案事实 · 按页检索已接入</li><li>KB02 品牌制作规范 · 正式 IP 原图待核准</li><li>KB03 历史策划 · 用于差异比较</li><li>KB04 内部渠道模板 · 官方限制另行核实</li><li>KB05 项目运行 · 结构化版本快照</li></ul><p className="context-note">四类静态知识库已接入 Dify；预算、任务和审核状态按当前项目读取，不由模型改写。</p></aside></div>{logsOpen&&<section className="runtime-drawer" aria-label="运行日志"><div className="section-heading"><h2>运行日志</h2><button className="icon-btn" aria-label="关闭运行日志" onClick={()=>setLogsOpen(false)}><X size={18}/></button></div>{items.filter(i=>i.type==='run').slice(-8).reverse().map(i=><article key={i.id}><strong>{agents.find(a=>a.key===i.data.key)?.name}</strong><span>{i.data.review_status==='approved'?'已批准':i.data.review_status==='rejected'?'已退回':i.data.status}</span><small>{i.data.workflow_run_id||i.id}</small></article>)}{!items.some(i=>i.type==='run')&&<p>当前项目暂无运行记录。</p>}</section>}</div>
 {assetReview&&<Modal title="素材人工审核" onClose={()=>{if(!busy)setAssetReview(null)}}><form onSubmit={reviewAsset}><p className="context-note">{assetReview.data.title} · 第 {assetReview.revision} 版</p><a className="secondary" href={'/api/files/'+assetReview.id} target="_blank" rel="noreferrer">打开文件核对</a><p className="context-note">请核对文字、日期、IP、授权、画面及二维码。批准记录仅表示你对该版素材的审核；文字排版工作稿仍需完成印前检查。</p><Field label="审核决定"><select value={assetDecision} onChange={e=>setAssetDecision(e.target.value)}><option value="approved">人工批准</option><option value="rejected">退回修改</option></select></Field><Field label="审核说明（至少5字）"><textarea required minLength={5} maxLength={2000} value={assetNote} onChange={e=>setAssetNote(e.target.value)} rows={4}/></Field>{formError&&<p className="form-error" role="alert">{formError}</p>}<button className="primary" disabled={busy||assetNote.trim().length<5}>{busy?'保存中…':'记录本次审核'}</button></form></Modal>}
 {toast&&<div className="toast" role="status"><CheckCircle2 size={18}/>{toast}</div>}
 {editor&&<Modal title={editor.type==='agent'?agents.find(a=>a.key===form.key)?.name+' · 接入说明':(editor.item?'编辑':'新建')+({task:'任务',content:'内容',budget:'物料',asset:'资料'} as any)[editor.type]} onClose={()=>{if(!busy)setEditor(null)}}><form onSubmit={save}><div className="form-grid">
 {editor.type!=='agent'&&<Field label="标题" wide>{input('title','输入标题','text',true)}</Field>}
 {editor.type==='task'&&<><Field label="任务类型">{select('lane',{online:'线上传播',offline:'线下活动'})}</Field><Field label="阶段">{select('phase',{'调研':'调研','预热':'预热','爆发':'爆发','延热':'延热','复盘':'复盘'})}</Field><Field label="状态">{select('status',taskStatuses)}</Field>{editor.item?.data.status==='done'&&form.status!=='done'&&<Field label="撤回完成理由（至少5字）" wide><textarea required minLength={5} maxLength={2000} value={form.change_reason||''} onChange={e=>set('change_reason',e.target.value)}/></Field>}<Field label="负责人">{input('owner','待分配')}</Field><Field label="截止日期">{input('due','','date')}</Field><Field label="资料来源">{input('source')}</Field><Field label="执行说明" wide><textarea rows={5} value={form.notes} onChange={e=>set('notes',e.target.value)}/></Field></>}
 {editor.type==='content'&&<><Field label="内容类型">{select('kind',contentKinds)}</Field><Field label="状态">{select('status',contentStatuses)}</Field><Field label="发布渠道">{input('channel','如：抖音 / 小红书')}</Field><Field label="关联任务">{select('task_id',{'':'不关联任务',...Object.fromEntries(tasks.map(t=>[t.id,t.data.title]))})}</Field><Field label="稿件内容" wide><textarea rows={10} placeholder="写下选题、文案或脚本…" value={form.body} onChange={e=>set('body',e.target.value)}/></Field><Field label="来源" wide>{input('source')}</Field></>}
 {editor.type==='budget'&&<><Field label="类别">{select('category',Object.fromEntries(['场地搭建','周边物料','设备租赁','借用物料','杂费','其他'].map(s=>[s,s])))}</Field><Field label="状态">{select('status',{unverified:'待核对',approved:'已批准',rejected:'已驳回',awaiting_review:'待审核',confirmed:'已确认',ordered:'已订购',received:'已到货'})}</Field><Field label="数量">{input('quantity','','number',true)}</Field><Field label="单位">{input('unit','件 / 套 / 批','text',true)}</Field><Field label="单价（元）">{input('unit_price','','number',true)}</Field><Field label="运费（元）">{input('shipping','','number',true)}</Field><Field label="实际支出（元，可留空）">{input('actual_amount','未登记','number')}</Field><Field label="规格">{input('spec','如：300 × 500 cm')}</Field><Field label="来源" wide>{input('source')}</Field><Field label="备注" wide><textarea rows={3} value={form.notes} onChange={e=>set('notes',e.target.value)}/></Field><div className="calculation wide">计划金额 <strong>{money(plannedCents(form)/100)}</strong></div></>}
 {editor.type==='asset'&&<><Field label="分类">{select('category',Object.fromEntries(assetCategories.map(s=>[s,s])))}</Field><Field label="资料属性">{select('origin',Object.fromEntries(['原始策划','执行资料','结案资料','其他'].map(s=>[s,s])))}</Field><Field label="备注" wide><textarea rows={4} value={form.notes} onChange={e=>set('notes',e.target.value)}/></Field></>}
 {editor.type==='agent'&&<><div className="notice wide"><AlertCircle size={17}/><p>这里保存接入计划。实际调用需要后端适配与密钥配置；保存后仍显示“未接入”。</p></div><Field label="计划使用的平台">{input('provider','Dify / Coze / 自建')}</Field><Field label="应用或工作流标识（非密钥）">{input('workflow_id','选填')}</Field><Field label="输入输出与接入备注" wide><textarea rows={4} value={form.notes} onChange={e=>set('notes',e.target.value)} placeholder="填写工作流要求的输入、输出字段与版本。请勿填写 API Key。"/></Field><div className="contract wide"><h3>统一调用约定</h3><code>POST /api/agents/{form.key}/run</code><pre>{JSON.stringify({schema_version:'1.0',project_id:projectId,project_revision:project?.revision,agent_key:form.key,request_id:'每次请求的唯一标识',selected_asset_ids:[],input:{brief:'项目简报',instruction:'本次任务要求'}},null,2)}</pre><p>当前返回 501 / AGENT_NOT_CONNECTED。未来结果先进入审核，再由你采纳到内容卡片。</p></div></>}
 </div>{formError&&<p className="form-error" role="alert">{formError}</p>}<div className="modal-actions">{editor.item&&!['a-original','a-closeout'].includes(editor.item.id)&&<button type="button" className="danger-text" disabled={busy} onClick={()=>{setConfirm(editor.item!);setEditor(null);setFormError('')}}><Trash2 size={15}/>删除</button>}<button type="button" className="secondary" disabled={busy} onClick={()=>setEditor(null)}>取消</button><button className="primary" disabled={busy}>{busy?<Loader2 size={16} className="spin"/>:<Check size={16}/>}保存{editor.type==='agent'?'说明':''}</button></div></form></Modal>}
 {projectEdit&&<Modal title={projectNew?'新建项目':'编辑项目简报'} onClose={()=>{if(!busy)setProjectEdit(false)}}><form onSubmit={saveProject}><div className="form-grid">{projectNew&&<><Field label="活动模板" wide><select value={form.template_id||'blank'} onChange={e=>{set('template_id',e.target.value);set('copy_from','')}}>{Object.entries(activityTemplates).map(([k,v])=><option key={k} value={k}>{v.name}</option>)}</select></Field>{form.template_id&&form.template_id!=='blank'&&<p className="context-note">{activityTemplates[form.template_id as keyof typeof activityTemplates].tasks.length}项可调整任务 · {activityTemplates[form.template_id as keyof typeof activityTemplates].materials.length}种建议物料；建议岗位：{activityTemplates[form.template_id as keyof typeof activityTemplates].roles.join('、')}</p>}<Field label="或复制已有项目的安排" wide><select value={form.copy_from||''} onChange={e=>{const source=projects.find(p=>p.id===e.target.value);setForm({...form,copy_from:e.target.value,template_id:'blank',brand:source?.brand||form.brand,school:source?.school||form.school,goal:source?.goal||form.goal})}}><option value="">不复制已有项目</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><p className="context-note">模板任务与物料均可调整。复制仅复用任务结构和物料需求，不复制日期、负责人、完成状态或创作成果。</p></>}<Field label="项目名称" wide>{input('name','项目名称','text',true)}</Field>{projectNew&&<><Field label="活动时间">{input('time')}</Field><Field label="活动地点">{input('place')}</Field><Field label="联系方式">{input('contact')}</Field><Field label="必须保留的文字" wide><textarea rows={3} maxLength={500} value={form.mandatory||''} onChange={e=>set('mandatory',e.target.value)}/></Field></>}<Field label="品牌">{input('brand')}</Field><Field label="学校 / 场景">{input('school')}</Field><Field label="核心目标" wide>{input('goal')}</Field><Field label="项目简报" wide><textarea rows={6} value={form.brief} onChange={e=>set('brief',e.target.value)}/></Field><Field label="资料版本说明" wide><textarea rows={3} value={form.source_note} onChange={e=>set('source_note',e.target.value)}/></Field><Field label="原案标称预算（元，可留空）">{input('reference_budget','','number')}</Field></div>{formError&&<p className="form-error">{formError}</p>}<div className="modal-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setProjectEdit(false)}>取消</button><button className="primary" disabled={busy}>{busy?'保存中…':'保存项目'}</button></div></form></Modal>}
 {uploading&&<Modal title="上传项目资料" onClose={()=>{if(!busy)setUploading(false)}}><form onSubmit={upload}><div className="upload-zone"><Upload size={28}/><strong>{file?file.name:'选择你的项目文件'}</strong><span>PDF、文档、图片、表格等 · 每个文件不超过20MB</span><input type="file" aria-label="选择上传文件" required onChange={e=>{const f=e.target.files?.[0]||null;setFile(f);if(f&&!form.title)set('title',f.name)}}/></div><div className="form-grid"><Field label="资料名称" wide>{input('title','默认使用文件名')}</Field><Field label="分类">{select('category',Object.fromEntries(assetCategories.map(s=>[s,s])))}</Field><Field label="资料属性">{select('origin',Object.fromEntries(['原始策划','执行资料','结案资料','其他'].map(s=>[s,s])))}</Field><Field label="备注" wide><textarea rows={3} value={form.notes} onChange={e=>set('notes',e.target.value)}/></Field></div>{formError&&<p className="form-error">{formError}</p>}<div className="modal-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setUploading(false)}>取消</button><button className="primary" disabled={busy}>{busy?'上传中…':'保存资料'}</button></div></form></Modal>}
 {confirm&&<Modal title="删除这条记录？" onClose={()=>{if(!busy)setConfirm(null)}}><p className="delete-message">将删除“{confirm.data.title||confirm.data.key}”。{confirm.type==='asset'?'对应上传文件也会删除。':'此操作不能撤销。'}</p>{formError&&<p className="form-error">{formError}</p>}<div className="modal-actions"><button className="secondary" disabled={busy} onClick={()=>setConfirm(null)}>取消</button><button className="danger" disabled={busy} onClick={remove}>{busy?'删除中…':'确认删除'}</button></div></Modal>}
 </div>
}
