'use client';
import {useEffect,useRef,useState,useMemo} from 'react';
import {activityDefaults} from '@/lib/activity';
import type {Item,Project} from '@/lib/model';
import type {PosterBrief} from '@/lib/poster-contract';
import {festivalGroups,posterStyles,posterVariants} from '@/lib/poster-options';
import {paintPoster} from '@/lib/poster-canvas';
import {requestId} from '@/lib/request-id';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogHeader,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Upload,Trash2,Check,Loader2,Download,ImagePlus} from 'lucide-react';
async function api(url:string,data?:unknown,method='POST'){const r=await fetch(url,data===undefined?undefined:{method,headers:{'Content-Type':'application/json','X-WOO-Stream':'1'},body:JSON.stringify(data)});const d:any=await r.json();if(!r.ok||d._http_status>=400)throw Error(d.error||'操作未完成');return d}
function PosterCard({slot,brief,batchId,projectId,onSaved}:{slot:any;brief:PosterBrief;batchId:string;projectId:string;onSaved:()=>void}){const canvas=useRef<HTMLCanvasElement>(null);const [error,setError]=useState(''),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState(''),[saved,setSaved]=useState(''),[rendering,setRendering]=useState(true);useEffect(()=>{let gone=false;setError('');setSaveError('');setSaved('');setRendering(true);if(slot.asset_id&&canvas.current){const scratch=document.createElement('canvas');paintPoster(scratch,'/api/files/'+slot.asset_id+'?inline=1',brief,slot.slot).then(()=>{if(gone||!canvas.current)return;canvas.current.width=scratch.width;canvas.current.height=scratch.height;canvas.current.getContext('2d')?.drawImage(scratch,0,0);setRendering(false)}).catch(e=>{if(!gone){setError(e.message);setRendering(false)}})}return()=>{gone=true}},[slot.asset_id,brief,slot.slot]);async function archive(){if(!canvas.current||rendering||error)return;setSaving(true);setSaveError('');try{const d=await api('/api/posters/export',{project_id:projectId,batch_id:batchId,slot:slot.slot,brief,png:canvas.current.toDataURL('image/png')});setSaved(d.id);onSaved()}catch(e){setSaveError((e as Error).message)}finally{setSaving(false)}}
 return <article className="poster-result"><div className="section-heading"><h3>{slot.slot+1} · {posterVariants[slot.slot]}</h3><span className="badge">{slot.asset_id?'待审核':({pending:'待生成',submitting:'生成中',unknown:'结果待核对',download_pending:'待保存'} as any)[slot.status]||slot.status}</span></div>{slot.asset_id?<canvas ref={canvas} aria-label={brief.headline+'，'+posterVariants[slot.slot]+'海报预览'}/>:<div className="poster-placeholder" style={{aspectRatio:brief.ratio.replace(':','/')}}>{slot.status==='submitting'?<Loader2 className="spin"/>:<ImagePlus/>}<p>{slot.error||'画面将在这里显示'}</p></div>}{error&&<p className="form-error" role="alert">{error}</p>}{saveError&&<p className="form-error" role="alert">{saveError}</p>}{slot.asset_id&&!error&&<div className="poster-result-actions">{saved?<a className="secondary" href={'/api/files/'+saved} download><Download size={16}/>下载海报 PNG</a>:<button className="secondary" disabled={rendering||saving} onClick={archive}><Download size={16}/>{saving?'正在准备文件…':'准备 PNG 下载'}</button>}<button className="secondary" disabled={saving||!!saved||rendering} onClick={archive}>{saving?'正在归档':saved?'已存入待审核资产':'保存到资产库'}</button></div>}{slot.status==='download_pending'&&<button className="secondary" onClick={async()=>{try{await api('/api/media/'+batchId+'-'+slot.slot,{project_id:projectId});location.reload()}catch(e){setError((e as Error).message)}}}>保存已生成的原图</button>}</article>}
export default function PosterWorkbench({project,items,onSaved,assetsOnly=false,usage='online',executionTaskId=''}:{executionTaskId?:string;project:Project;items:Item[];onSaved:()=>void;assetsOnly?:boolean;usage?:'online'|'offline'}){
 const activity=activityDefaults(project,items),activityRevision=items.find(i=>i.type==='activity_settings')?.revision||0;
 const [assets,setAssets]=useState<Item[]>([]),[assetId,setAssetId]=useState(''),[festival,setFestival]=useState(activityRevision?'自定义主题':'劳动节'),[prompt,setPrompt]=useState(activityRevision?'请为'+activity.event_name+'制作活动海报，结合所选IP与校园氛围。':'请制作一张五一海报，突出校园活力与劳动的快乐。'),[headline,setHeadline]=useState(activityRevision?activity.event_name.slice(0,60):'五一，快乐动起来'),[time,setTime]=useState(activity.time),[place,setPlace]=useState(activity.place),[contact,setContact]=useState(activity.contact),[mandatory,setMandatory]=useState(activity.mandatory),[style,setStyle]=useState('brand'),[ratio,setRatio]=useState<PosterBrief['ratio']>('3:4'),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[phase,setPhase]=useState(''),[batch,setBatch]=useState<any>(null),[removing,setRemoving]=useState<Item|null>(null),[history,setHistory]=useState<any[]>([]);
 const upload=useRef<HTMLInputElement>(null),alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[]);
 async function loadAssets(){const d=await api('/api/posters/ip?project_id='+encodeURIComponent(project.id));setAssets(d.assets);setAssetId(old=>old&&d.assets.some((a:any)=>a.id===old)?old:d.assets[0]?.id||'')}
 useEffect(()=>{loadAssets().catch(e=>setError(e.message));const last=items.filter(i=>i.type==='poster_batch'&&(i.data.brief?.usage||'online')===usage&&(!executionTaskId||i.data.brief?.execution_task_id===executionTaskId)).at(-1);if(last)refresh(last.id).catch(e=>setError(e.message))},[project.id]);
 useEffect(()=>setHistory(items.filter(i=>i.type==='poster_batch'&&(i.data.brief?.usage||'online')===usage&&(!executionTaskId||i.data.brief?.execution_task_id===executionTaskId)).slice().reverse()),[items]);
 async function refresh(id:string){const d=await api('/api/posters/'+id+'?project_id='+encodeURIComponent(project.id));if(alive.current)setBatch(d);return d}
 async function generateRemaining(id:string){for(let slot=0;slot<4;slot++){if(!alive.current)return;const current=await refresh(id);if(current.slots[slot].status!=='pending')continue;setPhase('正在生成 '+(slot+1)+' / 4 · '+posterVariants[slot]+'，请保持页面打开');try{await api('/api/posters/'+id,{project_id:project.id,slot})}catch(e){setError((e as Error).message);await refresh(id);return}await refresh(id)}const final=await refresh(id);setPhase(final.slots.every((s:any)=>s.asset_id)?'四张结果已返回，请检查画面与文字。':'部分海报尚未完成，请查看每张任务状态。')}
 async function start(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setPhase('正在策划四个构图方向…');try{const b={activity_revision:activityRevision,execution_task_id:executionTaskId,usage,project_id:project.id,project_revision:project.revision,request_id:requestId(),asset_id:assetId,festival,prompt,headline,time,place,contact,mandatory,style,ratio,consent};const d=await api('/api/posters',b);setBatch(d);await generateRemaining(d.id)}catch(e){setError((e as Error).message);setPhase('')}finally{setBusy(false);setConsent(false);onSaved()}}
 async function importIP(file:File){if(!['image/png','image/jpeg'].includes(file.type)||file.size>8*1024*1024){setError('请导入8MB以内的 PNG 或 JPEG IP 图片。');return}setBusy(true);setError('');try{const f=new FormData();f.set('project_id',project.id);f.set('file',file);f.set('title',file.name.replace(/\.[^.]+$/,''));f.set('category','IP与视觉');f.set('origin','其他');f.set('notes','用户导入的IP创作参考');const r=await fetch('/api/files',{method:'POST',body:f}),d:any=await r.json();if(!r.ok)throw Error(d.error);await loadAssets();setAssetId(d.id);onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false);if(upload.current)upload.current.value=''}}
 const resultBrief=batch?.brief;const [editCopy,setEditCopy]=useState<any>(null);useEffect(()=>setEditCopy(null),[batch?.id]);const outputBrief=useMemo(()=>resultBrief?{...resultBrief,...editCopy}:null,[resultBrief,editCopy]);
 if(assetsOnly)return <section className="panel"><h2>共享 IP 数字资产池</h2><p className="context-note">所有活动可直接选用这里的IP。导入一次即可复用；删除会从共享池移除。</p>{error&&<p className="form-error" role="alert">{error}</p>}<fieldset disabled={busy}><legend>IP 数字资产</legend><div className="poster-assets"><button type="button" aria-pressed={!assetId} className={'poster-asset '+(!assetId?'selected':'')} onClick={()=>setAssetId('')}><ImagePlus/><span>不使用 IP</span></button>{assets.map(a=><div className={'poster-asset '+(assetId===a.id?'selected':'')} key={a.id}><button type="button" aria-pressed={assetId===a.id} onClick={()=>setAssetId(a.id)}><img src={'/api/files/'+a.id+'?inline=1'} alt={a.data.title}/><span>{a.data.title}</span>{assetId===a.id&&<Check size={16}/>}</button><button type="button" className="poster-asset-delete" aria-label={'删除IP资产 '+a.data.title} onClick={()=>setRemoving(a)}><Trash2 size={15}/></button></div>)}<button type="button" className="poster-asset" onClick={()=>upload.current?.click()}><Upload/><span>导入 IP</span></button></div><input ref={upload} type="file" accept="image/png,image/jpeg" hidden onChange={e=>{if(e.target.files?.[0])importIP(e.target.files[0])}}/><p className="context-note">原案三视图仅作创作参考。支持 PNG / JPEG，单张不超过8MB。</p></fieldset> <AlertDialog open={!!removing} onOpenChange={open=>{if(!open)setRemoving(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>删除此 IP 资产？</AlertDialogTitle><AlertDialogDescription>将删除“{removing?.data.title}”及上传文件。已提交海报任务保留自己的参考快照。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction onClick={async()=>{if(!removing)return;try{await api('/api/records',{id:removing.id,project_id:removing.project_id,revision:removing.revision},'DELETE');if(assetId===removing.id)setAssetId('');await loadAssets();onSaved()}catch(e){setError((e as Error).message)}setRemoving(null)}}>删除资产</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></section>;
 return <div className="poster-workbench"><form className="poster-form panel" onSubmit={start}><div className="section-heading"><h2>海报创作</h2><span className="mini-label">一次生成 4 个方向</span></div><fieldset disabled={busy}><legend>1 选择 IP 资产</legend><div className="poster-assets"><button type="button" aria-pressed={!assetId} className={'poster-asset '+(!assetId?'selected':'')} onClick={()=>setAssetId('')}><ImagePlus/><span>不使用 IP</span></button>{assets.map(a=><div className={'poster-asset '+(assetId===a.id?'selected':'')} key={a.id}><button type="button" aria-pressed={assetId===a.id} onClick={()=>setAssetId(a.id)}><img src={'/api/files/'+a.id+'?inline=1'} alt={a.data.title}/><span>{a.data.title}</span>{assetId===a.id&&<Check size={16}/>}</button><button type="button" className="poster-asset-delete" aria-label={'删除IP资产 '+a.data.title} onClick={()=>setRemoving(a)}><Trash2 size={15}/></button></div>)}<button type="button" className="poster-asset" onClick={()=>upload.current?.click()}><Upload/><span>导入 IP</span></button></div><input ref={upload} type="file" accept="image/png,image/jpeg" hidden onChange={e=>{if(e.target.files?.[0])importIP(e.target.files[0])}}/><p className="context-note">原案三视图仅作创作参考。支持 PNG / JPEG，单张不超过8MB。</p></fieldset>
 <fieldset disabled={busy}><legend>2 主题与创意</legend><div className="form-grid"><label className="field"><span>节日 / 活动预设</span><select value={festival} onChange={e=>{const f=e.target.value;setFestival(f);if(f!=='自定义主题'){setPrompt('请制作一张'+f+'海报，结合所选IP与节日氛围。');setHeadline(f==='劳动节'?'五一，快乐动起来':f+' · 快乐不停')}}}>{Object.entries(festivalGroups).map(([g,values])=><optgroup label={g} key={g}>{values.map(v=><option key={v}>{v}</option>)}</optgroup>)}<option>自定义主题</option></select></label><label className="field"><span>画面比例</span><select value={ratio} onChange={e=>setRatio(e.target.value as any)}><option value="3:4">竖版 3:4</option><option value="9:16">竖屏 9:16</option><option value="1:1">方形 1:1</option><option value="16:9">横版 16:9</option></select></label></div><label className="field"><span>创意要求（可直接使用预设）</span><textarea value={prompt} maxLength={1500} rows={3} onChange={e=>setPrompt(e.target.value)} placeholder="例如：请制作一张十一海报，Woo虎在校园里接力，画面热闹但不要拥挤。"/></label></fieldset>
 <fieldset disabled={busy}><legend>3 海报信息</legend><label className="field"><span>主标题</span><input required maxLength={60} value={headline} onChange={e=>setHeadline(e.target.value)}/></label><div className="form-grid"><label className="field"><span>时间（选填）</span><input maxLength={100} value={time} onChange={e=>setTime(e.target.value)} placeholder="例如：5月1日 14:00–17:00"/></label><label className="field"><span>地点（选填）</span><input maxLength={100} value={place} onChange={e=>setPlace(e.target.value)} placeholder="例如：示例大学西校园6B小广场"/></label><label className="field"><span>联系方式（选填）</span><input maxLength={100} value={contact} onChange={e=>setContact(e.target.value)} placeholder="电话、微信或咨询方式"/></label></div><label className="field"><span>您希望海报中必须保留的文字信息是什么？</span><textarea rows={4} maxLength={500} value={mandatory} onChange={e=>setMandatory(e.target.value)} placeholder="逐行填写，例如：\nWoo虎！接住这一棒\n毕业接力，能量不停\n主办：新闻与传播学院"/></label><p className="context-note">这些文字由工作台排版，原文保留；空白信息不会自动编造。</p></fieldset>
 <fieldset disabled={busy}><legend>4 创意风格</legend><div className="poster-styles">{posterStyles.map(s=><button type="button" key={s.id} aria-pressed={style===s.id} className={style===s.id?'selected':''} onClick={()=>setStyle(s.id)}><strong>{s.name}</strong><span>{s.description}</span></button>)}</div></fieldset><label className="poster-consent"><input type="checkbox" checked={consent} disabled={busy} onChange={e=>setConsent(e.target.checked)}/>我确认上述创作要求及IP使用权，同意通过 Dify 生成4张画面，使用模型额度。结果均为待审核草稿。</label><button className="primary poster-start" disabled={busy||!consent}>{busy?<><Loader2 className="spin" size={18}/>{phase}</>:'开始创作 · 4 张海报'}</button>{busy&&<p className="context-note">参考图生成通常每张约2分钟，四张依次生成。请保持此页面打开；已有结果会保存，不重复提交。</p>}</form>
 <section className="poster-output"><div className="section-heading"><h2>创作结果</h2>{history.length>0&&<select aria-label="查看历史海报任务" value={batch?.id||''} disabled={busy} onChange={async e=>{setError('');setPhase('');if(!e.target.value){setBatch(null);return}try{await refresh(e.target.value)}catch(err){setError((err as Error).message)}}}><option value="">选择历史任务</option>{history.map(h=><option key={h.id} value={h.id}>{h.data.brief?.headline||h.id}</option>)}</select>}</div>{error&&<p className="form-error" role="alert">{error}</p>}{phase&&<p role="status">{phase}</p>}{!batch&&<div className="poster-empty"><ImagePlus size={36}/><h3>四张海报，在这里比较</h3><p>选择 IP 和主题，填写必留文字，再开始创作。</p></div>}{batch?.error&&<p className="form-error">{batch.error}</p>}{batch?.plan&&<details className="panel"><summary>查看设计说明</summary><p className="preserve">{batch.plan.result.body}</p></details>}{outputBrief&&<><details className="panel"><summary>修改结果文字（不重新生图）</summary>{[['headline','主标题',60],['mandatory','必留文字',500],['time','时间',100],['place','地点',100],['contact','联系方式',100]].map(([k,label,max])=><label className="field" key={String(k)}><span>{label}</span><textarea maxLength={Number(max)} rows={k==='mandatory'?4:2} value={outputBrief[k as keyof PosterBrief] as string} onChange={e=>setEditCopy((old:any)=>({...old,[k]:e.target.value}))}/></label>)}</details><div className="poster-results">{(batch.slots||[0,1,2,3].map(slot=>({slot,status:'pending'}))).map((s:any)=><PosterCard key={batch.id+'-'+s.slot} slot={s} brief={outputBrief} batchId={batch.id} projectId={project.id} onSaved={onSaved}/>)}</div>{!busy&&batch.status==='ready'&&batch.slots.some((s:any)=>s.status==='pending')&&<button className="secondary" onClick={async()=>{setBusy(true);setError('');try{await generateRemaining(batch.id)}catch(e){setError((e as Error).message);setPhase('')}finally{setBusy(false);onSaved()}}}>继续生成尚未提交的海报</button>}</>}</section>
 <AlertDialog open={!!removing} onOpenChange={open=>{if(!open)setRemoving(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>删除此 IP 资产？</AlertDialogTitle><AlertDialogDescription>将删除“{removing?.data.title}”及上传文件。已提交海报任务保留自己的参考快照。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction onClick={async()=>{if(!removing)return;try{await api('/api/records',{id:removing.id,project_id:removing.project_id,revision:removing.revision},'DELETE');if(assetId===removing.id)setAssetId('');await loadAssets();onSaved()}catch(e){setError((e as Error).message)}setRemoving(null)}}>删除资产</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>
}
