'use client';
import {useState,useEffect,useRef} from 'react';
import type {ProductionArtifact} from '@/lib/production-server';
import {copyTags} from '@/lib/copywriting';
import {requestId} from '@/lib/request-id';
export default function ProductionArtifactEditor({artifact,onSave,brandAssets=[]}:{artifact:ProductionArtifact;brandAssets?:any[];onSave:(data:any)=>Promise<void>}){
 const [title,setTitle]=useState(''),[body,setBody]=useState(''),[tags,setTags]=useState<string[]>([]),[reason,setReason]=useState(''),[logo,setLogo]=useState(''),[qr,setQr]=useState(''),[busy,setBusy]=useState(false),pending=useRef(requestId());
 useEffect(()=>{setTitle(artifact.copy?.title||artifact.layout?.headline||'');setBody(artifact.copy?.body||artifact.observation||artifact.layout?.details.join('\n')||'');setTags([...(artifact.copy?.tags||[])]);setLogo(artifact.layout?.logo?.asset_id||'');setQr(artifact.layout?.qr?.url||'');setReason('');pending.current=requestId()},[artifact.id]);
 useEffect(()=>{pending.current=requestId()},[title,body,tags,reason,logo,qr]);
 async function save(){setBusy(true);try{await onSave({request_id:pending.current,reason,...(artifact.copy?{title,body,tags}:artifact.layout?{headline:title,details:body.split('\n').filter(v=>v.trim()),logo_asset_id:logo,qr_url:qr}:{observation:body})})}finally{setBusy(false)}}
 return <details><summary>{artifact.kind==='observation'?'纠正图片观察':'直接修改文字'} · 不调用模型</summary>{artifact.kind==='observation'?<p className="context-note">只描述图片可见内容。纠正后不会自动覆盖已生成文案；依赖旧观察的配文需要人工核对、保存改字版本并重新批准。</p>:<p className="context-note">保存新产物版本，保留背景像素和原运行；原文件与审批可查看。新版本需要重新审核，文案缺少固定事实时会明确补入。</p>}{artifact.kind!=='observation'&&<label className="field"><span>标题</span><input maxLength={artifact.layout?150:200} value={title} onChange={e=>setTitle(e.target.value)}/></label>}<label className="field"><span>{artifact.layout?'详情文字（每行一条；固定事实与必留文字必须保留）':artifact.kind==='observation'?'核对后的画面观察':'正文'}</span><textarea rows={7} maxLength={artifact.kind==='observation'?3000:10000} value={body} onChange={e=>setBody(e.target.value)}/></label>{artifact.layout&&<><label className="field"><span>独立LOGO层</span><select value={logo} onChange={e=>setLogo(e.target.value)}><option value="">不放LOGO</option>{brandAssets.map(a=><option key={a.id} value={a.id}>{a.data.title}</option>)}</select></label><label className="field"><span>独立二维码层 · 目标网址</span><input type="url" maxLength={500} value={qr} onChange={e=>setQr(e.target.value)}/></label></>}{artifact.copy&&copyTags.map(t=><label className="execution-check" key={t}><input type="checkbox" checked={tags.includes(t)} onChange={e=>setTags(e.target.checked?[...tags,t]:tags.filter(x=>x!==t))}/><span>{t}</span></label>)}<label className="field"><span>修改理由（至少5字）</span><textarea maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button type="button" className="secondary" disabled={busy||reason.trim().length<5||!body.trim()||(!!artifact.layout&&!title.trim())} onClick={save}>确认修改并另存待审版本</button></details>
}
