'use client';
import {useEffect,useState} from 'react';
import {printProofZip} from '@/lib/production-prepress';
import {printCheck} from '@/lib/production-print';
import type {Item} from '@/lib/model';
export default function ProductionPrintCheck({assetId,projectId,batchId,slot,hash,approved,items,active=true}:{assetId:string;active?:boolean;projectId:string;batchId:string;slot:string;hash:string;approved:boolean;items:Item[]}){
 const [opened,setOpened]=useState(false),[loadedFor,setLoadedFor]=useState(''),[pixels,setPixels]=useState<{width:number;height:number}|null>(null),[spec,setSpec]=useState({width_mm:210,height_mm:297,bleed_mm:3,ppi:300,safe_mm:5,paper:'待印厂确认',printer_confirmed:false}),[note,setNote]=useState(''),[materials,setMaterials]=useState<string[]>([]),[revision,setRevision]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[savedHash,setSavedHash]=useState('');const lines=items.find(i=>i.type==='procurement')?.data.lines||[];
 useEffect(()=>{if(!opened||!active||loadedFor===assetId+':'+hash)return;let live=true;fetch('/api/production/print?'+new URLSearchParams({project_id:projectId,batch_id:batchId,slot})).then(async r=>{const d:any=await r.json();if(!r.ok)throw Error(d.error||'规格读取失败');return d}).then((r:any)=>{if(live){setLoadedFor(assetId+':'+hash);setRevision(r.revision||0);if(r.data?.artifact_hash===hash){setSpec(r.data.spec);setNote(r.data.supplier_note);setMaterials(r.data.material_ids);setSavedHash(JSON.stringify({spec:r.data.spec,note:r.data.supplier_note,materials:r.data.material_ids}))}}}).catch(()=>{if(live)setError('规格读取失败')});return()=>{live=false}},[active,opened,assetId,projectId,batchId,slot,hash,loadedFor]);
 useEffect(()=>{if(!opened||!active)return;let live=true;setPixels(null);const image=new Image();image.onload=()=>{if(live)setPixels({width:image.naturalWidth,height:image.naturalHeight})};image.onerror=()=>{if(live)setError('无法读取原生像素')};image.src='/api/files/'+assetId+'?inline=1';return()=>{live=false}},[active,opened,assetId,hash]);
 let check:any=null;try{if(pixels)check=printCheck(spec,pixels)}catch{}
 async function save(){setBusy(true);setError('');try{const r=await fetch('/api/production/print',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project_id:projectId,batch_id:batchId,slot,artifact_hash:hash,revision,spec,material_ids:materials,supplier_note:note,consent:true})}),d:any=await r.json();if(!r.ok)throw Error(d.error);setRevision(d.revision);setSavedHash(JSON.stringify({spec,note,materials}));setNotice('规格版本已保存，关联批准设计与物料；送印文件及字体、色彩仍待核准。')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function proof(){setBusy(true);setError('');try{if(savedHash!==JSON.stringify({spec,note,materials}))throw Error('规格已修改，请先保存当前版本');const r=await fetch('/api/production/'+batchId+'/artifacts/'+slot+'?project_id='+encodeURIComponent(projectId)),d:any=await r.json();if(!r.ok||d.sha256!==hash)throw Error('批准产物已改变');const blob=await printProofZip(d.artifact,spec,revision,hash),f=new FormData();f.set('project_id',projectId);f.set('consent','true');f.set('file',blob,'print-proof.zip');const saved=await fetch('/api/production/print-proof',{method:'POST',body:f}),proof:any=await saved.json();if(!saved.ok)throw Error(proof.error);const a=document.createElement('a');a.href='/api/production/print-proof/'+proof.id+'?project_id='+encodeURIComponent(projectId);a.download=batchId+'-'+slot+'-rgb-prepress-proof.zip';a.click();setNotice('已归档独立物理尺寸、出血和安全区的RGB PDF核对稿；仍需印厂色彩与打样确认。')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <details onToggle={e=>setOpened(e.currentTarget.open)}><summary>送印规格与关联物料</summary><fieldset disabled={busy}><div className="form-grid">{[['width_mm','成品宽 mm'],['height_mm','成品高 mm'],['ppi','目标 PPI'],['bleed_mm','出血 mm'],['safe_mm','安全区 mm']].map(([key,label])=><label className="field" key={key}><span>{label}</span><input type="number" min={0} max={10000} value={spec[key as 'width_mm']} onChange={e=>{setSpec({...spec,[key]:Number(e.target.value),printer_confirmed:false});setNotice('')}}/></label>)}<label className="field"><span>纸张 / 材质与观看距离</span><input maxLength={200} value={spec.paper} onChange={e=>setSpec({...spec,paper:e.target.value,printer_confirmed:false})}/></label></div><label className="field"><span>印厂与色彩配置核对备注</span><textarea maxLength={2000} value={note} onChange={e=>{setNote(e.target.value);setSpec({...spec,printer_confirmed:false})}}/></label><label className="execution-check"><input type="checkbox" checked={spec.printer_confirmed} onChange={e=>setSpec({...spec,printer_confirmed:e.target.checked})}/><span>印厂已确认上述尺寸、纸张、出血与色彩转换要求</span></label>{lines.map((l:any)=><label className="execution-check" key={l.material_id}><input type="checkbox" checked={materials.includes(l.material_id)} onChange={e=>setMaterials(v=>e.target.checked?[...v,l.material_id]:v.filter(x=>x!==l.material_id))}/><span>关联物料：{l.title} · {l.quantity}{l.unit}</span></label>)}<button className="secondary" disabled={!approved||!check} onClick={save}>保存本次规格版本</button><button className="secondary" disabled={!approved||!revision||check?.status==='blocked'||savedHash!==JSON.stringify({spec,note,materials})} onClick={proof}>生成独立尺寸 RGB 印前 PDF 核对稿</button></fieldset>{error&&<p className="form-error">{error}</p>}{notice&&<p role="status">{notice}</p>}{check?<><p>原生像素 {pixels?.width} × {pixels?.height}；所需像素 {check.required_pixels.width} × {check.required_pixels.height}；有效 PPI {check.effective_ppi}。</p><p className={check.reasons.length?'form-error':'context-note'}>{check.reasons.join('；')||'程序检查通过，仍需印前人工核准。'}</p></>:<p>请输入有效尺寸与分辨率。</p>}<p className="context-note">海报批准后可保存规格。当前为RGB数字设计，线下准备包保留原图、规格、采购、分工与检查清单。</p></details>;
}
