'use client';
import {useEffect,useState} from 'react';
export default function ProductionBrandProfile({projectId,assets,onSaved}:{projectId:string;assets:any[];onSaved:()=>void}){
 const [form,setForm]=useState<any>(null),[memories,setMemories]=useState<any[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[consent,setConsent]=useState(false),[reason,setReason]=useState('');
 async function load(){const [b,m]=await Promise.all([fetch('/api/production/brand?project_id='+encodeURIComponent(projectId)),fetch('/api/production/memory?project_id='+encodeURIComponent(projectId))]);const p:any=await b.json(),list:any=await m.json();if(!b.ok||!m.ok)throw Error(p.error||list.error);setForm(p.profile?{...p.profile.data,revision:p.profile.revision}:{revision:0,name:'Woo虎',ip_asset_id:'',logo_asset_id:'',colors:['#ffc42e','#ef392d'],font:'WOO Noto CJK SC',reference_asset_ids:[],prohibitions:'不得改变Woo虎造型；不得生成新品牌LOGO、二维码或活动事实；不编造功效。',notes:''});setMemories(list.memories)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[projectId]);
 function change(p:any){setForm({...form,...p});setConsent(false);setNotice('')}
 async function save(){setBusy(true);setError('');try{const {revision,name,ip_asset_id,logo_asset_id,colors,font,reference_asset_ids,prohibitions,notes}=form;const r=await fetch('/api/production/brand',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project_id:projectId,revision,name,ip_asset_id,logo_asset_id,colors,font,reference_asset_ids,prohibitions,notes,consent:true})}),d:any=await r.json();if(!r.ok)throw Error(d.error);await load();setConsent(false);setNotice('品牌档案已保存。新批次锁定此版本；品牌/IP变化需要重做相关画面与镜头，旧批次不会自动覆盖。');onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function revoke(m:any){setBusy(true);setError('');try{const r=await fetch('/api/production/memory',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({project_id:projectId,id:m.id,revision:m.revision,reason,consent:true})}),d:any=await r.json();if(!r.ok)throw Error(d.error);await load();onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <details><summary>品牌档案与批准作品记忆</summary>{error&&<p role="alert" className="form-error">{error}</p>}{notice&&<p>{notice}</p>}{form&&<><label className="field"><span>品牌名称</span><input maxLength={150} value={form.name} onChange={e=>change({name:e.target.value})}/></label>{(['ip_asset_id','logo_asset_id'] as const).map(field=><label className="field" key={field}><span>{field==='ip_asset_id'?'批准IP参考':'批准LOGO（可选）'}</span><select value={form[field]} onChange={e=>change({[field]:e.target.value})}><option value="">选择品牌资产</option>{assets.map(a=><option key={a.id} value={a.id}>{a.data.title||a.data.filename}</option>)}</select></label>)}<label className="field"><span>品牌色（十六进制，用逗号分隔）</span><input value={form.colors.join(',')} onChange={e=>change({colors:e.target.value.split(',').map(v=>v.trim())})}/></label><label className="field"><span>字体要求（海报成品当前使用已校验 WOO Noto CJK SC）</span><input value={form.font} maxLength={150} onChange={e=>change({font:e.target.value})}/></label><label className="field"><span>参考案例图片（最多五张）</span><select multiple value={form.reference_asset_ids} onChange={e=>change({reference_asset_ids:Array.from(e.target.selectedOptions).map(o=>o.value)})}>{assets.map(a=><option key={a.id} value={a.id}>{a.data.title||a.data.filename}</option>)}</select></label><label className="field"><span>禁用项</span><textarea maxLength={3000} value={form.prohibitions} onChange={e=>change({prohibitions:e.target.value})}/></label><label className="field"><span>备注</span><textarea maxLength={2000} value={form.notes} onChange={e=>change({notes:e.target.value})}/></label><label className="execution-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>我已核对品牌规范与参考资产。IP变化影响海报背景与相关视频镜头；颜色、字体、禁用项变化影响视觉与文案质检。下一批使用新版本，已有作品需重新核对。</span></label><button className="primary" disabled={busy||!consent||!form.ip_asset_id} onClick={save}>确认品牌档案</button></>}
 <p>仅收录你人工批准后主动加入的作品，按渠道、风格和活动类型记录。新批次最多引用三条同品牌版本案例；案例只提供风格参考，不作为新活动事实。</p><label className="field"><span>撤回作品记忆原因（需要至少五个字）</span><input value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)}/></label>{memories.map(m=><article key={m.id}><p>{m.data.channel} · {m.data.style} · {m.data.activity_type} · {m.data.status==='approved'?'可参考':'已撤回'}</p><pre>{m.data.text}</pre>{m.data.status==='approved'&&<button className="secondary" disabled={busy||reason.trim().length<5} onClick={()=>revoke(m)}>撤回此案例</button>}</article>)}</details>;
}
