'use client';
import {useEffect,useRef,useState} from 'react';
import type {Project,Item} from '@/lib/model';
import type {ProductionBatch,ProductionJob} from '@/lib/production-batch';
import type {ProductionArtifact} from '@/lib/production-server';
import {productionFont} from '@/lib/production-font';
import {paintProduction,sha256,productionFontFiles} from '@/lib/production-content';
import {deliveryZip} from '@/lib/production-package';
import {copyPlatforms} from '@/lib/copywriting';
import {requestId} from '@/lib/request-id';
import ProductionPrintCheck from './production-print-check';
import ProductionVisualRevision from './production-visual-revision';
import ProductionBrandProfile from './production-brand-profile';
import ProductionRevisionPreview from './production-revision-preview';
import ProductionBindRun from './production-bind-run';
import OutcomePanel from './outcome-panel';
import ProductionVideoPlan from './production-video-plan';
import {procurementCsv} from '@/lib/materials';
import ProductionBriefEditor from './production-brief-editor';
import ProductionArtifactEditor from './production-artifact-editor';
import {productionAttention,type ProductionAttention} from '@/lib/production-attention';
import {Image as ImageIcon,FileText,ScanEye,Clapperboard,CheckCircle2} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import ProductionThumbnail from './production-thumbnail';
import {readArchivedArtifact} from '@/lib/production-read-client';
type View={deliveries?:any[];data:ProductionBatch;revision:number;control:{enabled:boolean};usage:any;capability:any};
async function api(url:string,method='GET',body?:unknown){const r=await fetch(url,{method,...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})}),d:any=await r.json();if(!r.ok)throw Error(d.error||'操作未完成');return d}
const labels:Record<string,string>={queued:'待执行',claimed:'已认领',submitting:'正在提交',running:'正在运行 / 待归档',unknown:'结果待核对',succeeded:'已归档',failed:'已确认失败',cancelled:'已取消'};
const business=(slot:string)=>/^(poster-[1-4]|copy-)/.test(slot);
const slotName=(slot:string)=>slot.startsWith('quality-')?'品牌质检 · '+slot.slice(8):slot.startsWith('repair-')?'受控返修 · '+slot.slice(7):slot.startsWith('poster')?'海报 '+slot.slice(7):slot.startsWith('vision')?'图片理解（抖音配文依据）':copyPlatforms[slot.slice(5) as keyof typeof copyPlatforms];
function ArtifactCard({projectId,batch,job,act,items,onEdit,brandAssets,busy,active}:{projectId:string;batch:View;busy:boolean;active:boolean;job:ProductionJob;items:Item[];brandAssets:any[];onEdit:(data:any)=>Promise<void>;act:(action:string,job?:ProductionJob,decision?:string)=>Promise<void>}){
 const [artifact,setArtifact]=useState<ProductionArtifact|null>(null),[error,setError]=useState(''),[ready,setReady]=useState(false),[history,setHistory]=useState<any[]>([]),[dependency,setDependency]=useState(''),canvas=useRef<HTMLCanvasElement>(null),[memoryType,setMemoryType]=useState('校园活动'),[memoryNotice,setMemoryNotice]=useState(''),[historyLoaded,setHistoryLoaded]=useState(false),[historyError,setHistoryError]=useState(''),[verifiedKey,setVerifiedKey]=useState(''),[historyOpen,setHistoryOpen]=useState(false),snapshot=useRef('');snapshot.current=projectId+':'+batch.data.id+':'+job.slot+':'+batch.revision+':'+job.artifact?.sha256;
 async function remember(){setError('');try{await api('/api/production/memory','POST',{project_id:projectId,batch_id:batch.data.id,slot:job.slot,artifact_hash:job.artifact!.sha256,channel:job.slot.startsWith('poster')?'海报':job.slot.slice(5),style:batch.data.input.approved_brief.style.slice(0,300),activity_type:memoryType,consent:true});setMemoryNotice('批准作品已加入风格记忆')}catch(e){setError((e as Error).message)}}
 useEffect(()=>{if(!active){setReady(false);setVerifiedKey('');return}let live=true;setReady(false);setVerifiedKey('');setError('');setDependency('');setHistoryLoaded(false);setHistory([]);setHistoryError('');
  readArchivedArtifact(projectId,batch.data.id,job.slot,job.artifact!.sha256,batch.revision).then(x=>{if(live){setArtifact(x.artifact);setVerifiedKey(batch.revision+':'+job.artifact!.sha256);setDependency(x.dependency_warning||'')}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false};
 },[active,projectId,batch.data.id,job.artifact?.sha256,batch.revision]);
 useEffect(()=>{if(!active||!artifact||verifiedKey!==batch.revision+':'+job.artifact?.sha256)return;let live=true;const controller=new AbortController(),node=canvas.current;setReady(false);if(artifact.layout&&node)paintProduction(node,'/api/files/'+artifact.asset_id+'?inline=1',artifact.layout,job.review!=='approved',{signal:controller.signal}).then(()=>{if(live)setReady(true)}).catch(e=>{if(live)setError(e.message)});else setReady(true);return()=>{live=false;controller.abort();if(node){node.width=0;node.height=0}}},[active,artifact,job.review,verifiedKey,batch.revision,job.artifact?.sha256]);
 async function loadHistory(){if(historyLoaded)return;const key=snapshot.current;setHistoryError('');try{const d=await readArchivedArtifact(projectId,batch.data.id,job.slot,job.artifact!.sha256,batch.revision,true);if(snapshot.current===key){setHistory(d.history||[]);setHistoryLoaded(true)}}catch(e){if(snapshot.current===key)setHistoryError((e as Error).message)}}
 useEffect(()=>{if(active&&historyOpen)void loadHistory()},[active,historyOpen,historyLoaded,batch.revision,job.artifact?.sha256]);

 return <article className="production-artifact">
  <section className="artifact-preview-pane" aria-label={slotName(job.slot)+'预览'}>
   <header className="artifact-preview-heading"><h3>{slotName(job.slot)}</h3><span className={'review-status review-'+job.review}>{job.review==='approved'?'已批准':job.review==='rejected'?'已退回':'待审核'}</span></header>
   {!artifact&&!error&&<p role="status" className="preview-placeholder">正在读取已归档作品…</p>}
   {artifact?.layout&&<div className="artifact-canvas-stage"><canvas ref={canvas} aria-label={slotName(job.slot)+'当前版本预览'}/></div>}
   {artifact?.copy&&<div className="artifact-copy-sheet"><h3>{artifact.copy.title}</h3><pre>{artifact.copy.text}</pre></div>}
   {artifact?.observation&&<div className="artifact-copy-sheet"><h3>画面观察</h3><p>{artifact.observation}</p></div>}
   {artifact?.quality&&<div className="artifact-copy-sheet"><h3>品牌质检建议</h3><p>{artifact.quality.needs_repair?'建议进行一轮受控返修':'无需自动返修'}；仍需人审。</p>{artifact.quality.findings.map((f,i)=><p key={i}>{f.area} · {f.severity} · {f.detail}</p>)}<p>{artifact.quality.uncertainty}</p></div>}
   {artifact?.copy?.added_fields?.length?<details><summary>已补入的确认事实</summary>{artifact.copy.added_fields.map(x=><p key={x.field}>{x.value}</p>)}</details>:null}
   {error&&<p role="alert" className="form-error">{error}</p>}
  </section>
  <aside className="artifact-inspector" aria-label="当前作品修改与审核">
   <div className="section-heading"><h3>版本审核</h3><CheckCircle2 size={19}/></div>
   <p className="context-note">核对品牌角色、活动事实、文字完整和画面质量。批准对应当前作品版本。</p>
   {dependency&&<p role="alert" className="form-error">{dependency}</p>}
   <div className="production-actions artifact-review-actions">{business(job.slot)&&<button className="primary" disabled={busy||!ready||!!error||!!dependency||job.review==='approved'} onClick={()=>act('review',job,'approved')}>批准此版本</button>}{business(job.slot)&&<button className="secondary" disabled={busy||!ready||!!error||job.review==='rejected'} onClick={()=>act('review',job,'rejected')}>退回修改</button>}</div>
   {artifact&&artifact.kind!=='quality'&&!job.slot.startsWith('repair-')&&<ProductionArtifactEditor artifact={artifact} onSave={onEdit} brandAssets={brandAssets}/>}
   {artifact?.asset_id&&job.slot.startsWith('poster-')&&<ProductionPrintCheck assetId={artifact.asset_id} projectId={projectId} batchId={batch.data.id} slot={job.slot} hash={job.artifact!.sha256} approved={job.review==='approved'} items={items} active={active}/>}
   {business(job.slot)&&job.review==='approved'&&<details><summary>收录为风格案例</summary><label className="field"><span>作品记忆的活动类型</span><input maxLength={100} value={memoryType} onChange={e=>setMemoryType(e.target.value)}/></label><button className="secondary" disabled={busy||!memoryType.trim()} onClick={remember}>收录批准作品</button><p role="status">{memoryNotice}</p></details>}
   <details className="artifact-history" onToggle={e=>setHistoryOpen(e.currentTarget.open)}><summary>版本与审批记录{history.length?' · '+history.length+' 次修改':''}</summary>{historyError&&<p className="form-error">{historyError}</p>}{!historyLoaded&&!historyError&&<p role="status">正在读取审批历史…</p>}<p className="context-note">当前版本：{job.artifact?.sha256}</p>{history.map(h=><div key={h.artifact.id}><p>{h.at} · {h.reason} · {h.review==='approved'?'原版已批准':h.review==='rejected'?'原版已退回':'原版待审核'}</p><pre>{h.data.copy?.text||h.data.observation||[h.data.layout?.headline,...(h.data.layout?.details||[])].join('\n')}</pre><small>版本哈希：{h.artifact.sha256}</small><p>审批记录：{h.reviews.map((r:any)=>r.decision+' · '+r.at).join('；')||'无'}</p></div>)}</details>
  </aside>
 </article>;
}

export function BatchWorkspace({projectId,view,items,assets,busy,focus,act,edit,active=true}:{projectId:string;view:View;active?:boolean;items:Item[];assets:any[];busy:boolean;focus:{batchId:string;slot:string;nonce:number}|null;act:(action:string,job?:ProductionJob,decision?:string,runId?:string)=>Promise<void>;edit:(job:ProductionJob,data:any)=>Promise<void>}){
 const groupOf=(j:ProductionJob)=>j.slot.startsWith('poster-')?'poster':j.slot.startsWith('copy-')?'copy':'checks';
 const first=view.data.jobs.find(j=>business(j.slot)&&j.state==='succeeded'&&j.review==='pending')||view.data.jobs.find(j=>business(j.slot))||view.data.jobs[0];
 const [group,setGroup]=useState(first?groupOf(first):'poster'),[selected,setSelected]=useState(first?.slot||'');
 useEffect(()=>{if(focus?.batchId!==view.data.id)return;const j=view.data.jobs.find(j=>j.slot===focus.slot);if(j){setGroup(groupOf(j));setSelected(j.slot)}},[focus,view.data.id]);
 const jobs=view.data.jobs.filter(j=>groupOf(j)===group),job=jobs.find(j=>j.slot===selected)||jobs[0];
 function changeGroup(next:string){setGroup(next);const list=view.data.jobs.filter(j=>groupOf(j)===next);setSelected((list.find(j=>j.state==='succeeded'&&j.review==='pending')||list[0])?.slot||'')}
 return <div className="batch-workspace">
  <Tabs value={group} onValueChange={changeGroup} className="artifact-types"><TabsList aria-label="作品类型" className="material-tabs-list">{[{id:'poster',name:'海报',Icon:ImageIcon},{id:'copy',name:'平台文案',Icon:FileText},{id:'checks',name:'识图与质检',Icon:ScanEye}].map(g=><TabsTrigger key={g.id} value={g.id} disabled={!view.data.jobs.some(j=>groupOf(j)===g.id)}><g.Icon size={16}/>{g.name}<span className="tab-count">{view.data.jobs.filter(j=>groupOf(j)===g.id).length}</span></TabsTrigger>)}</TabsList><TabsContent value={group} className="batch-workspace-body">
   <nav className="artifact-rail" aria-label="选择本批作品">{jobs.map(j=><button key={j.slot} className="artifact-choice" aria-pressed={job?.slot===j.slot} onClick={()=>setSelected(j.slot)}><ProductionThumbnail projectId={projectId} batchId={view.data.id} job={j} revision={view.revision} active={active}/><span><strong>{slotName(j.slot)}</strong><small>{j.state==='succeeded'?(j.review==='approved'?'已批准':j.review==='rejected'?'已退回':'待审核'):labels[j.state]}</small></span></button>)}</nav>
   <div className="artifact-focus">{job?<>
    <div className="selected-job-status"><span>{job.stage==='download_pending'?'已生成，待保存原图':labels[job.state]}</span>{job.error&&<p role="alert" className="form-error">{job.error}</p>}{job.state==='unknown'&&!job.attempts.at(-1)?.workflow_run_id&&<ProductionBindRun disabled={busy} onBind={id=>act('bind',job,undefined,id)}/>}
     {job.state==='failed'&&<button className="secondary" disabled={busy} onClick={()=>act('retry',job)}>确认只重试此项</button>}{job.state==='queued'&&<button className="quiet" disabled={busy} onClick={()=>act('cancel',job)}>取消此项</button>}
     {job.attempts.at(-1)?.workflow_run_id&&<details><summary>查看原运行记录</summary><p>{job.attempts.at(-1)!.workflow_run_id}</p></details>}
    </div>
    {job.state==='succeeded'?<ArtifactCard key={job.slot} projectId={projectId} batch={view} job={job} items={items} brandAssets={assets} busy={busy} active={active} onEdit={data=>edit(job,data)} act={(a,j,d)=>act(a,j,d)}/>:<div className="production-empty pending-artifact"><ImageIcon size={36}/><h3>{slotName(job.slot)}</h3><p>{job.state==='queued'?'尚未提交生成。确认调用上限后，使用批次上方的启动按钮。':job.state==='cancelled'?'这项任务已取消。':job.state==='unknown'?'先核对原运行结果，再决定下一步。':'归档完成后将在这里显示作品。'}</p></div>}
   </>:<p className="context-note">此分类暂无作品。</p>}</div>
  </TabsContent></Tabs>
 </div>;
}

export default function ProductionPanel({project,items,onSaved,onNavigate}:{project:Project;items:Item[];onSaved:()=>void;onNavigate?:(section:string)=>void}){
 const activity=items.find(i=>i.type==='activity_settings'),[views,setViews]=useState<View[]>([]),[briefs,setBriefs]=useState<any[]>([]),[assets,setAssets]=useState<any[]>([]),[cap,setCap]=useState<any>({}),[open,setOpen]=useState(''),[briefId,setBriefId]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loaded,setLoaded]=useState(false),[visited,setVisited]=useState<string[]>([]),[stage,setStage]=useState('prepare'),[focus,setFocus]=useState<{batchId:string;slot:string;nonce:number}|null>(null);
 const attention=productionAttention(items,views.map(v=>v.data),assets.length>0);
 function goAttention(a:ProductionAttention){
  if(a.target==='batch'){setStage('artifacts');setOpen(a.batch_id!);const view=views.find(v=>v.data.id===a.batch_id),job=view?.data.jobs.find(j=>a.id===a.batch_id+j.slot||a.id===a.batch_id+j.slot+'-print');if(job)setFocus({batchId:a.batch_id!,slot:job.slot,nonce:Date.now()});requestAnimationFrame(()=>document.getElementById('production-batch-'+a.batch_id)?.scrollIntoView({behavior:'smooth',block:'start'}))}
  else if(a.target==='activity'){const section=document.getElementById('activity-information'),button=section?.querySelector('button');if(button?.textContent?.includes('填写'))button.click();section?.scrollIntoView({behavior:'smooth',block:'start'})}
  else if(a.target==='brief'){setStage('prepare');requestAnimationFrame(()=>{const d=document.getElementById('production-brief') as HTMLDetailsElement|null;if(d){d.open=true;d.scrollIntoView({behavior:'smooth',block:'start'})}})}
  else if(a.target==='video'){setStage('video');requestAnimationFrame(()=>document.getElementById('production-video')?.scrollIntoView({behavior:'smooth',block:'start'}))}
  else onNavigate?.(a.target==='materials'?'budget':'team')
 }
 useEffect(()=>{if(loaded)setVisited(v=>v.includes(stage)?v:[...v,stage])},[stage,loaded]);
 useEffect(()=>{if(loaded&&stage==='prepare'){const brief=document.getElementById('production-brief') as HTMLDetailsElement|null;if(brief)brief.open=true}},[stage,loaded]);
 const pendingId=useRef(requestId());
 async function refresh(){const d=await api('/api/production?project_id='+encodeURIComponent(project.id));setViews(d.batches);setBriefs(d.briefs);setCap(d.capability);}
 useEffect(()=>{setLoaded(false);setVisited([]);setViews([]);setAssets([]);setBriefId('');setOpen('');setStage('prepare');setFocus(null);setError('');pendingId.current=requestId();let active=true;Promise.all([api('/api/production?project_id='+encodeURIComponent(project.id)),api('/api/posters/ip?project_id='+encodeURIComponent(project.id))]).then(([d,a])=>{if(active){setLoaded(true);setViews(d.batches);setOpen(d.batches[0]?.data.id||'');setStage(d.batches.length?'artifacts':'prepare');setBriefs(d.briefs);setCap(d.capability);setAssets(a.assets)}}).catch(e=>{if(active){setLoaded(true);setError(e.message)}});return()=>{active=false}},[project.id]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();await refresh();onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function approve(data:any){await run(async()=>{const r=await api('/api/production','POST',{action:'approve_brief',...data});setBriefId(r.id);pendingId.current=requestId();setNotice('主题与品牌图已批准。下一步确认调用上限并保存批次。')})}
 async function create(text:number,images:number,quality:boolean){await run(async()=>{const key='woo-production-request:'+project.id+':'+briefId;let id=localStorage.getItem(key);if(!id){id=pendingId.current;localStorage.setItem(key,id)}const r=await api('/api/production','POST',{project_id:project.id,brief_id:briefId,project_revision:project.revision,request_id:id,budget:{text,image:images,video_seconds:0},quality_control:quality,consent:true});setOpen(r.data.id);setStage('artifacts');setNotice('批次已保存；关闭或刷新页面后可在下方继续查看。')})}
 async function act(view:View,action:string,job?:ProductionJob,decision?:string,runId?:string){await run(async()=>{await api('/api/production/'+view.data.id,'PATCH',{project_id:project.id,revision:view.revision,action,...(job?{slot:job.slot}:{}),...(job?.artifact?{hash:job.artifact.sha256}:{}),...(decision?{decision}:{}),...(runId?{workflow_run_id:runId}:{}),consent:true});setNotice(action==='recover'?'已查询原运行，未创建新生成请求。':'批次操作已保存。')})}
 async function edit(view:View,job:ProductionJob,data:any){await run(async()=>{await api('/api/production/'+view.data.id+'/artifacts/'+job.slot,'PATCH',{project_id:project.id,revision:view.revision,hash:job.artifact!.sha256,...data,consent:true});setNotice('改字版本已保存，没有模型调用。请重新核对并批准；旧版与原审批仍可查看。')})}
 async function revise(view:View,plan:any,scope:string[]){await run(async()=>{const key='woo-production-revise:'+project.id+':'+view.data.id+':'+plan.plan_hash+':'+scope.slice().sort().join(',');let id=localStorage.getItem(key);if(!id){id=requestId();localStorage.setItem(key,id)}const r=await api('/api/production/'+view.data.id+'/revise','POST',{project_id:project.id,revision:view.revision,request_id:id,plan_hash:plan.plan_hash,scope,consent:true});setOpen(r.data.id);setStage('artifacts');setNotice('新事实修订已建立：背景像素和原运行沿用，没有模型调用。请重新审核文字；旧稿与旧批准记录仍可查。')})}
 async function videoPackage(scriptId:string){await run(async()=>{const pack=await api('/api/production/video-package?project_id='+encodeURIComponent(project.id)+'&script_id='+encodeURIComponent(scriptId)),files:{name:string;bytes:Uint8Array}[]=[],enc=new TextEncoder(),extensions:Record<string,string>={'video/mp4':'mp4','image/png':'png','image/jpeg':'jpg','image/webp':'webp','audio/mpeg':'mp3','audio/wav':'wav','audio/x-wav':'wav','audio/mp4':'m4a','audio/ogg':'ogg'};for(let i=0;i<pack.approved_assets.length;i++){const a=pack.approved_assets[i],r=await fetch('/api/files/'+a.asset_id);if(!r.ok)throw Error('视频素材读取失败');const bytes=new Uint8Array(await r.arrayBuffer());if(await sha256(bytes)!==a.sha256)throw Error('视频素材哈希校验失败');const name='media/'+a.role+'-'+String(i+1).padStart(2,'0')+'.'+(extensions[a.mime]||'bin');files.push({name,bytes});a.delivery_file=name}files.push(...await productionFontFiles());if(pack.plan?.data.srt)files.push({name:'captions.srt',bytes:enc.encode(pack.plan.data.srt)});files.push({name:'shot-package.json',bytes:enc.encode(JSON.stringify(pack,null,2))},{name:'READ-BEFORE-RENDER.txt',bytes:enc.encode(pack.notice+'\n待补资源：'+pack.missing_resources.join('；'))});const url=URL.createObjectURL(deliveryZip(files)),link=document.createElement('a');link.href=url;link.download='woo-30s-shot-package.zip';link.click();setTimeout(()=>URL.revokeObjectURL(url),30000);setNotice('已导出批准脚本、已有素材和音轨字幕方案。30秒完整成片仍等待持久合成资源。')})}
 async function offline(view:View){await run(async()=>{const pack=await api('/api/production/'+view.data.id+'/offline?project_id='+encodeURIComponent(project.id)),enc=new TextEncoder(),files:{name:string;bytes:Uint8Array}[]=[];for(const d of pack.designs){const r=await fetch('/api/files/'+d.artifact.asset_id);if(!r.ok)throw Error('原图读取失败');const bytes=new Uint8Array(await r.arrayBuffer());if(await sha256(bytes)!==d.artifact.background_sha256)throw Error('原图校验失败');files.push({name:'backgrounds/'+d.slot+'.'+(r.headers.get('content-type')?.includes('png')?'png':'jpg'),bytes});files.push({name:'layouts/'+d.slot+'.json',bytes:enc.encode(JSON.stringify(d.artifact.layout,null,2))});if(d.print_proof){const r=await fetch('/api/production/print-proof/'+d.print_proof.id+'?project_id='+encodeURIComponent(project.id)+'&file=pdf');if(!r.ok)throw Error('印前核对稿读取失败');const bytes=new Uint8Array(await r.arrayBuffer());if(await sha256(bytes)!==d.print_proof.data.outputs.find((x:any)=>x.mime==='application/pdf').sha256)throw Error('印前核对稿校验失败');files.push({name:'print-proofs/'+d.slot+'.pdf',bytes})}}files.push(...await productionFontFiles());files.push({name:'procurement.csv',bytes:enc.encode(procurementCsv(pack.procurement.name,pack.procurement.lines))},{name:'offline-preparation.json',bytes:enc.encode(JSON.stringify(pack,null,2))},{name:'CHECK-BEFORE-PRINT.txt',bytes:enc.encode('本包为线下准备包。请核准印厂规格、真实像素、中文字体与色彩配置，确认最终送印文件；采购与布置按清单落实并记录凭据。')});const url=URL.createObjectURL(deliveryZip(files)),link=document.createElement('a');link.href=url;link.download=view.data.id+'-offline-preparation.zip';link.click();setTimeout(()=>URL.revokeObjectURL(url),30000);setNotice('线下准备包已导出，送印文件与现实执行仍需核准。')})}
 async function download(view:View){await run(async()=>{const manifest=await api('/api/production/'+view.data.id+'/export?project_id='+encodeURIComponent(project.id)),enc=new TextEncoder(),files:{name:string;bytes:Uint8Array}[]=[],checks:any[]=[];
 for(const entry of manifest.artifacts){const a=entry.data as ProductionArtifact;let bytes:Uint8Array,name:string;if(a.layout){const canvas=document.createElement('canvas');await paintProduction(canvas,'/api/files/'+a.asset_id+'?inline=1',a.layout,false);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('海报导出失败')),'image/png'));bytes=new Uint8Array(await blob.arrayBuffer());canvas.width=0;canvas.height=0;name='online/'+a.slot+'.png';files.push({name:'layouts/'+a.slot+'.json',bytes:enc.encode(JSON.stringify(a.layout,null,2))});}else{bytes=enc.encode(a.copy!.text);name='online/'+a.slot+'.txt'}files.push({name,bytes});checks.push({name,sha256:await sha256(bytes),artifact_id:a.id,approved_artifact_sha256:entry.sha256});}
 if(manifest.supplement){for(const [name,value] of [['online/publishing-plan.json',manifest.supplement.publishing_plan],['online/material-list.json',manifest.supplement.material_list]])files.push({name:name as string,bytes:enc.encode(JSON.stringify(value,null,2))});if(manifest.supplement.video.id){for(const info of manifest.supplement.video.outputs){const kind=info.mime==='video/mp4'?'video':'cover',r=await fetch('/api/production/renders/'+manifest.supplement.video.id+'?project_id='+encodeURIComponent(project.id)+'&file='+kind);if(!r.ok)throw Error('批准视频读取失败');const bytes=new Uint8Array(await r.arrayBuffer());if(await sha256(bytes)!==info.sha256)throw Error('批准成片或封面校验失败');files.push({name:kind==='video'?'online/video.mp4':'online/cover.jpg',bytes})}}}
 manifest.delivery_files=checks;if(manifest.artifacts.some((a:any)=>a.data.layout))files.push(...await productionFontFiles());manifest.renderer={version:'production-canvas-2',dimensions:'1080x1440',font:'WOO Noto CJK SC · GB2312+Latin subset · Sans2.004',font_sha256:productionFont.sha256};files.push({name:'manifest.json',bytes:enc.encode(JSON.stringify(manifest,null,2))});const blob=deliveryZip(files),form=new FormData();form.set('project_id',project.id);form.set('file',blob,view.data.id+'-approved.zip');const response=await fetch('/api/production/'+view.data.id+'/deliveries',{method:'POST',body:form}),saved:any=await response.json();if(!response.ok)throw Error(saved.error||'交付包未归档');const link=document.createElement('a');link.href='/api/production/'+view.data.id+'/deliveries/'+saved.id+'?project_id='+encodeURIComponent(project.id);link.download=view.data.id+'-approved.zip';link.click();setNotice('批准包已归档并开始下载。实际文件与哈希已保存，重新打开后仍可下载；不代表已经发布。')})}
 return <><section className="panel production-panel" aria-label="内容制作工作台">
  <div className="section-heading production-heading"><div><span className="section-kicker">内容制作</span><h2>本次创作工作台</h2><p className="muted">四张主题海报 · 四平台文案 · 30秒视频</p></div><button className="secondary" disabled={busy} onClick={()=>run(refresh)}>刷新状态</button></div>
  {error&&<p role="alert" className="form-error">{error}</p>}{notice&&<p role="status" className="production-notice">{notice}</p>}{!cap.verified&&<p className="context-note">后台触发器正在联通验收。现在可以确认主题、保存批次；生产启动将在关页验证通过后开放。</p>}
  <div className="production-attention-bar"><strong>待我处理 <span className="count-chip">{attention.length}</span></strong><div className="production-attention">{attention.map(a=><button type="button" className="attention-chip" key={a.id} onClick={()=>goAttention(a)}>{a.title}</button>)}{!attention.length&&<span className="muted">当前没有待处理提醒</span>}</div></div>
  {!loaded?<p role="status">正在读取生产批次…</p>:<Tabs value={stage} onValueChange={setStage} className="production-stages"><TabsList aria-label="制作阶段" className="material-tabs-list production-stage-list"><TabsTrigger value="prepare">简报与三案</TabsTrigger><TabsTrigger value="artifacts">制作与审核</TabsTrigger><TabsTrigger value="video">视频</TabsTrigger><TabsTrigger value="delivery">交付</TabsTrigger></TabsList>
   {(stage==='prepare'||visited.includes('prepare'))&&<TabsContent value="prepare" forceMount className="production-stage-pane">
    <p className="context-note">确认活动事实与品牌参考，选择创作方向，再确认模型调用上限。</p>
    <ProductionBrandProfile key={project.id} projectId={project.id} assets={assets} onSaved={onSaved}/>
    <ProductionBriefEditor key={project.id+':'+activity?.revision} project={project} items={items} assets={assets} briefs={briefs} busy={busy} briefId={briefId} onSelect={id=>{setBriefId(id);pendingId.current=requestId()}} onApprove={approve} onCreate={create} onSaved={onSaved}/>
   </TabsContent>}
   {(stage==='artifacts'||visited.includes('artifacts'))&&<TabsContent value="artifacts" forceMount className="production-stage-pane">
    {!views.length&&<div className="production-empty"><ImageIcon size={36}/><h3>还没有生产批次</h3><p>先确认简报、创作方向与调用上限。</p><button className="primary" onClick={()=>setStage('prepare')}>准备本次创作</button></div>}
    {views.map(view=><article className="production-batch" id={'production-batch-'+view.data.id} key={view.data.id}>
     <button className="production-summary" aria-expanded={open===view.data.id} aria-controls={'batch-body-'+view.data.id} onClick={()=>setOpen(open===view.data.id?'':view.data.id)}><strong>{view.data.input.approved_brief.theme}</strong><span>{view.data.jobs.filter(j=>business(j.slot)&&j.state==='succeeded').length}/8 已归档 · {view.data.jobs.filter(j=>business(j.slot)&&j.review==='approved').length} 已批准</span><small>{view.data.created_at}</small></button>
     {open===view.data.id&&<div id={'batch-body-'+view.data.id}>
      <div className="batch-budget"><span>文字 <strong>{view.usage.spent.text}</strong> 已计 · {view.usage.reserved.text} 保留 / {view.data.input.budget.text} 上限</span><span>生图 <strong>{view.usage.spent.image}</strong> 已计 · {view.usage.reserved.image} 保留 / {view.data.input.budget.image} 上限</span><span>实际费用：未知</span></div>
      <p className={activity?.revision!==view.data.input.activity_revision?'form-error':'context-note'}>{activity?.revision!==view.data.input.activity_revision?'活动事实已改变；本批为旧稿，正式导出暂停。':'当前活动事实版本一致。'}</p>
      <div className="production-actions batch-controls"><button className={view.data.jobs.some(j=>business(j.slot)&&j.state==='succeeded'&&j.review==='pending')?'secondary':'primary'} disabled={busy||!cap.verified||view.control.enabled} onClick={()=>act(view,'start')}>启动后台生产</button><button className="secondary" disabled={busy||!view.control.enabled} onClick={()=>act(view,'pause')}>暂停后续提交</button><button className="secondary" disabled={busy||!view.data.jobs.some(j=>['running','unknown'].includes(j.state)&&j.attempts.at(-1)?.workflow_run_id)} onClick={()=>act(view,'recover')}>查询原运行 / 重试下载</button></div>
      <BatchWorkspace projectId={project.id} view={view} items={items} assets={assets} busy={busy} active={stage==='artifacts'} focus={focus} act={(a,j,d,r)=>act(view,a,j,d,r)} edit={(j,d)=>edit(view,j,d)}/>
      <details className="batch-revision"><summary>修订创作依据与生产范围</summary><p className="context-note">批准事实版本：{view.data.input.activity_revision}。修改后保留旧稿与原批准记录；新的生成范围仍需单独确认预算。</p>{activity?.revision!==view.data.input.activity_revision&&view.data.jobs.some(j=>business(j.slot)&&j.state==='succeeded')&&<ProductionRevisionPreview key={view.data.id+':'+view.revision+':'+activity?.revision} projectId={project.id} batchId={view.data.id} busy={busy} onConfirm={(plan,scope)=>revise(view,plan,scope)}/>}<ProductionVisualRevision key={view.data.id+':'+briefId} projectId={project.id} parentId={view.data.id} briefId={briefId} onSaved={()=>run(refresh)}/></details>
     </div>}
    </article>)}
   </TabsContent>}
   {(stage==='video'||visited.includes('video'))&&<TabsContent value="video" forceMount className="production-stage-pane"><section id="production-video"><div className="section-heading"><h3>30秒视频镜头与素材</h3><Clapperboard size={20}/></div><p className="context-note">核对批准脚本，准备逐镜素材、音轨、字幕、封面和片尾。合成服务未连接时可以导出资源包。</p>{items.filter(i=>i.type==='run'&&i.data.key==='script'&&i.data.review_status==='approved').map(i=><ProductionVideoPlan key={i.id+':'+i.revision} projectId={project.id} script={i} items={items} onSaved={onSaved} onExport={()=>videoPackage(i.id)}/>)}{!items.some(i=>i.type==='run'&&i.data.key==='script'&&i.data.review_status==='approved')&&<div className="production-empty"><Clapperboard size={36}/><h3>先准备视频脚本</h3><p>批准脚本后，在这里继续逐镜素材制作与成片审核。</p><button className="secondary" onClick={()=>onNavigate?.('video')}>打开视频创作</button></div>}</section></TabsContent>}
   {(stage==='delivery'||visited.includes('delivery'))&&<TabsContent value="delivery" forceMount className="production-stage-pane"><p className="context-note">导出当前已批准内容。部分批准包、完整八项包与线下准备包分别标明；导出不等于已发布或送印。</p>{!views.length&&<p className="muted">暂无生产批次可交付。</p>}{views.map(view=><section className="delivery-batch" key={view.data.id}><div className="section-heading"><h3>{view.data.input.approved_brief.theme}</h3><span>{view.data.jobs.filter(j=>business(j.slot)&&j.review==='approved').length}/8 已批准</span></div>{activity?.revision!==view.data.input.activity_revision&&<p className="form-error">活动事实已改变；正式导出暂停，请先修订并重新审核。</p>}<div className="production-actions"><button className="primary" disabled={busy||!view.data.jobs.some(j=>business(j.slot)&&j.review==='approved')} onClick={()=>download(view)}>导出已批准内容包</button><button className="secondary" disabled={busy||!view.data.jobs.some(j=>j.slot.startsWith('poster')&&j.review==='approved')} onClick={()=>offline(view)}>导出线下准备包</button></div>{view.deliveries?.length?<details><summary>已归档线上包 · {view.deliveries.length}</summary>{view.deliveries.map(d=><p key={d.id}><a href={'/api/production/'+view.data.id+'/deliveries/'+d.id+'?project_id='+encodeURIComponent(project.id)} download>{d.data.partial?'部分批准包':'完整八项批准包'} · {d.created_at}</a><small>文件哈希：{d.data.sha256}</small></p>)}</details>:<p className="context-note">还没有归档的交付包。</p>}</section>)}</TabsContent>}
  </Tabs>}
 </section><OutcomePanel key={project.id} project={project} items={items} onSaved={onSaved}/></>;
}
