'use client';
import {useEffect,useState} from 'react';
import type {Item} from '@/lib/model';
import {requestId} from '@/lib/request-id';
import {sha256} from '@/lib/production-content';
import {videoPackageBlob} from '@/lib/client-video-package';
async function api(url:string,method='GET',body?:any){const r=await fetch(url,{method,...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})}),d:any=await r.json();if(!r.ok)throw Error(d.error);return d}
export default function ProductionVideoJobs({projectId,scriptId,pack,items,onSaved}:{projectId:string;scriptId:string;pack:any;items:Item[];onSaved:()=>void}){
 const [tasks,setTasks]=useState<any[]>([]),[renders,setRenders]=useState<any[]>([]),[cap,setCap]=useState<any>({}),[frames,setFrames]=useState<Record<string,string>>({}),[bind,setBind]=useState<Record<string,string>>({}),[clipConsent,setClipConsent]=useState(false),[renderConsent,setRenderConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const keys=items.filter(i=>i.type==='asset'&&i.data.review_status==='approved'&&['image/png','image/jpeg'].includes(i.data.mime));
 async function load(){const [s,r]=await Promise.all([api('/api/production/shots?project_id='+encodeURIComponent(projectId)+'&script_id='+encodeURIComponent(scriptId)),api('/api/production/renders?project_id='+encodeURIComponent(projectId)+'&script_id='+encodeURIComponent(scriptId))]);setTasks(s.tasks);setRenders(r.renders);setCap(r.capability)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[projectId,scriptId,pack.plan?.revision]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();await load();onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function stableRequest(key:string){let id=localStorage.getItem(key);if(!id){id=requestId();localStorage.setItem(key,id)}return id}
 async function generate(shot:any,retry?:any){await run(async()=>{const frame=keys.find(i=>i.id===frames[shot.id]);if(!frame)throw Error('先选择批准关键帧');const id=stableRequest('woo-shot:'+projectId+':'+pack.script.sha256+':'+shot.id+':'+frame.id+':'+frame.revision+':'+(retry?.id||''));await api('/api/production/shots','POST',{project_id:projectId,script_id:scriptId,script_hash:pack.script.sha256,shot_id:shot.id,keyframe_asset_id:frame.id,request_id:id,...(retry?{retry_of:retry.id}:{}),budget_seconds:5,consent:true});setNotice('五秒镜头任务已保存。关闭页面后后台查询原任务；生成素材需先审核，再选入镜头方案。')})}
 async function submit(){await run(async()=>{const {pack:p,blob}=await videoPackageBlob(projectId,scriptId);if(blob.size>64*1024*1024)throw Error('合成包超过64MB；请压缩已有媒体后重新审核素材');const id=stableRequest('woo-render:'+projectId+':'+p.script.sha256+':'+p.plan.revision+':'+await sha256(await blob.arrayBuffer())),f=new FormData();f.set('project_id',projectId);f.set('request_id',id);f.set('consent','true');f.set('file',blob,'shot-package.zip');const r=await fetch('/api/production/renders',{method:'POST',body:f}),d:any=await r.json();if(!r.ok)throw Error(d.error);setNotice('合成请求已保存。未知状态只查询原请求，不重新提交；成片和封面归档后等待人审。')})}
 const file=(r:any,kind:string)=>'/api/production/renders/'+r.id+'?project_id='+encodeURIComponent(projectId)+'&file='+kind;
 return <details><summary>五秒AIGC镜头与完整成片任务</summary>{error&&<p role="alert" className="form-error">{error}</p>}{notice&&<p>{notice}</p>}<p>当前工具生成五秒片段，长AIGC镜头需先拆成五秒镜头并批准脚本。真人素材继续上传并审核。</p><label className="execution-check"><input type="checkbox" checked={clipConsent} onChange={e=>setClipConsent(e.target.checked)}/><span>我确认所选关键帧与镜头；每次点击仅生成这一镜五秒，实际费用未知，其他镜头不重做</span></label>{pack.timeline.filter((s:any)=>s.type==='aigc').map((s:any)=><div key={s.id}><p>{s.id} · {s.duration} 秒</p><select aria-label={s.id+'批准关键帧'} value={frames[s.id]||''} onChange={e=>{setFrames({...frames,[s.id]:e.target.value});setClipConsent(false)}}><option value="">选择批准关键帧</option>{keys.map(i=><option key={i.id} value={i.id}>{i.data.title||i.data.filename}</option>)}</select><button className="secondary" disabled={busy||!clipConsent||!frames[s.id]||s.duration!==5} onClick={()=>generate(s)}>确认生成此镜五秒</button>{tasks.filter(t=>t.data.shot_id===s.id).map(t=><article key={t.id}><p>{t.data.status} · 已计 {t.data.spent_seconds} 秒 / 保留 {t.data.reserved_seconds} 秒 · 实际费用未知</p>{t.data.error&&<p>{t.data.error}</p>}{t.data.provider_task_id&&<small>原任务：{t.data.provider_task_id}</small>}{t.data.asset_id&&<p>片段已存入资料资产，待你审核；批准后可选入此镜。</p>}<button className="secondary" disabled={busy||['archived','failed'].includes(t.data.status)} onClick={()=>run(async()=>{await api('/api/production/shots/'+t.id+'?project_id='+encodeURIComponent(projectId))})}>查询原任务 / 重试下载</button>{t.data.status==='failed'&&<button className="secondary" disabled={busy||!clipConsent||!frames[s.id]} onClick={()=>generate(s,t)}>确认失败后只重试此镜</button>}{t.data.status==='unknown'&&!t.data.workflow_run_id&&<><input aria-label="原Dify运行编号" value={bind[t.id]||''} onChange={e=>setBind({...bind,[t.id]:e.target.value})}/><button className="secondary" disabled={busy||!bind[t.id]} onClick={()=>run(async()=>{await api('/api/production/shots/'+t.id,'PATCH',{project_id:projectId,workflow_run_id:bind[t.id],consent:true})})}>核对输入并绑定原运行</button></>}</article>)}</div>)}
 <p>{cap.reason}</p><label className="execution-check"><input type="checkbox" checked={renderConsent} onChange={e=>setRenderConsent(e.target.checked)}/><span>我已确认镜头、配音、音乐、字幕、封面与片尾方案，提交30秒竖屏合成；不代表已经发布</span></label><button className="primary" disabled={busy||!renderConsent||!cap.configured||!cap.verified||!pack.plan||pack.missing_shots.length>0} onClick={submit}>提交完整成片合成</button><button className="secondary" disabled={busy} onClick={()=>run(load)}>刷新视频状态</button>{renders.map(r=><article key={r.id}><p>成片：{r.data.status} · {r.data.review_status==='approved'?'人工批准':r.data.review_status==='rejected'?'已退回':'待审核'} · 实际费用未知</p>{r.data.error&&<p>{r.data.error}</p>}{r.data.status!=='archived'&&<button className="secondary" disabled={busy||r.data.status==='failed'} onClick={()=>run(async()=>{await api('/api/production/renders/'+r.id+'?project_id='+encodeURIComponent(projectId))})}>查询原合成 / 重试归档</button>}{r.data.status==='archived'&&<><video controls preload="metadata" src={file(r,'video')} style={{maxWidth:'100%',maxHeight:480}}/><img alt="待核对视频封面" src={file(r,'cover')} style={{maxWidth:180}}/><p>实测 {r.data.technical.output.duration} 秒，1080×1920。请核对音画、字幕、片尾、安全区、黑帧疑点及授权。</p><button className="primary" disabled={busy||r.data.review_status==='approved'} onClick={()=>run(async()=>{await api('/api/production/renders/'+r.id,'PATCH',{project_id:projectId,revision:r.revision,hash:r.data.outputs[0].sha256,decision:'approved',consent:true})})}>批准当前成片和封面</button><button className="secondary" disabled={busy} onClick={()=>run(async()=>{await api('/api/production/renders/'+r.id,'PATCH',{project_id:projectId,revision:r.revision,hash:r.data.outputs[0].sha256,decision:'rejected',consent:true})})}>退回</button><p><a href={file(r,'video')} download>下载{r.data.review_status==='approved'?'批准成片':'待审成片'}</a> · <a href={file(r,'cover')} download>下载封面</a></p></>}</article>)}</details>;
}
