import {env} from 'cloudflare:workers';
import {bucket, database, HttpError, now, record} from './server';
export const arkBase='https://ark.cn-beijing.volces.com/api/v3';
export const defaults={image_model:'doubao-seedream-5-0-pro-260628',video_model:'doubao-seedance-2-5-260628',search_model:'doubao-seed-2-1-pro-260628'};
const configPath='_private/ark-config-v1';
const encoder=new TextEncoder();
const b64=(a:Uint8Array)=>{let s='';for(let i=0;i<a.length;i+=8192)s+=String.fromCharCode(...a.subarray(i,i+8192));return btoa(s)};
const bytes=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function encryptionKey(){const value=(env as any).ARK_CREDENTIAL_ENCRYPTION_KEY;if(!value)throw new HttpError(503,'密钥存储尚未配置，请联系工作台维护者。');return crypto.subtle.importKey('raw',bytes(value),'AES-GCM',false,['encrypt','decrypt'])}
export async function config(){const obj=await bucket().get(configPath);return obj?await obj.json<any>():null}
export async function publicConfig(){const c=await config();return {configured:!!(env as any).DIFY_WORKFLOW_API_KEY,storage_ready:!!(env as any).ARK_CREDENTIAL_ENCRYPTION_KEY,image_model:c?.image_model||defaults.image_model,video_model:c?.video_model||defaults.video_model,search_model:c?.search_model||defaults.search_model}}
export async function saveConfig(input:{api_key?:string,image_model:string,video_model:string,search_model?:string}){const old=await config();let encrypted=old?{cipher:old.cipher,iv:old.iv}:null;if(input.api_key){const iv=crypto.getRandomValues(new Uint8Array(12));const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},await encryptionKey(),encoder.encode(input.api_key));encrypted={cipher:b64(new Uint8Array(cipher)),iv:b64(iv)}}if(!encrypted?.cipher)throw new HttpError(400,'首次配置请填写火山方舟 API Key。');await bucket().put(configPath,JSON.stringify({...encrypted,image_model:input.image_model,video_model:input.video_model,search_model:input.search_model||old?.search_model||defaults.search_model,updated_at:now()}));return publicConfig()}
export async function arkConfig(){const c=await config();if(!c?.cipher)throw new HttpError(503,'请先在媒体工作台配置火山方舟 API Key，并开通图片和视频模型。');const decoded=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(c.iv)},await encryptionKey(),bytes(c.cipher));return {...c,key:new TextDecoder().decode(decoded)}}
export class ArkRejection extends HttpError{constructor(public provider_status:number,public provider_code:string,public provider_request_id:string,message:string){super(502,message)}}
export function sanitizedArkError(value:unknown,key:string){return (key?String(value||'').split(key).join('[redacted]'):String(value||'')).replace(/Bearer\s+[A-Za-z0-9._~+\/-]+/gi,'Bearer [redacted]').replace(/sk-[A-Za-z0-9_-]+/g,'[redacted]').replace(/[\r\n\t]/g,' ').slice(0,700)}
export async function arkRequest(path:string,key:string,body?:unknown){let response:Response;try{response=await fetch(arkBase+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(body?110000:20000)})}catch{throw new HttpError(504,'未能确认方舟请求结果，请检查方舟日志；不要立即重新生成，以免重复扣费。')}if(!response.ok){let details:any={};try{details=await response.json()}catch{}const code=sanitizedArkError(details.error?.code||details.code,key);const request=sanitizedArkError(details.error?.request_id||details.request_id||response.headers.get('x-request-id'),key);const detail=sanitizedArkError(details.error?.message||details.message,key);const message=code==='SetLimitExceeded'?'当前模型被账户用量上限暂停。请检查该模型的推理限额与安心体验状态。':code==='ToolNotOpen'?'联网搜索工具尚未开通，需要在方舟单独开通对应工具服务。':code==='ModelNotOpen'?'当前模型服务尚未开通，请在方舟开通管理启用对应模型。':response.status===401||response.status===403?'方舟密钥或模型权限不正确，请检查 API Key 和模型开通状态。':response.status===429?'方舟额度不足或请求过快，请检查余额和限流。':response.status===404?'方舟未找到所选模型或接口（HTTP 404）。请检查该账户可调用的模型 ID / 推理接入点，以及模型是否已开通。':'方舟拒绝请求（HTTP '+response.status+'）。';throw new ArkRejection(response.status,code,request,message+(code?' 错误码：'+code+'。':'')+(detail?' 原因：'+detail:'')+(request?' 请求编号：'+request:''))}try{return await response.json() as any}catch{throw new HttpError(502,'方舟响应格式异常，请检查控制台记录。')}}

export async function saveMedia(id:string,data:any){await database().prepare("UPDATE records SET data=?,revision=revision+1,updated_at=? WHERE id=? AND type='media'").bind(JSON.stringify(data),now(),id).run()}
export async function referenceImage(id:string,project:string){const asset=await record(id,project);if(asset.type!=='asset'||!['image/png','image/jpeg'].includes(asset.data.mime)||asset.data.size>8*1024*1024||!asset.data.storage_key)throw new HttpError(400,'参考图需要为已上传的 PNG / JPEG，且不超过8MB。');if((asset.data.generated||asset.id.startsWith('generated-')||asset.id.startsWith('layout-'))&&asset.data.review_status!=='approved')throw new HttpError(400,'AI素材需要先人工审核批准，才能作为参考图。');const object=await bucket().get(asset.data.storage_key);if(!object)throw new HttpError(404,'参考图片不存在');const data=new Uint8Array(await object.arrayBuffer());return 'data:'+asset.data.mime+';base64,'+b64(data)}
export async function persistImage(id:string,project:string,result:any){const raw=result.data?.[0]?.b64_json;if(typeof raw!=='string'||raw.length>28*1024*1024)throw new HttpError(502,'方舟没有返回有效图片，或图片超过20MB。');const data=bytes(raw);let mime='';if(data[0]===137&&data[1]===80&&data[2]===78&&data[3]===71)mime='image/png';else if(data[0]===255&&data[1]===216&&data[2]===255)mime='image/jpeg';else throw new HttpError(502,'返回图片格式不支持。');if(!data.length||data.length>20*1024*1024)throw new HttpError(502,'图片超过20MB。');return persistAsset(id,project,data,mime,mime==='image/png'?'png':'jpg')}
async function persistAsset(id:string,project:string,data:Uint8Array,mime:string,ext:string){const assetId='generated-'+id,key=project+'/'+assetId;await bucket().put(key,data,{httpMetadata:{contentType:mime}});const t=now();await database().prepare('INSERT OR IGNORE INTO records (id,project_id,type,data,revision,created_at,updated_at) VALUES (?,?,?,?,1,?,?)').bind(assetId,project,'asset',JSON.stringify({title:'AI生成'+(ext==='mp4'?'视频':'图片'),category:ext==='mp4'?'其他':'图片',origin:'执行资料',notes:'火山方舟生成；待人工审核。生成提示词和模型见媒体运行记录。',generated:true,review_status:'awaiting_review',source_media_id:id,filename:assetId+'.'+ext,mime,size:data.length,storage_key:key}),t,t).run();return assetId}
export function trustedVideoUrl(raw:unknown){if(typeof raw!=='string')throw new HttpError(502,'视频地址缺失');const u=new URL(raw);if(u.protocol!=='https:'||u.username||u.password||u.port||!['volces.com','volccdn.com','byteimg.com'].some(s=>u.hostname.endsWith('.'+s)))throw new HttpError(502,'视频下载域名不在允许列表，请联系维护者处理。');return u.toString()}
export async function persistVideo(id:string,project:string,url:unknown){const r=await fetch(trustedVideoUrl(url),{redirect:'manual',signal:AbortSignal.timeout(60000)});if(!r.ok||!r.body)throw new HttpError(502,'视频下载失败，可以稍后查询任务并重试下载。');const limit=20*1024*1024;if(Number(r.headers.get('content-length'))>limit)throw new HttpError(413,'视频超过20MB保存上限。');const reader=r.body.getReader(),chunks:Uint8Array[]=[];let total=0;while(true){const {value,done}=await reader.read();if(done)break;total+=value.length;if(total>limit){await reader.cancel();throw new HttpError(413,'视频超过20MB保存上限。')}chunks.push(value)}const data=new Uint8Array(total);let offset=0;for(const c of chunks){data.set(c,offset);offset+=c.length}if(total<12||new TextDecoder().decode(data.subarray(4,8))!=='ftyp')throw new HttpError(502,'返回内容不是有效 MP4。');return persistAsset(id,project,data,'video/mp4','mp4')}

export function researchResult(result:any){const texts:string[]=[],sources:{url:string,title:string,publish_time:string}[]=[];if(!Array.isArray(result.output))throw new HttpError(502,'没有收到有效调研输出，请查看方舟日志。');for(const output of result.output){if(output.type!=='message'||!Array.isArray(output.content))continue;for(const content of output.content){if(content.type!=='output_text')continue;if(typeof content.text==='string')texts.push(content.text);for(const a of content.annotations||[]){if(a.type!=='url_citation'||typeof a.url!=='string')continue;try{const u=new URL(a.url);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)continue;if(!sources.some(s=>s.url===u.href))sources.push({url:u.href,title:String(a.title||u.hostname).slice(0,300),publish_time:String(a.publish_time||'').slice(0,100)})}catch{}}}}const body=texts.join('\n\n');if(!body||body.length>40000)throw new HttpError(502,'调研输出为空或过长，请缩小问题范围。');return {body,sources:sources.slice(0,50),status:sources.length?'awaiting_review':'needs_sources',warning:sources.length?'网页摘要仍需打开原文核对，注意数据统计时间及人数口径。':'没有返回可核对的网页引用，不能视为已完成联网调研。',response_id:result.id,usage:result.usage||null}}

// Provider download URLs stay in private object storage and never in public records.
export async function stageImageDownload(id:string,project:string,url:unknown){
 const safe=trustedVideoUrl(url);
 await bucket().put('_private/media-download/'+id,JSON.stringify({project_id:project,url:safe}));
}
export async function retryImageDownload(id:string,project:string){
 const object=await bucket().get('_private/media-download/'+id);
 const staged=object?await object.json<any>():null;
 if(staged?.project_id!==project)throw new HttpError(404,'图片下载记录不存在，请核对 Dify 日志。');
 const r=await fetch(trustedVideoUrl(staged.url),{redirect:'manual',signal:AbortSignal.timeout(60000)});
 if(!r.ok||!r.body)throw new HttpError(502,'图片下载失败，可重试保存原图片。');
 const limit=20*1024*1024;
 if(Number(r.headers.get('content-length'))>limit)throw new HttpError(413,'图片超过20MB保存上限。');
 const reader=r.body.getReader(),chunks:Uint8Array[]=[];let total=0;
 while(true){const {value,done}=await reader.read();if(done)break;total+=value.length;if(total>limit){await reader.cancel();throw new HttpError(413,'图片超过20MB保存上限。')}chunks.push(value)}
 const data=new Uint8Array(total);let offset=0;for(const c of chunks){data.set(c,offset);offset+=c.length}
 return persistImage(id,project,{data:[{b64_json:b64(data)}]});
}
