import {outcomeSections} from './production-report';
import type {Project,Item} from './model';
import {isEarlyConcept,closeoutEvents} from './closeout-baseline';
import {closeoutText} from './closeout';
export function wrapText(text:string,width=42){const lines:string[]=[];for(const original of text.replace(/\r/g,'').split('\n')){let line='',length=0;for(const char of original){const weight=char.codePointAt(0)!>255?1:0.55;if(length+weight>width&&line){lines.push(line);line='';length=0}line+=char;length+=weight}lines.push(line)}return lines}
export function paginate(text:string){const lines=wrapText(text);const pages:string[]=[];for(let i=0;i<lines.length;i+=12)pages.push(lines.slice(i,i+12).join('\n'));return pages}
export type Section={title:string;body:string};
export function projectSections(project:Project,items:Item[]):Section[]{items=items.filter(i=>!isEarlyConcept(i));const activity=items.find(i=>i.type==='activity_settings');return [...outcomeSections(items.filter(i=>i.type==='outcome'&&i.data.activity_revision===(activity?.revision||0))),{title:'项目简报',body:`项目：${project.name}\n品牌：${project.brand}\n场景：${project.school}\n目标：${project.goal}\n${project.brief}\n资料版本：${project.source_note}`},...(project.id==='woo-original'?[{title:'完成版结案 · 实际活动',body:closeoutEvents.map(e=>e.date+' '+e.title+'｜'+e.place+'\n'+e.detail+'\n来源：结案P'+e.page).join('\n\n')},{title:'完成版结案 · 成果与口径',body:closeoutText}]:[]),{title:'线上执行记录',body:items.filter(i=>i.type==='task'&&i.data.lane==='online').map(i=>`${i.data.title}｜${i.data.status}｜${i.data.owner||'负责人待定'}｜${i.data.due||'日期待定'}\n${i.data.notes}\n来源：${i.data.source}`).join('\n\n')||'暂无线上任务'},{title:'线下执行记录',body:items.filter(i=>i.type==='task'&&i.data.lane==='offline').map(i=>`${i.data.title}｜${i.data.status}｜${i.data.owner||'负责人待定'}｜${i.data.due||'日期待定'}\n${i.data.notes}\n来源：${i.data.source}`).join('\n\n')||'暂无线下任务'},{title:'预算与物料',body:items.filter(i=>i.type==='budget').map(i=>`${i.data.title}｜${i.data.spec||'规格待定'}\n${i.data.quantity}${i.data.unit} × ${i.data.unit_price}元 + 运费${i.data.shipping}元\n实际支出：${i.data.actual_amount??'未登记'}；状态：${i.data.status}\n${i.data.notes}\n来源：${i.data.source}`).join('\n\n')||'暂无预算条目'},...items.filter(i=>i.type==='content').map(i=>({title:i.data.title,body:`内容状态：${i.data.status}；渠道：${i.data.channel||'待定'}\n${i.data.body}\n来源：${i.data.source}`})),{title:'参考资料与核对事项',body:items.filter(i=>i.type==='asset').map(i=>`${i.data.title}｜${i.data.origin}\n${i.data.notes}`).join('\n\n')+'\n\n此导出为可编辑的工作稿。资料中的版本、金额、人数和日期冲突仍须核对。附件原文不会自动读取；所选图片作为工作稿参考，仍须人工审核。'}]}
export type PptImage={title:string;data:string;width:number;height:number;source:string};
export async function buildPpt(title:string,sections:Section[],images:PptImage[]=[]){const {default:PptxGenJS}=await import('pptxgenjs');const ppt=new PptxGenJS();ppt.layout='LAYOUT_WIDE';ppt.author='WOO STUDIO';ppt.subject='乐虎项目工作稿';ppt.title=title;ppt.theme={headFontFace:'Microsoft YaHei',bodyFontFace:'Microsoft YaHei'};const cover=ppt.addSlide();cover.background={color:'FAD431'};cover.addText('WOO / CAMPUS STUDIO',{x:.7,y:.55,w:11,h:.4,fontSize:16,bold:true,color:'1B1B19'});cover.addText(title,{x:.7,y:2,w:11.9,h:2,fontSize:38,bold:true,color:'1B1B19',fit:'shrink',breakLine:false});cover.addText('策划 · 内容 · 执行 · 复盘\n可编辑工作稿 / '+new Date().toLocaleDateString('zh-CN'),{x:.7,y:5.65,w:11,h:.8,fontSize:16,color:'1B1B19'});cover.addNotes(title);let number=1;for(const section of sections){const pages=paginate(section.body);for(let i=0;i<pages.length;i++){const slide=ppt.addSlide();slide.background={color:'FBFAF5'};slide.addShape(ppt.ShapeType.rect,{x:0,y:0,w:13.333,h:.12,fill:{color:'FAD431'},line:{color:'FAD431'}});slide.addText(section.title.slice(0,32)+(pages.length>1?`（${i+1}/${pages.length}）`:''),{x:.7,y:.5,w:11.8,h:.7,fontSize:26,bold:true,color:'1B1B19',fit:'shrink'});slide.addText(pages[i],{x:.7,y:1.5,w:11.8,h:4.85,fontSize:18,color:'33332C',margin:0,breakLine:false,paraSpaceAfter:0,lineSpacingMultiple:1.15});slide.addText('WOO STUDIO · 工作稿 · 待人工核对',{x:.7,y:6.75,w:10,h:.25,fontSize:10,color:'77776C'});slide.addText(String(++number).padStart(2,'0'),{x:12,y:6.72,w:.6,h:.3,fontSize:11,color:'77776C'});slide.addNotes(`完整章节标题：${section.title}\n本页内容：\n${pages[i]}`)}}for(const image of images){const slide=ppt.addSlide();slide.background={color:'FBFAF5'};slide.addText(image.title.slice(0,50),{x:.7,y:.45,w:11.9,h:.7,fontSize:26,bold:true,color:'1B1B19',fit:'shrink'});const scale=Math.min(11.9/image.width,4.8/image.height);const w=image.width*scale,h=image.height*scale;slide.addImage({data:image.data,x:(13.333-w)/2,y:1.4+(4.8-h)/2,w,h});slide.addText('来源：'+image.source,{x:.7,y:6.4,w:11.9,h:.5,fontSize:12,color:'77776C',fit:'shrink'});slide.addNotes('图片来源：'+image.source+'\n工作稿图片，待人工审核。')}return ppt}
export async function exportPpt(title:string,sections:Section[],images:PptImage[]=[]){const ppt=await buildPpt(title,sections,images);await ppt.writeFile({fileName:title.replace(/[\\/:*?"<>|]/g,'-').slice(0,80)+'.pptx'})}

export async function loadPptImages(projectId:string,items:Item[],selectedIds:string[]):Promise<PptImage[]>{
 if(selectedIds.length>6)throw Error('一次最多选择6张图片。');
 const images:PptImage[]=[];
 for(const id of [...new Set(selectedIds)]){
  const asset=items.find(i=>i.id===id&&i.project_id===projectId&&i.type==='asset');
  if((asset?.data.generated||asset?.id.startsWith('generated-')||asset?.id.startsWith('layout-'))&&asset?.data.review_status!=='approved')throw Error('AI图片需要在资料与资产中人工审核后才能加入PPT。');
  if(!asset||!['image/png','image/jpeg'].includes(asset.data.mime)||asset.data.size>8*1024*1024)throw Error('图片不存在或不符合格式、大小要求。');
  const response=await fetch('/api/files/'+encodeURIComponent(id)+'?inline=1',{signal:AbortSignal.timeout(30000)});
  if(!response.ok)throw Error('无法读取图片：'+asset.data.title);
  const blob=await response.blob();if(blob.size>8*1024*1024||!['image/png','image/jpeg'].includes(blob.type))throw Error('图片格式或大小不符合要求。');
  const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(Error('图片读取失败'));reader.readAsDataURL(blob)});
  const dimensions=await new Promise<{width:number;height:number}>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve({width:image.naturalWidth,height:image.naturalHeight});image.onerror=()=>reject(Error('图片文件无法解码'));image.src=data});
  if(!dimensions.width||!dimensions.height)throw Error('图片尺寸无效。');
  images.push({title:asset.data.title,data,...dimensions,source:asset.data.origin+' · '+asset.data.title+' · '+(asset.data.notes||'用户所选参考图片')});
 }
 return images;
}
