import {z} from 'zod';
import {budgetUsage} from './production-batch';
export function productionBaseline(items:{id:string;type:string;data:any;created_at?:string}[],activityRevision:number){
 return items.filter(i=>i.type==='production_batch'&&i.data.input.activity_revision===activityRevision).map(i=>{
  const jobs=i.data.jobs.filter((j:any)=>/^(poster-[1-4]|copy-)/.test(j.slot)),reviewed=jobs.filter((j:any)=>j.reviews?.length),firstAccepted=reviewed.filter((j:any)=>j.reviews[0].decision==='approved').length;
  const first=jobs.flatMap((j:any)=>(j.reviews||[]).filter((r:any)=>r.decision==='approved').map((r:any)=>Date.parse(r.at))).filter(Number.isFinite).sort((a:number,b:number)=>a-b)[0];
  const brief=items.find(r=>r.id===i.data.input.approved_brief.id),start=Date.parse(brief?.data.approved_at||i.data.created_at),deliveries=items.filter(r=>r.type==='production_delivery'&&r.data.batch_id===i.id&&r.data.input_hash===i.data.input_hash).sort((a,b)=>Date.parse(a.data.exported_at)-Date.parse(b.data.exported_at)),full=deliveries.find(r=>!r.data.partial),elapsed=(at?:string)=>at?Math.max(0,Math.round((Date.parse(at)-start)/1000)):null;
  const queries=i.data.jobs.flatMap((j:any)=>j.recovery_history||[]),queried=new Set(queries.map((q:any)=>q.workflow_run_id)),recovered=new Set(queries.filter((q:any)=>q.result==='archived').map((q:any)=>q.workflow_run_id));
  return {batch_id:i.id,theme:i.data.input.approved_brief.theme,first_approved_seconds:first==null?null:Math.max(0,Math.round((first-Date.parse(i.data.created_at))/1000)),first_package_seconds:elapsed(deliveries[0]?.data.exported_at),full_package_seconds:elapsed(full?.data.exported_at),first_package_partial:deliveries[0]?.data.partial??null,first_round_accepted:firstAccepted,first_round_reviewed:reviewed.length,review_events:jobs.reduce((n:number,j:any)=>n+(j.reviews?.length||0),0),modifications:jobs.map((j:any)=>({slot:j.slot,count:j.artifact_history?.length||0})),unknown_jobs:i.data.jobs.filter((j:any)=>j.state==='unknown').length,calls:budgetUsage(i.data),recovery_success_rate:queried.size?recovered.size/queried.size:null,recovery_queried_runs:queried.size,recovery_archived_runs:recovered.size};
 })
}
export const sourceSchema=z.object({label:z.string().trim().min(1).max(300),locator:z.string().trim().min(1).max(300),version:z.string().trim().min(1).max(100),url:z.string().max(2000).refine(v=>!v||/^https?:\/\//i.test(v),'来源链接必须为HTTP或HTTPS'),asset_id:z.string().max(200)}).strict();
export const outcomeSchema=z.object({kind:z.enum(['metric','expense']),channel:z.string().trim().min(1).max(100),metric:z.enum(['曝光','观看','互动','报名','到场','实际支出']),unit:z.string().trim().min(1).max(30),planned:z.number().finite().nonnegative().nullable(),actual:z.number().finite().nonnegative().nullable(),cost_category:z.enum(['model','render','procurement','other']).nullable(),period:z.string().trim().min(1).max(300),source:sourceSchema,observed_at:z.string().datetime(),notes:z.string().max(2000)}).strict().superRefine((r,c)=>{if(r.actual===null&&r.planned===null)c.addIssue({code:'custom',message:'至少填写目标或实际值'});if(r.kind==='expense'&&(r.metric!=='实际支出'||r.unit!=='元'||!r.cost_category))c.addIssue({code:'custom',message:'费用必须按人民币元和费用类别登记'});if(r.kind==='metric'&&(r.metric==='实际支出'||r.cost_category!==null))c.addIssue({code:'custom',message:'效果指标不属于费用类别'});});
export type Outcome=z.infer<typeof outcomeSchema>;
const kinds:Record<string,string>={model:'模型调用',render:'渲染资源',procurement:'活动采购',other:'其他费用'};
export function outcomeSummary(rows:{id:string;revision:number;data:any}[]){const active=rows.filter(r=>!r.data.revoked_at),expense=active.filter(r=>r.data.kind==='expense');return {active,revoked:rows.filter(r=>r.data.revoked_at),expenses:Object.entries(kinds).map(([key,label])=>{const entries=expense.filter(r=>r.data.cost_category===key);return {category:key,label,planned_known:entries.some(r=>r.data.planned!==null)?entries.reduce((s,r)=>s+(r.data.planned??0),0):null,actual_known:entries.some(r=>r.data.actual!==null)?entries.reduce((s,r)=>s+(r.data.actual??0),0):null,actual_unknown:entries.filter(r=>r.data.actual===null).length,entry_count:entries.length,source_ids:entries.map(r=>r.id)}}),metrics:active.filter(r=>r.data.kind==='metric'),notice:'跨渠道、跨场次数据分别展示，未去重。未登记金额不等于零元；目标与实际分栏，历史结案另列。'};}
export function outcomeSections(rows:{id:string;revision:number;data:any}[]){const s=outcomeSummary(rows);return [{title:'本次活动 · 效果与口径',body:s.notice+'\n\n'+(s.metrics.map(r=>`${r.data.channel}｜${r.data.metric}（${r.data.unit}）\n目标：${r.data.planned??'未设定'}；实际：${r.data.actual??'未登记'}\n范围：${r.data.period}\n来源：${r.data.source.label} · ${r.data.source.locator} · ${r.data.source.version}\n来源记录：${r.id}@${r.revision}\n${r.data.notes}`).join('\n\n')||'暂无本次活动效果记录。')},{title:'本次活动 · 费用分账',body:s.expenses.map(x=>`${x.label}｜记录${x.entry_count}条\n已知目标金额：${x.planned_known??'未登记'}；已知实付：${x.actual_known??'未登记'}；未填实付${x.actual_unknown}条\n来源：${x.source_ids.join('、')||'未登记'}`).join('\n\n')+'\n\n已知部分不能当作完整总费用。模型次数和token不能直接换算人民币账单。'},{title:'本次活动 · 记录核对',body:rows.map(r=>`${r.id}@${r.revision}｜${r.data.revoked_at?'已撤回：'+r.data.revoke_reason:'有效'}\n统计时间：${r.data.observed_at}\n来源链接：${r.data.source.url||'未提供'}\n文件：${r.data.source.asset_id||'无'}`).join('\n\n')||'暂无记录。'}];}
