import {z} from 'zod';
import {activityRecord} from './activity-server';
import {record,database,bucket,HttpError,now} from './server';
import {brandSnapshot} from './production-brand';
import {sha256} from './production-content';
const mediaRef=z.object({asset_id:z.string().max(200),source_in:z.number().finite().min(0).max(86400),rights_note:z.string().trim().max(2000)}).strict();
export const videoPlanSchema=z.object({project_id:z.string().min(1),script_id:z.string().min(1),script_hash:z.string().regex(/^[a-f0-9]{64}$/),revision:z.number().int().nonnegative(),shots:z.array(mediaRef.extend({shot_id:z.string().min(1).max(100)})).max(60),voice:mediaRef,music:mediaRef,voice_volume:z.number().min(0).max(2),music_volume:z.number().min(0).max(1),srt:z.string().max(20000),subtitle_source:z.string().trim().max(2000),composition:z.object({transition:z.enum(['cut','fade']),still_motion:z.enum(['hold','slow_zoom']).optional(),cover_text:z.string().max(80),endcard_text:z.string().max(1000),endcard_seconds:z.number().min(1).max(5)}).strict().optional(),consent:z.literal(true)}).strict();
export function automaticScriptSrt(timeline:any[]){const clock=(v:number)=>{const ms=Math.round(v*1000);return `${String(Math.floor(ms/3600000)).padStart(2,'0')}:${String(Math.floor(ms/60000)%60).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')},${String(ms%1000).padStart(3,'0')}`};let n=0;return timeline.map(s=>{const text=[s.subtitle,s.dialogue,s.voiceover,s.narration].find(v=>typeof v==='string'&&v.trim());return text?`${++n}\n${clock(s.start)} --> ${clock(s.end)}\n${text.trim()}\n`:''}).filter(Boolean).join('\n')}
export function subtitleCues(raw:string,duration:number){
 if(!raw.trim())return [];
 const cues=raw.replace(/\r/g,'').trim().split(/\n\s*\n/).map(block=>{const lines=block.split('\n');if(!/^\d+$/.test(lines[0]))throw new HttpError(400,'字幕每段需有序号');const match=lines[1]?.match(/^(\d{2}):(\d{2}):(\d{2}),(\d{3}) --> (\d{2}):(\d{2}):(\d{2}),(\d{3})$/);if(!match)throw new HttpError(400,'请填写标准SRT时间码');const n=match.slice(1).map(Number);if(n[1]>=60||n[2]>=60||n[5]>=60||n[6]>=60)throw new HttpError(400,'字幕时间码无效');const start=n[0]*3600+n[1]*60+n[2]+n[3]/1000,end=n[4]*3600+n[5]*60+n[6]+n[7]/1000,text=lines.slice(2).join('\n').trim();if(!text||start>=end||end>duration)throw new HttpError(400,'字幕文本不能为空，时间必须在片长范围内');return {start,end,text}});
 for(let i=1;i<cues.length;i++)if(cues[i].start<cues[i-1].end)throw new HttpError(400,'字幕需按时间排序且不能重叠');return cues;
}
export async function approvedVideoScript(project:string,id:string){
 const r=await record(id,project),a=await activityRecord(project);if(r.type!=='run'||r.data.key!=='script'||r.data.review_status!=='approved'||r.data.v2_output?.execution_mode!=='live')throw new HttpError(400,'请选择本项目人工批准的真实脚本');if((r.data.activity_revision||0)!==(a?.revision||0))throw new HttpError(409,'活动事实修改后，脚本需要重新核对批准');const current=await database().prepare('SELECT revision FROM projects WHERE id=?').bind(project).first<any>();if(r.data.project_revision!==current.revision)throw new HttpError(409,'项目版本已改变，请重新核对脚本');const shots=r.data.v2_output?.structured_output?.shots;if(!Array.isArray(shots)||!shots.length||shots.length>60)throw new HttpError(400,'批准脚本缺少分镜');let cursor=0;const ids=new Set<string>();const timeline=shots.map((s:any)=>{if(typeof s.id!=='string'||!s.id||ids.has(s.id)||!['live','aigc'].includes(s.type)||typeof s.duration!=='number'||!Number.isFinite(s.duration)||s.duration<=0)throw new HttpError(400,'镜头编号、类型或时长无效');ids.add(s.id);const item={...s,start:cursor,end:cursor+s.duration};cursor+=s.duration;return item});if(Math.abs(cursor-30)>0.5)throw new HttpError(409,'镜头总长需要为30秒（允许±0.5秒），请先修订并批准脚本');return {r,a,current,timeline,duration:cursor,hash:await sha256(JSON.stringify(r.data.v2_output))};
}
async function checkedMedia(project:string,ref:z.infer<typeof mediaRef>,role:string){
 if(!ref.asset_id)return null;if(!ref.rights_note)throw new HttpError(400,'已选素材需填写来源与使用许可说明');const r=await record(ref.asset_id,project);if(r.type!=='asset'||r.data.review_status!=='approved')throw new HttpError(409,'素材必须属于本项目并已人工批准');const mime=String(r.data.mime||'');if(role==='picture'?!/^(video\/|image\/(png|jpeg|webp))/.test(mime):!mime.startsWith('audio/'))throw new HttpError(400,'镜头请选择图片或视频，音轨请选择音频');const obj=await bucket().get(r.data.storage_key);if(!obj)throw new HttpError(404,'素材文件不存在');const bytes=new Uint8Array(await obj.arrayBuffer());return {...ref,asset_id:r.id,revision:r.revision,mime,filename:r.data.filename,sha256:await sha256(bytes)};
}
export async function saveVideoPlan(raw:unknown){
 const b=videoPlanSchema.parse(raw),s=await approvedVideoScript(b.project_id,b.script_id);if(s.hash!==b.script_hash)throw new HttpError(409,'脚本版本已更新，请刷新');const expected=s.timeline.map((x:any)=>x.id);if(b.shots.length!==expected.length||new Set(b.shots.map(x=>x.shot_id)).size!==expected.length||b.shots.some(x=>!expected.includes(x.shot_id)))throw new HttpError(400,'镜头槽必须与批准脚本一致');const asset_snapshots:any[]=[];for(const ref of b.shots){const media=await checkedMedia(b.project_id,ref,'picture');if(media)asset_snapshots.push({...media,role:'picture',shot_id:ref.shot_id})}for(const role of ['voice','music'] as const){const media=await checkedMedia(b.project_id,b[role],role);if(media)asset_snapshots.push({...media,role})}subtitleCues(b.srt,s.duration);if(b.srt.trim()&&!b.subtitle_source)throw new HttpError(400,'请填写字幕来源及校对说明');const id='video-plan-'+b.script_id,old=await record(id,b.project_id).catch(()=>null);if((old?.revision||0)!==b.revision)throw new HttpError(409,'视频准备方案已更新，请刷新');const profile=await brandSnapshot(b.project_id),t=now(),value={...b,brand_profile_sha256:profile?.sha256||null,asset_snapshots,activity_revision:s.a?.revision||0,script_revision:s.r.revision,confirmed_at:t,history:[...(old?.data.history||[]),...(old?[{revision:old.revision,script_hash:old.data.script_hash,shots:old.data.shots,voice:old.data.voice,music:old.data.music,srt:old.data.srt,at:old.updated_at}]:[])]};const q=old?database().prepare('UPDATE records SET data=?,revision=revision+1,updated_at=? WHERE id=? AND project_id=? AND revision=?').bind(JSON.stringify(value),t,id,b.project_id,b.revision):database().prepare("INSERT OR IGNORE INTO records VALUES (?,?,'video_plan',?,1,?,?)").bind(id,b.project_id,JSON.stringify(value),t,t);if(!(await q.run()).meta.changes)throw new HttpError(409,'保存冲突，请刷新');return {id,revision:b.revision+1,data:value};
}
export async function videoPreparation(project:string,script:string,allowStale=false){
 const s=await approvedVideoScript(project,script),profile=await brandSnapshot(project),old=await record('video-plan-'+script,project).catch(()=>null),stale=!!old&&((old.data.brand_profile_sha256||null)!==(profile?.sha256||null)||old.data.script_hash!==s.hash||old.data.activity_revision!==(s.a?.revision||0)),p=stale?null:old;if(stale&&!allowStale)throw new HttpError(409,'视频准备方案引用旧版脚本或事实，请重新保存');const assets:any[]=[],timeline:any[]=[];const resolve=async(ref:z.infer<typeof mediaRef>,role:string,shotId?:string)=>{try{const media=await checkedMedia(project,ref,role);if(media&&p){const saved=p.data.asset_snapshots?.find((x:any)=>x.asset_id===media.asset_id&&x.role===role&&x.shot_id===shotId);if(!saved||saved.revision!==media.revision||saved.sha256!==media.sha256)throw new HttpError(409,'素材版本已改变，请重新保存视频准备方案')}return media}catch(e){if(allowStale)return null;throw e}};
 for(const shot of s.timeline){const ref=p?.data.shots.find((x:any)=>x.shot_id===shot.id)||{asset_id:shot.asset_ref||'',source_in:0,rights_note:shot.asset_ref?'原批准脚本关联素材；使用许可待人工复核':''};const media=await resolve(ref,'picture',shot.id);if(media)assets.push({...media,role:'picture',shot_id:shot.id});timeline.push({...shot,asset_ref:media?.asset_id||null,source_in:ref.source_in})}
 for(const role of ['voice','music']){const ref=p?.data[role];if(ref){const media=await resolve(ref,role);if(media)assets.push({...media,role})}}
 const subtitles=subtitleCues(p?.data.srt||'',s.duration),missing_shots=timeline.filter(x=>!x.asset_ref).map(x=>x.id),missing_resources=[...missing_shots.map(id=>'镜头 '+id),...['voice','music'].filter(role=>!assets.some(x=>x.role===role)),...(!subtitles.length?['srt']:[]),'持久FFmpeg/Remotion合成执行环境','素材实际时长、音画与版权人工核准'];
 return {schema_version:2,previous_plan_revision:old?.revision||0,stale_plan:stale,project_id:project,project_revision:s.current.revision,activity_revision:s.a?.revision||0,activity:s.a?.data||null,script:{id:s.r.id,revision:s.r.revision,workflow_run_id:s.r.data.workflow_run_id,sha256:s.hash,reviews:s.r.data.review_history},plan:p?{id:p.id,revision:p.revision,data:p.data}:null,render:{status:'blocked',reason:'尚未接入可持久执行FFmpeg或Remotion的合成资源',target_duration:30,actual_planned_duration:s.duration,width:1080,height:1920,fps:30,tracks:['picture','voice','music','srt'],voice_volume:p?.data.voice_volume??1,music_volume:p?.data.music_volume??0.15,estimated_render_cost:null},timeline,approved_assets:assets,suggested_srt:automaticScriptSrt(s.timeline),composition:p?.data.composition||{transition:'cut',still_motion:'hold',cover_text:s.a?.data.event_name||'',endcard_text:[s.a?.data.event_name,s.a?.data.time,s.a?.data.place,s.a?.data.contact,s.a?.data.mandatory].filter(Boolean).join('\n'),endcard_seconds:3},subtitles,missing_shots,missing_resources,mixed_live_aigc:timeline.some(x=>x.type==='live')&&timeline.some(x=>x.type==='aigc'),notice:'本包是已批准脚本、镜头槽和音轨字幕准备方案；尚未合成MP4，也未验证文件实际时长。未进行新模型调用。'};
}
