import {env} from 'cloudflare:workers';
import {z} from 'zod';
import {database,bucket,record,HttpError,now} from './server';
import {approvedVideoScript} from './production-video';
import {sha256} from './production-content';
import {stableJson} from './production-batch';
import {productionConfiguration} from './production-server';
import {referenceImage,publicConfig,persistVideo} from './ark';
import {streamDifyRun,getDifyRun,type DifyRun} from './dify-run-transport';
import {queryDifyVideo} from './dify-media';
const key=()=>(env as unknown as Record<string,string>).DIFY_WORKFLOW_API_KEY;
async function update(r:any,data:any){const q=await database().prepare("UPDATE records SET data=?,revision=revision+1,updated_at=? WHERE id=? AND project_id=? AND revision=? AND type='video_shot_task'").bind(JSON.stringify(data),now(),r.id,r.project_id,r.revision).run();if(!q.meta.changes)throw new HttpError(409,'镜头状态已改变，请重新读取');return {...r,data,revision:r.revision+1}}
export async function listShotTasks(project:string,script?:string){const q=await database().prepare("SELECT * FROM records WHERE project_id=? AND type='video_shot_task' ORDER BY created_at DESC LIMIT 100").bind(project).all<any>();return q.results.map(r=>({...r,data:JSON.parse(r.data)})).filter(r=>!script||r.data.script_id===script)}
const schema=z.object({project_id:z.string().min(1),script_id:z.string().min(1),script_hash:z.string().regex(/^[a-f0-9]{64}$/),shot_id:z.string().min(1),keyframe_asset_id:z.string().min(1),request_id:z.string().uuid(),retry_of:z.string().optional(),budget_seconds:z.literal(5),consent:z.literal(true)}).strict();
export async function submitShotTask(raw:unknown){const r=schema.parse(raw),requestHash=await sha256(stableJson(r)),id='video-shot-'+r.request_id,old=await record(id,r.project_id).catch(()=>null);if(old){if(old.type!=='video_shot_task'||old.data.request_sha256!==requestHash)throw new HttpError(409,'请求编号已用于其他镜头');return old}const s=await approvedVideoScript(r.project_id,r.script_id);if(s.hash!==r.script_hash)throw new HttpError(409,'脚本已改变，请刷新');const shot=s.timeline.find((x:any)=>x.id===r.shot_id);if(!shot||shot.type!=='aigc'||shot.duration!==5)throw new HttpError(400,'当前工具只生成批准的五秒AIGC镜头；请先将长镜头拆分并重新批准');const asset=await record(r.keyframe_asset_id,r.project_id);if(asset.type!=='asset'||asset.data.review_status!=='approved')throw new HttpError(409,'请选择本项目已批准的关键帧');const image=await referenceImage(asset.id,r.project_id),bytes=await bucket().get(asset.data.storage_key),frameHash=await sha256(await bytes!.arrayBuffer()),identity=await sha256(stableJson({script_hash:s.hash,shot_id:r.shot_id,keyframe:frameHash}));const prior=(await listShotTasks(r.project_id,r.script_id)).find(x=>x.data.identity===identity);if(prior&&!r.retry_of)return prior;if(r.retry_of&&(!prior||prior.id!==r.retry_of||prior.data.status!=='failed'))throw new HttpError(409,'只有确认失败的原镜头可明确重试；未知任务需先查询');const c=await publicConfig(),configuration=await productionConfiguration(),prompt=[shot.description,shot.visual,shot.action,shot.generation_prompt,shot.prompt].filter(v=>typeof v==='string').join('；').slice(0,2500)+'。根据批准关键帧制作五秒竖屏片段，保持角色一致。不得生成字幕、LOGO、二维码、活动事实或新角色。';const inputs={brief:JSON.stringify({kind:'video',project_id:r.project_id,request_id:r.request_id,prompt,approved_run_id:r.script_id,reference_image:image,ratio:'9:16',consent:true}),requirements:'能力类型：media_video_submit'},t=now(),data={...r,request_sha256:requestHash,identity,keyframe_sha256:frameHash,keyframe_revision:asset.revision,configuration,expected_model:c.video_model,status:'prepared',reserved_seconds:5,spent_seconds:0,actual_cost:null,review_status:'pending'};await bucket().put('_private/video-shot-request/'+id,JSON.stringify(inputs));await database().prepare("INSERT OR IGNORE INTO records VALUES (?,?,'video_shot_task',?,1,?,?)").bind(id,r.project_id,JSON.stringify(data),t,t).run();let stored=await record(id,r.project_id);if(stored.data.request_sha256!==requestHash)throw new HttpError(409,'镜头请求冲突');if(stored.data.status!=='prepared')return stored;stored=await update(stored,{...stored.data,status:'submitting'});
 try{const run=await streamDifyRun(key(),inputs,r.project_id,async run=>{const latest=await record(id,r.project_id);if(latest.data.workflow_run_id&&latest.data.workflow_run_id!==run.workflow_run_id)throw new HttpError(409,'原运行号冲突');await update(latest,{...latest.data,workflow_run_id:run.workflow_run_id,status:'running'})},configuration.workflow_id);return archiveShotRun(await record(id,r.project_id),run)}catch{const current=await record(id,r.project_id);return update(current,{...current.data,status:'unknown',error:'提交结果未知；查询或绑定原Dify运行，不重复生成'})}}
async function archiveShotRun(r:any,run:DifyRun){if(run.workflow_id&&run.workflow_id!==r.data.configuration.workflow_id)throw new HttpError(409,'发布版本不匹配');if(['failed','stopped'].includes(run.status))return update(r,{...r.data,status:'failed',error:'Dify原运行已确认失败',reserved_seconds:0,spent_seconds:5});if(run.status!=='succeeded')return r;const list:any=run.outputs.video_submit_result,remote=list?.[0];if(!Array.isArray(list)||list.length!==1||!/^cgt-[A-Za-z0-9_-]{1,100}$/.test(remote?.id||''))throw new HttpError(409,'视频提交结果无有效任务号，保留原运行');if(r.data.provider_task_id&&r.data.provider_task_id!==remote.id)throw new HttpError(409,'不能覆盖原视频任务号');return update(r,{...r.data,status:'queued',workflow_run_id:run.id,provider_task_id:remote.id,reserved_seconds:0,spent_seconds:5,error:null})}
export async function queryShotTask(project:string,id:string,bindId?:string){let r=await record(id,project);if(r.type!=='video_shot_task')throw new HttpError(404,'镜头任务不存在');if(['archived','failed'].includes(r.data.status))return r;if(!r.data.provider_task_id){const runId=r.data.workflow_run_id||bindId;if(!runId)return r;const run=await getDifyRun(key(),runId);if(bindId&&!r.data.workflow_run_id){const saved=await bucket().get('_private/video-shot-request/'+id),inputs=await saved!.json<any>();if(run.workflow_id!==r.data.configuration.workflow_id||stableJson(run.inputs)!==stableJson(inputs))throw new HttpError(409,'原运行版本或输入不匹配，未绑定')}r=await archiveShotRun(r,run);if(!r.data.provider_task_id)return r}const query=await queryDifyVideo({project_id:project,task_id:r.data.provider_task_id},r.data.expected_model,r.data.configuration.workflow_id),result=query.result;if(['failed','cancelled','expired'].includes(result.status))return update(r,{...r.data,status:'failed',provider_status:result.status,error:'原视频任务已确认失败或终止'});if(result.status!=='succeeded')return update(r,{...r.data,status:result.status,provider_status:result.status});try{const asset_id=await persistVideo(id,project,result.content?.video_url||result.video_url);return update(r,{...r.data,status:'archived',asset_id,review_status:'pending',error:null})}catch{return update(r,{...r.data,status:'download_pending',error:'原片段已生成，下载暂未完成；只查询原任务和重试下载'})}}
export async function shotTick(){const q=await database().prepare("SELECT id,project_id FROM records WHERE type='video_shot_task' AND json_extract(data,'$.status') IN ('submitting','unknown','running','queued','download_pending') ORDER BY updated_at LIMIT 1").first<any>();return q?queryShotTask(q.project_id,q.id):null}
