import {z} from 'zod';
import {database,bucket,HttpError,now} from './server';
import {activityRecord} from './activity-server';
import {readBatch,createBatch,mutateBatch} from './production-store';
import {newBatch,stableJson,type ProductionJob} from './production-batch';
import {loadProductionArtifact,saveProductionArtifact} from './production-server';
import {copyText,completeCopy} from './copywriting';
import {sha256} from './production-content';

export async function revisionImpact(project:string,parentId:string){
 const old=await readBatch(project,parentId),a=await activityRecord(project);
 if(!a)throw new HttpError(409,'请先保存活动事实');
 const activity={event_name:a.data.event_name,time:a.data.time,place:a.data.place,contact:a.data.contact,mandatory:a.data.mandatory};
 const fields=(Object.keys(activity) as (keyof typeof activity)[]).filter(k=>activity[k]!==old.data.input.activity[k]).map(field=>({field,before:old.data.input.activity[field],after:activity[field]}));
 const supported=activity.event_name===old.data.input.activity.event_name;
 const slots=old.data.jobs.filter(j=>/^(poster-[1-4]|copy-)/.test(j.slot)&&j.state==='succeeded').map(j=>({slot:j.slot,action:j.kind==='image'?'仅更新文字层，复用背景':'更新固定事实，复用正文',model_calls:0}));
 const value={parent_id:parentId,parent_revision:old.revision,activity_revision:a.revision,fields,supported,slots,video_effect:fields.length?'旧脚本和视频方案暂停正式交付，需核对字幕与片尾后重新批准':'无变化',estimated:{text:0,image:0,video_seconds:0},notice:supported?'选择本次要更新的成品；未选的受影响项保留在旧批次，不进入新批正式包。':'主题发生改变，请重新批准创作方向；品牌/IP变更需要重做画面与相关镜头。'};
 return {...value,plan_hash:await sha256(stableJson(value))};
}
/** A scoped fact revision reuses pixels. Omitted affected slots cannot enter its delivery. */
export async function reviseProductionFacts(parentId:string,raw:unknown){
 const r=z.object({project_id:z.string().min(1),revision:z.number().int().positive(),request_id:z.string().uuid(),consent:z.literal(true),plan_hash:z.string().regex(/^[a-f0-9]{64}$/).optional(),scope:z.array(z.string()).min(1).max(8).optional()}).strict().parse(raw),old=await readBatch(r.project_id,parentId);if(old.revision!==r.revision)throw new HttpError(409,'旧批次已改变，请重新读取。');
 const impact=await revisionImpact(r.project_id,parentId);if(r.plan_hash&&impact.plan_hash!==r.plan_hash)throw new HttpError(409,'修改影响已变化，请重新预览');const scope=r.scope||impact.slots.map(j=>j.slot);if(new Set(scope).size!==scope.length||scope.some(slot=>!impact.slots.some(j=>j.slot===slot)))throw new HttpError(400,'更新范围无效');
 if(!old.data.jobs.some(j=>/^(poster-[1-4]|copy-)/.test(j.slot)&&j.state==='succeeded'))throw new HttpError(409,'先归档至少一项成功成果，再建立改字修订；原未知任务继续留在旧批核对');
 const a=await activityRecord(r.project_id),project=await database().prepare('SELECT revision,name,brand,school FROM projects WHERE id=?').bind(r.project_id).first<any>();if(!a||a.data.event_name!==old.data.input.activity.event_name)throw new HttpError(409,'活动主题改变需要重新批准创作计划；本操作只更新固定文字事实。');
 const activity={event_name:a.data.event_name,time:a.data.time,place:a.data.place,contact:a.data.contact,mandatory:a.data.mandatory};if(stableJson(activity)===stableJson(old.data.input.activity))throw new HttpError(409,'活动文字没有改变。');
 const id='content-brief-revision-'+r.request_id,t=now(),data={...old.data.input.approved_brief,asset_id:old.data.input.brand.id,asset_revision:old.data.input.brand.revision,source_ids:old.data.input.approved_brief.source_ids,activity,activity_revision:a.revision,approved_at:t,source_brief_id:old.data.input.approved_brief.id,reason:'人工确认固定事实修订，主题和背景沿用原批准版本'};
 await database().prepare("INSERT OR IGNORE INTO records VALUES (?,?,'content_brief',?,1,?,?)").bind(id,r.project_id,JSON.stringify(data),t,t).run();
 const input={...old.data.input,quality_control:false,reuse_only:true,production_scope:scope,image_grounding:old.data.input.image_grounding&&old.data.jobs.find(j=>j.slot==='vision-poster-1')?.state==='succeeded',request_id:r.request_id,project_revision:project.revision,project_snapshot:{name:project.name,brand:project.brand,school:project.school},activity_revision:a.revision,activity,approved_brief:{...old.data.input.approved_brief,id,revision:1}},batch=await newBatch(input);
 let next=await createBatch(batch);const lineage={parent_batch_id:parentId,parent_input_hash:old.data.input_hash,reused_backgrounds:true,model_calls:0,scope,impact_hash:impact.plan_hash,changed:Object.keys(activity).filter(k=>activity[k as keyof typeof activity]!==old.data.input.activity[k as keyof typeof activity])};
 await bucket().put('_private/production-lineage/'+batch.id,JSON.stringify(lineage));
 for(const job of old.data.jobs){
  if(!next.data.jobs.some(j=>j.slot===job.slot))continue;
  if(!job.slot.startsWith('vision')&&!scope.includes(job.slot)){if(next.data.jobs.find(j=>j.slot===job.slot)?.state!=='cancelled')next=await mutateBatch(r.project_id,batch.id,next.revision,b=>({...b,jobs:b.jobs.map(j=>j.slot===job.slot?{...j,state:'cancelled',error:'本次未选更新；旧事实作品仅保留在原批次'}:j)}));continue;}
  if(next.data.jobs.find(j=>j.slot===job.slot)?.state==='succeeded')continue;
  const source=(await loadProductionArtifact(r.project_id,parentId,job.slot)).artifact,currentAttempt=job.attempts.at(-1)!;
  const imported:ProductionJob={...job,review:'pending',reviews:[],artifact:undefined,attempts:[{...currentAttempt,units:{text:0,image:0,video_seconds:0},state:'spent',reason:'reused_from:'+parentId}]};
  const staged={...next.data,jobs:next.data.jobs.map(j=>j.slot===job.slot?imported:j)};
  let content:any={};
  if(source.layout){let headline=source.layout.headline,details=[...source.layout.details];for(const k of ['time','place','contact','mandatory'] as const){const before=old.data.input.activity[k],after=activity[k];if(before&&before!==after){headline=headline.split(before).join(after);details=details.map(text=>text.split(before).join(after)).filter(text=>text.trim()&&!['时间：','地点：','联系：'].includes(text.trim()))}}for(const [key,label] of [['time','时间：'],['place','地点：'],['contact','联系：'],['mandatory','']] as const)if(activity[key]&&!(headline+'\n'+details.join('\n')).includes(activity[key]))details.push(label+activity[key]);content={asset_id:source.asset_id,background_sha256:source.background_sha256,layout:{...source.layout,headline,details}};}
  if(source.observation)content={observation:source.observation};
  if(source.copy){let title=source.copy.title,body=source.copy.body;for(const k of ['time','place','contact','mandatory'] as const){const before=old.data.input.activity[k],after=activity[k];if(before&&before!==after){title=title.split(before).join(after);body=body.split(before).join(after)}}const c=completeCopy({title,body},{required_text:activity.mandatory,time:activity.time,location:activity.place,contact:activity.contact});content={copy:{...c,platform:source.copy.platform,tags:source.copy.tags,text:copyText(source.copy.platform,c.title,c.body,source.copy.tags)}};}
  if(job.slot==='copy-douyin'&&staged.input.image_grounding){const obs=next.data.jobs.find(j=>j.slot==='vision-poster-1')?.artifact;if(obs)content.upstream=[{slot:'vision-poster-1',sha256:obs.sha256}]}const artifact=await saveProductionArtifact(staged,job.slot,{id:source.workflow_run_id,total_tokens:null,elapsed_time:null},content);
  next=await mutateBatch(r.project_id,batch.id,next.revision,b=>({...b,jobs:b.jobs.map(j=>j.slot===job.slot?{...imported,artifact}:j)}));
 }
 await database().prepare("INSERT OR IGNORE INTO records VALUES (?,?,'production_control',?,1,?,?)").bind('control-'+batch.id,r.project_id,JSON.stringify({enabled:false,lineage}),t,t).run();return next;
}

export async function visualRevisionImpact(project:string,parentId:string,briefId:string){const old=await readBatch(project,parentId),brief=await (await import('./server')).record(briefId,project);if(brief.type!=='content_brief')throw new HttpError(400,'先批准要使用的新创作简报');const {brandSnapshot}=await import('./production-brand'),profile=await brandSnapshot(project),fields=[{field:'IP',before:old.data.input.brand.id+'@'+old.data.input.brand.revision,after:brief.data.asset_id+'@'+brief.data.asset_revision},{field:'theme',before:old.data.input.approved_brief.theme,after:brief.data.theme},{field:'style',before:old.data.input.approved_brief.style,after:brief.data.style},{field:'CTA',before:old.data.input.approved_brief.cta,after:brief.data.cta},{field:'brand_profile',before:old.data.input.brand_profile?.sha256||'',after:profile?.sha256||''}].filter(f=>f.before!==f.after),videoRows=await database().prepare("SELECT id,data FROM records WHERE project_id=? AND type='run' AND json_extract(data,'$.key')='script' AND json_extract(data,'$.review_status')='approved' ORDER BY id").bind(project).all<any>(),video_effect=videoRows.results.map(r=>{const d=JSON.parse(r.data);return {script_id:r.id,shots:(d.v2_output?.structured_output?.shots||[]).filter((s:any)=>s.type==='aigc').map((s:any)=>s.id),action:'重新核准IP关键帧后，按所选镜头单独生成；实拍素材可在确认适用后复用，片尾和字幕重新核对'}}),value={parent_id:parentId,parent_revision:old.revision,brief_id:briefId,brief_revision:brief.revision,brand_profile_sha256:profile?.sha256||null,fields,slots:['poster-1','poster-2','poster-3','poster-4','copy-weibo','copy-xiaohongshu','copy-douyin','copy-moments'],video_effect,notice:'只生成所选新视觉/文案。未选旧作品保留原批，不混入新品牌版本；抖音配文需同时选择海报1作为新观察依据。每张海报可加一次质检和最多一轮返修，最终仍需人工批准。'};return {...value,plan_hash:await sha256(stableJson(value))}}
export async function reviseProductionVisual(parentId:string,raw:unknown){const r=z.object({mode:z.literal('visual'),project_id:z.string(),new_brief_id:z.string(),request_id:z.string().uuid(),plan_hash:z.string().regex(/^[a-f0-9]{64}$/),scope:z.array(z.string()).min(1).max(8),quality_control:z.boolean(),budget:z.object({text:z.number().int().min(0).max(100),image:z.number().int().min(0).max(100),video_seconds:z.literal(0)}).strict(),consent:z.literal(true)}).strict().parse(raw),plan=await visualRevisionImpact(r.project_id,parentId,r.new_brief_id);if(plan.plan_hash!==r.plan_hash)throw new HttpError(409,'视觉变更计划已变化，请重新预览');if(!plan.fields.length)throw new HttpError(409,'主题与品牌没有改变，改固定事实请使用改字修订');const p=await database().prepare('SELECT revision FROM projects WHERE id=?').bind(r.project_id).first<any>(),{createProduction}=await import('./production-server'),batch=await createProduction({project_id:r.project_id,brief_id:r.new_brief_id,project_revision:p.revision,request_id:r.request_id,scope:r.scope,quality_control:r.quality_control,budget:r.budget,consent:true}),lineage={parent_batch_id:parentId,revision_kind:'visual',impact_hash:plan.plan_hash,scope:r.scope,fields:plan.fields,video_followup:plan.video_effect,video_status:'pending_human_keyframe_and_script_confirmation',old_callbacks_overwrite_new:false};await bucket().put('_private/production-lineage/'+batch.data.id,JSON.stringify(lineage));return batch}
