import {z} from 'zod';
import {database,bucket,record,HttpError,now} from './server';
import {loadProductionArtifact} from './production-server';
import {printCheck,printSpecSchema} from './production-print';
import {imageDimensions} from './image-dimensions';
import {activityRecord} from './activity-server';
import {readProcurement} from './materials-server';
import {readUnifiedExecution} from './unified-tasks';
import {sha256} from './production-content';
export const printContractSchema=z.object({project_id:z.string().min(1),batch_id:z.string().min(1),slot:z.string().regex(/^poster-[1-4]$/),artifact_hash:z.string().regex(/^[a-f0-9]{64}$/),revision:z.number().int().nonnegative(),spec:printSpecSchema,material_ids:z.array(z.string().min(1)).max(150),supplier_note:z.string().trim().max(2000),consent:z.literal(true)}).strict();
export async function savePrintContract(raw:unknown){const b=printContractSchema.parse(raw),loaded=await loadProductionArtifact(b.project_id,b.batch_id,b.slot),a=await activityRecord(b.project_id);if(loaded.job.review!=='approved'||loaded.job.artifact!.sha256!==b.artifact_hash)throw new HttpError(409,'先批准当前海报版本，再确认送印规格');if(a?.revision!==loaded.batch.data.input.activity_revision)throw new HttpError(409,'活动事实已改变，旧稿不能作为本次送印版本');const bill=await readProcurement(b.project_id);for(const id of b.material_ids)if(!bill.lines.some(l=>l.material_id===id))throw new HttpError(400,'关联物料必须来自本项目已保存的采购清单');
 const asset=await record(loaded.artifact.asset_id!,b.project_id),object=await bucket().get(asset.data.storage_key);if(!object)throw new HttpError(404,'原图不存在');const bytes=new Uint8Array(await object.arrayBuffer()),check=printCheck(b.spec,imageDimensions(bytes));const id='print-'+b.batch_id+'-'+b.slot,old=await record(id,b.project_id).catch(()=>null);if((old?.revision||0)!==b.revision)throw new HttpError(409,'送印规格已更新，请刷新');const t=now(),value={...b,check,background_sha256:await sha256(bytes),activity_revision:a.revision,confirmed_at:t,press_file_status:'pending',color_and_font_status:'pending',history:[...(old?.data.history||[]),...(old?[{revision:old.revision,spec:old.data.spec,material_ids:old.data.material_ids,artifact_hash:old.data.artifact_hash,at:old.updated_at}]:[])]};
 const statement=old?database().prepare('UPDATE records SET data=?,revision=revision+1,updated_at=? WHERE id=? AND project_id=? AND revision=?').bind(JSON.stringify(value),t,id,b.project_id,b.revision):database().prepare("INSERT OR IGNORE INTO records VALUES (?,?,'print_contract',?,1,?,?)").bind(id,b.project_id,JSON.stringify(value),t,t);const result=await statement.run();if(!result.meta.changes)throw new HttpError(409,'规格保存冲突，请刷新');return {id,revision:b.revision+1,data:value};
}
export async function offlinePreparation(project:string,batch:string){const a=await activityRecord(project),r=await record(batch,project);if(r.type!=='production_batch')throw new HttpError(404,'批次不存在');if(a?.revision!==r.data.input.activity_revision)throw new HttpError(409,'活动事实已改变，请先建立并审核改字版本');const bill=await readProcurement(project),execution=await readUnifiedExecution(project),rows=await database().prepare("SELECT id,revision,data FROM records WHERE project_id=? AND type IN ('print_contract','print_proof','execution_evidence') ORDER BY created_at,id").bind(project).all<any>(),records=rows.results.map(x=>({...x,data:JSON.parse(x.data)}));const designs=[];
 for(const job of r.data.jobs.filter((j:any)=>j.slot.startsWith('poster')&&j.state==='succeeded'&&j.review==='approved')){const loaded=await loadProductionArtifact(project,batch,job.slot),contract=records.find(x=>x.id==='print-'+batch+'-'+job.slot&&x.data.artifact_hash===job.artifact.sha256);designs.push({slot:job.slot,artifact:loaded.artifact,approved_hash:job.artifact.sha256,review_history:job.reviews||[],contract:contract||null,print_proof:records.find(x=>x.data.batch_id===batch&&x.data.slot===job.slot&&x.data.artifact_hash===job.artifact.sha256&&x.data.contract_revision===contract?.revision&&x.data.status==='rgb_proof_pending_human_and_supplier')||null,preflight:contract?.data.check||{status:'blocked',reasons:['尚未确认本次送印规格']},press_file_status:'pending'});}
 if(!designs.length)throw new HttpError(400,'先审核通过至少一张海报');return {schema_version:1,package_kind:'offline_preparation',project_id:project,batch_id:batch,input_hash:r.data.input_hash,activity_revision:a?.revision,activity:a?.data,designs,procurement:bill,execution,evidence:records.filter(x=>x.data.task_id),checklists:[{stage:'印制确认',items:['核对设计版本与必留文字','核对印厂尺寸、纸张、出血、ICC和字体','取得打样与报价确认']},{stage:'收货与布置',items:['登记实际数量与凭据','核对破损与缺件','按分工完成现场布置及安全检查']},{stage:'现场与发布',items:['登记现场照片或发布链接','分别记录观看、互动、报名和到场','记录采购实付与其他费用']}],formal_print:{status:'blocked',reasons:['本包提供批准设计、规格和准备清单；尚未生成并人工核准印厂要求的送印文件']},exported_at:now()};}
