import {env} from 'cloudflare:workers';
import {database,bucket,record,HttpError,now} from './server';
import {videoPreparation,approvedVideoScript} from './production-video';
import {readDeliveryZip} from './production-package';
import {sha256} from './production-content';
import {stableJson} from './production-batch';
import {productionFont,productionFontLicense} from './production-font';
const settings=()=>env as unknown as Record<string,string>;
export function rendererCapability(){const s=settings();return {configured:!!s.WOO_RENDERER_URL&&!!s.WOO_RENDERER_TOKEN,verified:s.WOO_RENDERER_VERIFIED==='1',status:s.WOO_RENDERER_URL&&s.WOO_RENDERER_TOKEN?'configured':'blocked',reason:s.WOO_RENDERER_URL&&s.WOO_RENDERER_TOKEN?(s.WOO_RENDERER_VERIFIED==='1'?'持久服务已验连接，成片仍需人工核对':'持久服务已配置，连接仍待验收'):'尚未配置持久FFmpeg服务；可以导出镜头包'}}
function connection(){const s=settings();if(!rendererCapability().configured)throw new HttpError(409,'持久合成服务尚未连接，未提交合成任务');if(s.WOO_RENDERER_TOKEN.length<32)throw new HttpError(503,'合成服务鉴权配置无效');const url=new URL(s.WOO_RENDERER_URL);if(url.protocol!=='https:'||url.username||url.password||url.search||url.hash)throw new HttpError(503,'合成服务地址配置无效');return {url:url.href.replace(/\/$/,''),token:s.WOO_RENDERER_TOKEN}}
async function boundedBytes(r:Response,max:number){if(!r.ok||!r.body)throw new HttpError(502,'合成文件读取失败；只重试下载');if(Number(r.headers.get('content-length'))>max)throw new HttpError(413,'成片超过归档限制');const rd=r.body.getReader(),chunks:Uint8Array[]=[];let size=0;for(;;){const {done,value}=await rd.read();if(done)break;size+=value.length;if(size>max){await rd.cancel();throw new HttpError(413,'成片超过归档限制')}chunks.push(value)}const out=new Uint8Array(size);let pos=0;for(const c of chunks){out.set(c,pos);pos+=c.length}return out}
async function patch(r:any,next:any){const q=await database().prepare("UPDATE records SET data=?,revision=revision+1,updated_at=? WHERE id=? AND project_id=? AND revision=? AND type='video_render'").bind(JSON.stringify(next),now(),r.id,r.project_id,r.revision).run();if(!q.meta.changes)throw new HttpError(409,'合成状态已更新，请重新读取');return {...r,data:next,revision:r.revision+1}}
export async function listVideoRenders(project:string,script?:string){const q=await database().prepare("SELECT * FROM records WHERE project_id=? AND type='video_render' ORDER BY created_at DESC LIMIT 50").bind(project).all<any>();return q.results.map(r=>({...r,data:JSON.parse(r.data)})).filter(r=>!script||r.data.script_id===script)}
export async function submitVideoRender(project:string,requestId:string,bytes:Uint8Array){
 if(!/^[a-f0-9-]{36}$/.test(requestId)||bytes.length>64*1024*1024)throw new HttpError(400,'合成请求编号或文件大小无效');const hash=await sha256(bytes),id='video-render-'+requestId,existing=await record(id,project).catch(()=>null);if(existing){if(existing.type!=='video_render'||existing.data.package_sha256!==hash)throw new HttpError(409,'请求编号已经用于其他视频包');return existing}
 if(!rendererCapability().verified)throw new HttpError(409,'持久合成服务尚未完成真实联调验收，未提交生产任务');const c=connection(),files=readDeliveryZip(bytes,70);let pack:any;try{pack=JSON.parse(new TextDecoder().decode(files.get('shot-package.json')))}catch{throw new HttpError(400,'缺少镜头包清单')}
 if(pack.project_id!==project)throw new HttpError(403,'视频包不属于当前项目');const current=JSON.parse(JSON.stringify(await videoPreparation(project,pack.script?.id||'')));if(!current.plan||current.missing_shots.length||!current.subtitles.length||!['voice','music'].every(role=>current.approved_assets.some((a:any)=>a.role===role)))throw new HttpError(409,'先保存并补全批准镜头、配音、音乐和字幕');
 for(const k of ['script','plan','timeline','composition','activity_revision','project_revision'])if(stableJson(pack[k])!==stableJson((current as any)[k]))throw new HttpError(409,'镜头包不是当前批准方案，请重新导出');
 if(pack.approved_assets.length!==current.approved_assets.length)throw new HttpError(409,'素材清单不一致');const allowed=new Set(['shot-package.json','captions.srt','READ-BEFORE-RENDER.txt','fonts/WOO-CJKsc-Regular.otf','fonts/OFL-NotoSansCJK.txt']);for(let i=0;i<pack.approved_assets.length;i++){const a=pack.approved_assets[i],{delivery_file,...snapshot}=a;if(stableJson(snapshot)!==stableJson(current.approved_assets[i])||!/^media\/[\w.-]+$/.test(delivery_file)||allowed.has(delivery_file))throw new HttpError(409,'素材快照或名称无效');const media=files.get(delivery_file);if(!media||await sha256(media)!==a.sha256)throw new HttpError(409,'镜头素材哈希不一致');allowed.add(delivery_file)}
 if([...files.keys()].some(name=>!allowed.has(name))||await sha256(files.get('fonts/WOO-CJKsc-Regular.otf')||new Uint8Array())!==productionFont.sha256||await sha256(files.get('fonts/OFL-NotoSansCJK.txt')||new Uint8Array())!==productionFontLicense.sha256||new TextDecoder().decode(files.get('captions.srt'))!==current.plan.data.srt)throw new HttpError(409,'字幕、字体或文件清单不一致');
 const key='_private/video-render-input/'+id;await bucket().put(key,bytes);const t=now(),data={request_id:requestId,script_id:pack.script.id,script_hash:pack.script.sha256,plan_revision:pack.plan.revision,activity_revision:pack.activity_revision,project_revision:pack.project_revision,package_sha256:hash,manifest_sha256:await sha256(files.get('shot-package.json')!),storage_key:key,endpoint:c.url,credential_sha256:await sha256(c.token),worker_version:'woo-ffmpeg-render-4',status:'prepared',review_status:'pending',model_calls:0,actual_cost:null};await database().prepare("INSERT OR IGNORE INTO records VALUES (?,?,'video_render',?,1,?,?)").bind(id,project,JSON.stringify(data),t,t).run();let r=await record(id,project);if(r.data.package_sha256!==hash)throw new HttpError(409,'请求冲突');if(r.data.status!=='prepared')return r;r=await patch(r,{...r.data,status:'submitting'});
 try{const res=await fetch(c.url+'/jobs',{method:'POST',headers:{Authorization:'Bearer '+c.token,'Content-Type':'application/zip','X-WOO-Request-ID':requestId},body:bytes.slice().buffer as ArrayBuffer,redirect:'manual',signal:AbortSignal.timeout(45000)});if(!res.ok){if(res.status===400)return patch(r,{...r.data,status:'failed',error:'合成服务拒绝输入，请核对规格后保存新方案'});throw new Error('unconfirmed')}const remote:any=await res.json();return bindRender(r,remote)}catch{return patch(r,{...r.data,status:'unknown',error:'提交结果待确认；只查询原请求编号，不重复提交'})}
}
async function bindRender(r:any,remote:any){if(remote.project!==r.project_id||remote.data?.version!==r.data.worker_version||!/^render-[a-f0-9]{64}$/.test(remote.id)||remote.data?.package_sha256!==r.data.package_sha256||remote.data?.input_manifest_sha256!==r.data.manifest_sha256||!['queued','rendering','succeeded','failed'].includes(remote.status))throw new HttpError(409,'远端合成项目、版本或哈希不匹配');if(r.data.remote_id&&r.data.remote_id!==remote.id)throw new HttpError(409,'原合成任务编号不允许替换');return patch(r,{...r.data,remote_id:remote.id,status:remote.status==='succeeded'?'download_pending':remote.status,technical:remote.data,error:remote.data.error||null})}
export async function queryVideoRender(project:string,id:string){let r=await record(id,project);if(r.type!=='video_render')throw new HttpError(404,'合成任务不存在');if(['archived','failed'].includes(r.data.status))return r;const c=connection();if(c.url!==r.data.endpoint||await sha256(c.token)!==r.data.credential_sha256)throw new HttpError(409,'合成服务配置改变，请恢复原连接查询此任务');const path=r.data.remote_id?'/jobs/'+r.data.remote_id:'/requests/'+r.data.request_id,res=await fetch(c.url+path+'?project_id='+encodeURIComponent(project),{headers:{Authorization:'Bearer '+c.token},redirect:'manual',signal:AbortSignal.timeout(30000)});if(res.status===404)return r;if(!res.ok)throw new HttpError(502,'原合成查询未成功；没有重新提交');r=await bindRender(r,await res.json());if(r.data.status!=='download_pending')return r;
 const meta=r.data.technical.output,cover=r.data.technical.cover;if(meta?.width!==1080||meta.height!==1920||meta.fps!==30||meta.video_codec!=='h264'||!meta.audio_present||Math.abs(meta.duration-30)>.5||!cover)throw new HttpError(409,'成片技术规格不合格');const outputs=[];for(const [suffix,mime,info] of [['file','video/mp4',meta],['cover','image/jpeg',cover]] as const){const f=await fetch(c.url+'/jobs/'+r.data.remote_id+'/'+suffix+'?project_id='+encodeURIComponent(project),{headers:{Authorization:'Bearer '+c.token},redirect:'manual',signal:AbortSignal.timeout(60000)}),bytes=await boundedBytes(f,suffix==='file'?32*1024*1024:8*1024*1024);if(await sha256(bytes)!==info.sha256)throw new HttpError(409,'成片或封面哈希不一致');if(suffix==='file'&&(bytes.length<12||new TextDecoder().decode(bytes.slice(4,8))!=='ftyp'))throw new HttpError(409,'成片不是MP4');const key='_private/video-render-output/'+id+'/'+info.filename;await bucket().put(key,bytes,{httpMetadata:{contentType:mime}});outputs.push({...info,storage_key:key,mime})}return patch(r,{...r.data,status:'archived',outputs,archived_at:now(),review_status:'pending'})
}
export async function reviewVideoRender(project:string,id:string,revision:number,hash:string,decision:'approved'|'rejected'){const r=await record(id,project);if(r.type!=='video_render'||r.revision!==revision||r.data.status!=='archived'||r.data.outputs?.[0]?.sha256!==hash)throw new HttpError(409,'成片状态或版本已经改变');await videoPreparation(project,r.data.script_id);const s=await approvedVideoScript(project,r.data.script_id),p=await record('video-plan-'+r.data.script_id,project);if(s.hash!==r.data.script_hash||p.revision!==r.data.plan_revision)throw new HttpError(409,'脚本或镜头方案改变，请合成并核对新版本');return patch(r,{...r.data,review_status:decision,reviews:[...(r.data.reviews||[]),{hash,decision,at:now()}]})}
export async function renderOutput(project:string,id:string,kind:string){const r=await record(id,project);if(r.type!=='video_render'||r.data.status!=='archived')throw new HttpError(404,'成片尚未归档');const info=r.data.outputs.find((x:any)=>kind==='cover'?x.mime==='image/jpeg':x.mime==='video/mp4'),o=info&&await bucket().get(info.storage_key);if(!o)throw new HttpError(404,'归档文件不存在');const bytes=await o.arrayBuffer();if(await sha256(bytes)!==info.sha256)throw new HttpError(409,'归档文件校验失败');return new Response(bytes,{headers:{'Content-Type':info.mime,'Content-Disposition':'inline; filename="'+info.filename+'"','Cache-Control':'no-store'}})}
export async function renderTick(){const q=await database().prepare("SELECT id,project_id FROM records WHERE type='video_render' AND json_extract(data,'$.status') IN ('submitting','unknown','queued','rendering','download_pending') ORDER BY updated_at LIMIT 1").first<any>();return q?queryVideoRender(q.project_id,q.id):null}
