import {z} from 'zod';
import {database,record,bucket,HttpError,now,projectExists} from './server';
import {sharedIP} from './execution-server';
import {sha256} from './production-content';
import {stableJson} from './production-batch';
import {loadProductionArtifact} from './production-server';
export const brandProfileSchema=z.object({project_id:z.string().min(1),revision:z.number().int().nonnegative(),name:z.string().trim().min(1).max(150),ip_asset_id:z.string().min(1),logo_asset_id:z.string().max(200),colors:z.array(z.string().regex(/^#[0-9a-fA-F]{6}$/)).min(1).max(8),font:z.string().min(1).max(150),reference_asset_ids:z.array(z.string()).max(5),prohibitions:z.string().trim().min(1).max(3000),notes:z.string().max(2000),consent:z.literal(true)}).strict();
export async function readBrandProfile(project:string){await projectExists(project);return record('brand-profile-'+project,project).catch(()=>null)}
export async function brandSnapshot(project:string){const p=await readBrandProfile(project);if(!p)return undefined;for(const snap of p.data.assets){const a=await sharedIP(snap.id),o=await bucket().get(a.data.storage_key);if(!o||a.revision!==snap.revision||await sha256(await o.arrayBuffer())!==snap.sha256)throw new HttpError(409,'品牌资产版本已改变，请重新确认品牌档案')}return {id:p.id,revision:p.revision,sha256:await sha256(stableJson(p.data)),data:p.data}}
export async function saveBrandProfile(raw:unknown){const r=brandProfileSchema.parse(raw),old=await readBrandProfile(r.project_id);if((old?.revision||0)!==r.revision)throw new HttpError(409,'品牌档案已改变，请刷新');const assets=[];for(const id of [...new Set([r.ip_asset_id,r.logo_asset_id,...r.reference_asset_ids].filter(Boolean))]){const a=await sharedIP(id),o=await bucket().get(a.data.storage_key);if(!o)throw new HttpError(404,'品牌资产文件不存在');assets.push({id,revision:a.revision,sha256:await sha256(await o.arrayBuffer())})}const t=now(),id='brand-profile-'+r.project_id,data={...r,assets,confirmed_at:t,history:[...(old?.data.history||[]),...(old?[{revision:old.revision,sha256:await sha256(stableJson(old.data)),name:old.data.name,at:old.updated_at}]:[])].slice(-30)},q=old?database().prepare('UPDATE records SET data=?,revision=revision+1,updated_at=? WHERE id=? AND project_id=? AND revision=?').bind(JSON.stringify(data),t,id,r.project_id,r.revision):database().prepare("INSERT OR IGNORE INTO records VALUES (?,?,'brand_profile',?,1,?,?)").bind(id,r.project_id,JSON.stringify(data),t,t);if(!(await q.run()).meta.changes)throw new HttpError(409,'保存冲突，请刷新');return {id,revision:r.revision+1,data}}
export async function listApprovedMemory(project:string){await projectExists(project);const r=await database().prepare("SELECT id,revision,data,created_at FROM records WHERE project_id=? AND type='approved_memory' ORDER BY created_at DESC LIMIT 100").bind(project).all<any>();return r.results.map(x=>({...x,data:JSON.parse(x.data)}))}
export async function saveApprovedMemory(raw:unknown){const r=z.object({project_id:z.string().min(1),batch_id:z.string().min(1),slot:z.string().regex(/^(poster-[1-4]|copy-(weibo|xiaohongshu|douyin|moments))$/),artifact_hash:z.string().regex(/^[a-f0-9]{64}$/),channel:z.string().min(1).max(100),style:z.string().min(1).max(300),activity_type:z.string().min(1).max(100),consent:z.literal(true)}).strict().parse(raw),l=await loadProductionArtifact(r.project_id,r.batch_id,r.slot);if(l.job.review!=='approved'||l.job.artifact?.sha256!==r.artifact_hash)throw new HttpError(409,'只可收录当前人工批准的作品');const profile=await brandSnapshot(r.project_id),text=l.artifact.copy?.text||[l.artifact.layout?.headline,...(l.artifact.layout?.details||[])].join('\n'),id='approved-memory-'+await sha256(stableJson(r)),t=now(),data={...r,text:text.slice(0,6000),artifact:l.artifact,approval:l.job.reviews||[],brand_profile_sha256:profile?.sha256||null,brand_asset_id:l.batch.data.input.brand.id,status:'approved',added_at:t};await database().prepare("INSERT OR IGNORE INTO records VALUES (?,?,'approved_memory',?,1,?,?)").bind(id,r.project_id,JSON.stringify(data),t,t).run();return record(id,r.project_id)}
export async function memorySnapshot(project:string,brandId:string,profileHash?:string,selectedIds?:string[]){const all=await listApprovedMemory(project);if(selectedIds&&selectedIds.some(id=>!all.some(r=>r.id===id&&r.data.status==='approved'&&r.data.brand_asset_id===brandId&&r.data.brand_profile_sha256===(profileHash||null))))throw new HttpError(409,'选择的作品记忆已撤回或品牌版本不同，请重新确认');return all.filter(r=>(!selectedIds||selectedIds.includes(r.id))&&r.data.status==='approved'&&r.data.brand_asset_id===brandId&&r.data.brand_profile_sha256===(profileHash||null)).slice(0,3).map(r=>({id:r.id,revision:r.revision,sha256:'',channel:r.data.channel,style:r.data.style,activity_type:r.data.activity_type,text:r.data.text})).reduce(async(p,r)=>[...await p,{...r,sha256:await sha256(stableJson(r))}],Promise.resolve<any[]>([]))}
export async function revokeApprovedMemory(project:string,id:string,revision:number,reason:string){if(reason.trim().length<5)throw new HttpError(400,'请填写撤回原因');const r=await record(id,project);if(r.type!=='approved_memory')throw new HttpError(404,'作品记忆不存在');const q=await database().prepare("UPDATE records SET data=json_set(data,'$.status','revoked','$.revoke_reason',?,'$.revoked_at',?),revision=revision+1,updated_at=? WHERE id=? AND project_id=? AND revision=?").bind(reason,now(),now(),id,project,revision).run();if(!q.meta.changes)throw new HttpError(409,'记忆已改变，请刷新');return record(id,project)}
