import {isEarlyConcept} from './closeout-baseline';
import {sourceSchema} from './v2-contract';
export function buildProjectSnapshot(project:any,rows:any[],includeCloseout:boolean,upstream:any[]=[]){
 const typed=(type:string)=>rows.filter(r=>r.type===type).map(r=>({...r,data:typeof r.data==='string'?JSON.parse(r.data):r.data}));
 // Snapshot only business fields; never include provider settings, private keys or raw asset files.
 const tasks=typed('task').filter(r=>!isEarlyConcept(r)).map(r=>({id:r.id,revision:r.revision,title:r.data.title,lane:r.data.lane,phase:r.data.phase,status:r.data.status,owner:r.data.owner,due:r.data.due,source:r.data.source,channel:r.data.channel,owner_id:r.data.owner_id,deliverable_ids:r.data.deliverable_ids}));
 const budgets=typed('budget').map(r=>({id:r.id,revision:r.revision,title:r.data.title,quantity:r.data.quantity,unit:r.data.unit,unit_price:r.data.unit_price,shipping:r.data.shipping,actual_amount:r.data.actual_amount,status:r.data.status,source:r.data.source}));
 const sources=[sourceSchema.parse({id:'project:'+project.id,version:String(project.revision),date:project.updated_at||null,type:'project',confidence:'documented'})];
 if(includeCloseout)sources.unshift(sourceSchema.parse({id:'woo-final-closeout',version:'public-demo-v1',date:null,type:'closeout',confidence:'documented',page:'P1–4'}));
 for(const r of upstream)sources.push(sourceSchema.parse({id:r.run_id,version:r.workflow_run_id||r.run_id,date:r.reviewed_at||null,type:'project',confidence:'approved'}));
 return {schema_version:'2.1',project_id:project.id,project_revision:project.revision,source_set:sources,activity:typed('activity_settings').map(r=>({id:r.id,revision:r.revision,...r.data,previous:undefined})),tasks,budgets,procurement:typed('procurement').map(r=>({id:r.id,revision:r.revision,...r.data,price_status:'仅为本次预算参考；空单价为待询价，不是实际支出'})),execution:typed('execution_plan').map(r=>({id:r.id,revision:r.revision,...r.data,online:undefined,offline:undefined,_operation:undefined})),assets:typed('asset').map(r=>({id:r.id,revision:r.revision,title:r.data.title,mime:r.data.mime,review_status:r.data.review_status||'unverified',source_run_id:r.data.source_run_id||null})),contents:typed('content').map(r=>({id:r.id,revision:r.revision,title:r.data.title,task_id:r.data.task_id,status:r.data.status,source:r.data.source})),runs:typed('run').map(r=>({id:r.id,revision:r.revision,key:r.data.key,status:r.data.status,review_status:r.data.review_status,workflow_run_id:r.data.workflow_run_id||null,review_history:r.data.review_history||[]})),approved_upstream_ids:upstream.map(r=>r.run_id),rules:['结案优先；原始记录只证明记录内容，不代表统计已审计','预算、实际支出、收入分别保留；未知实付保持 null','任务完成由用户或归档资料确定，模型不得改写','资料附件不会自动读取，未选摘录不得作为已检索证据']};
}
