import {database,now,HttpError} from './server';
import {emptyExecution,executionSchema} from './project-execution';
import {isEarlyConcept} from './closeout-baseline';
export const taskStage=(s:string)=>s==='done'?'completed':s==='ready'?'reviewed':s==='review'?'awaiting_review':s==='doing'?'draft':'planned';
export const taskStatus=(s:string)=>s==='completed'?'done':s==='reviewed'?'ready':s==='awaiting_review'?'review':s==='draft'?'doing':'todo';
export async function ensureUnifiedTasks(project:string){const db=database(),marker='tasks-unified-'+project;if(await db.prepare('SELECT id FROM records WHERE id=?').bind(marker).first())return;const r=await db.prepare("SELECT data FROM records WHERE project_id=? AND type='execution_plan'").bind(project).first<any>();const plan=r?executionSchema.parse(JSON.parse(r.data)):emptyExecution,t=now();const statements:any[]=[];for(const lane of ['online','offline'] as const)for(const task of plan[lane]){const data={...task,lane,phase:'预热',status:taskStatus(task.stage||(task.done?'completed':'planned')),owner:plan.assignments.find(a=>a.member_id===task.owner_id)?.name||'',due:task.due||'',notes:'',source:'项目宣发安排（原记录保留）'};statements.push(db.prepare("INSERT OR IGNORE INTO records (id,project_id,type,data,revision,created_at,updated_at) SELECT ?,?,'task',?,1,?,? WHERE NOT EXISTS (SELECT id FROM records WHERE id=?)").bind(task.id,project,JSON.stringify(data),t,t,marker))}statements.push(db.prepare("INSERT OR IGNORE INTO records VALUES (?,?,'system','{}',1,?,?)").bind(marker,project,t,t));await db.batch(statements)}
export async function unifiedTaskRows(project:string){await ensureUnifiedTasks(project);const {results}=await database().prepare("SELECT * FROM records WHERE project_id=? AND type='task' ORDER BY created_at,id").bind(project).all<any>();return results.map(r=>({...r,data:JSON.parse(r.data)})).filter(r=>!r.data.archived&&!isEarlyConcept(r))}
export async function readUnifiedExecution(project:string){const rows=await unifiedTaskRows(project),r=await database().prepare("SELECT * FROM records WHERE id=? AND project_id=? AND type='execution_plan'").bind('execution-'+project,project).first<any>();const plan=r?executionSchema.parse(JSON.parse(r.data)):structuredClone(emptyExecution);for(const lane of ['online','offline'] as const)plan[lane]=rows.filter(r=>r.data.lane===lane).map(r=>({id:r.id,title:r.data.title,done:r.data.status==='done',stage:taskStage(r.data.status) as any,owner_id:r.data.owner_id,due:r.data.due||'',channel:r.data.channel||'',deliverable_ids:r.data.deliverable_ids||[]}));return {revision:r?.revision||0,data:plan}}
export function bumpExecutionStatement(project:string,t:string){return database().prepare("INSERT INTO records (id,project_id,type,data,revision,created_at,updated_at) VALUES (?,?,'execution_plan',?,1,?,?) ON CONFLICT(id) DO UPDATE SET revision=records.revision+1,updated_at=excluded.updated_at").bind('execution-'+project,project,JSON.stringify(emptyExecution),t,t)}
