import {taskTransition} from '@/lib/task-transition';
import {ensureUnifiedTasks,bumpExecutionStatement} from '@/lib/unified-tasks';
import {z} from 'zod';
const identity=z.object({id:z.string().min(1),project_id:z.string().min(1),revision:z.number().int().positive()});
import {database,bucket,record,projectExists,schemas,checkOrigin,failure,now,HttpError,linkedTask} from '@/lib/server';
export async function POST(req:Request){try{checkOrigin(req);const b=z.object({type:z.enum(['task','content','budget','agent']),project_id:z.string().min(1),data:z.unknown()}).parse(await req.json());if(!['task','content','budget','agent'].includes(b.type))throw new HttpError(400,'记录类型不正确');const d=schemas[b.type as keyof typeof schemas].parse(b.data);await projectExists(String(b.project_id));if(b.type==='task')await ensureUnifiedTasks(b.project_id);if(b.type==='content')await linkedTask(d,b.project_id);if(b.type==='agent'){const {results}=await database().prepare("SELECT data FROM records WHERE project_id=? AND type='agent'").bind(b.project_id).all<any>();if(results.some(r=>JSON.parse(r.data).key===(d as any).key))throw new HttpError(409,'已有接入说明，请刷新后编辑。')}
 const id=crypto.randomUUID(),t=now();const insert=database().prepare('INSERT INTO records (id,project_id,type,data,revision,created_at,updated_at) VALUES (?,?,?,?,1,?,?)').bind(id,b.project_id,b.type,JSON.stringify(d),t,t);if(b.type==='task')await database().batch([insert,bumpExecutionStatement(b.project_id,t)]);else await insert.run();return Response.json({id},{status:201})}catch(e){return failure(e)}}
export async function PATCH(req:Request){try{checkOrigin(req);const b=identity.extend({data:z.unknown()}).parse(await req.json());const old=await record(String(b.id),String(b.project_id));const type=old.type as keyof typeof schemas;const parsed=schemas[type].parse(b.data);if(type==='content')await linkedTask(parsed,old.project_id);if(type==='task')await ensureUnifiedTasks(old.project_id);let data=type==='asset'?{...old.data,...parsed}:parsed;if(type==='task')data=taskTransition(old.data,parsed,now());
 const t=now(),stmt=database().prepare('UPDATE records SET data=?,revision=revision+1,updated_at=? WHERE id=? AND project_id=? AND revision=?').bind(JSON.stringify(data),t,old.id,old.project_id,Number(b.revision));const r=type==='task'?(await database().batch([stmt,database().prepare("INSERT INTO records (id,project_id,type,data,revision,created_at,updated_at) SELECT ?,?,'execution_plan',?,1,?,? WHERE EXISTS (SELECT id FROM records WHERE id=? AND revision=? AND updated_at=?) ON CONFLICT(id) DO UPDATE SET revision=records.revision+1,updated_at=excluded.updated_at").bind('execution-'+old.project_id,old.project_id,JSON.stringify({assignments:[],material_ready_ids:[],online:[],offline:[]}),t,t,old.id,b.revision+1,t)]))[0]:await stmt.run();if(!r.meta.changes)throw new HttpError(409,'记录已在其他窗口更新，请关闭编辑框并刷新后重试。');return Response.json({ok:true})}catch(e){return failure(e)}}
export async function DELETE(req:Request){try{checkOrigin(req);const b=identity.parse(await req.json());const old=await record(String(b.id),String(b.project_id));if(['a-original','a-closeout'].includes(old.id))throw new HttpError(400,'原始参考文件保留在项目中，不能删除。');if(old.type==='task'){const {results}=await database().prepare("SELECT data FROM records WHERE project_id=? AND type='content'").bind(old.project_id).all<any>();if(results.some(r=>JSON.parse(r.data).task_id===old.id))throw new HttpError(409,'此任务仍有关联内容，请先在内容卡片中取消关联。')}
 if(old.type==='task'){await ensureUnifiedTasks(old.project_id);const t=now(),r=await database().prepare("UPDATE records SET data=json_set(data,'$.archived',json('true')),revision=revision+1,updated_at=? WHERE id=? AND project_id=? AND revision=?").bind(t,old.id,old.project_id,b.revision).run();if(!r.meta.changes)throw new HttpError(409,'任务已更新，请刷新');await bumpExecutionStatement(old.project_id,t).run();return Response.json({ok:true})}
 const r=await database().prepare('DELETE FROM records WHERE id=? AND project_id=? AND revision=?').bind(old.id,old.project_id,Number(b.revision)).run();if(!r.meta.changes)throw new HttpError(409,'记录已更新，请刷新后重试。');if(old.type==='asset'&&old.data.storage_key){try{await bucket().delete(old.data.storage_key)}catch(e){console.error('orphaned asset cleanup',old.id,e)}}return Response.json({ok:true})}catch(e){return failure(e)}}
