import {build} from 'esbuild';
import {DatabaseSync} from 'node:sqlite';
import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE records(id TEXT PRIMARY KEY,project_id TEXT,type TEXT,data TEXT,revision INTEGER,created_at TEXT,updated_at TEXT);');
const wrap=(sql,args=[])=>({bind(...v){return wrap(sql,v)},async first(){return db.prepare(sql).get(...args)||null},async run(){return {meta:{changes:Number(db.prepare(sql).run(...args).changes)}}}});
const files=new Map();globalThis.layoutTestEnv={DB:{prepare:sql=>wrap(sql)},BUCKET:{async put(k,v){files.set(k,v)},async delete(k){files.delete(k)}}};
const plugin={name:'test',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export const env=globalThis.layoutTestEnv;',loader:'js'}))}};
await mkdir('.sites-runtime/tests',{recursive:true});
for(const [name,entry] of Object.entries({layout:'lib/layout-preview.ts',archive:'app/api/agents/layout/route.ts',review:'app/api/files/[id]/review/route.ts'}))await build({entryPoints:[entry],bundle:true,platform:'node',format:'esm',outfile:`.sites-runtime/tests/layout-${name}.mjs`,plugins:[plugin],packages:'external'});
const layout=await import('../.sites-runtime/tests/layout-layout.mjs'),archive=await import('../.sites-runtime/tests/layout-archive.mjs'),review=await import('../.sites-runtime/tests/layout-review.mjs');
const result=JSON.parse(await readFile('dify/content-v21/graphic-live-case1.json','utf8'));
const add=(id,status,output=result)=>db.prepare('INSERT INTO records VALUES (?,?,?,?,1,?,?)').run(id,'test','run',JSON.stringify({review_status:status,v2_output:output}),'','');
add('pending','awaiting_review');add('approved','approved');add('mock','approved',{...result,execution_mode:'mock'});
const req=(body,origin='https://test.site')=>new Request('https://test.site/api/agents/layout',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
assert.equal((await archive.POST(req({project_id:'test',run_id:'pending',page:1}))).status,409);assert.equal(files.size,0);
assert.equal((await archive.POST(req({project_id:'other',run_id:'approved',page:1}))).status,404);
assert.equal((await archive.POST(req({project_id:'test',run_id:'mock',page:1}))).status,409);
assert.equal((await archive.POST(req({project_id:'test',run_id:'approved',page:100}))).status,400);
const accepted=await archive.POST(req({project_id:'test',run_id:'approved',page:1}));assert.equal(accepted.status,201);const {id}=await accepted.json();
assert.equal(JSON.parse(db.prepare('SELECT data FROM records WHERE id=?').get(id).data).review_status,'awaiting_review');
assert.equal((await archive.POST(req({project_id:'test',run_id:'approved',page:1}))).status,200);assert.equal(files.size,1);
const reviewParams={params:Promise.resolve({id})},body={project_id:'test',revision:1,decision:'approved',note:'测试环境人工审核夹具'};
assert.equal((await review.POST(req({...body,project_id:'other'}),reviewParams)).status,404);
assert.equal((await review.POST(req({...body,revision:2}),reviewParams)).status,409);
assert.equal((await review.POST(req({...body,note:'短'}),reviewParams)).status,400);
assert.equal((await review.POST(req(body,'https://other.site'),reviewParams)).status,403);
assert.equal((await review.POST(req(body),reviewParams)).status,200);
const updated=db.prepare('SELECT data,revision FROM records WHERE id=?').get(id),data=JSON.parse(updated.data);assert.equal(updated.revision,2);assert.equal(data.review_history.length,1);assert.equal(data.review_history[0].source_revision,1);
assert.equal((await review.POST(req(body),reviewParams)).status,409);
const hostile=layout.layoutSvg({page:1,headline:'<script>alert(1)</script>',body:'A'.repeat(10000),caption:'" onload="alert(2)',imageRef:'javascript:alert(3)'});
assert.ok(!hostile.includes('<script>'));assert.ok(!hostile.includes('javascript:'));assert.ok(!hostile.includes(' onload="'));assert.ok(hostile.includes('&lt;script&gt;'));assert.equal((hostile.match(/A/g)||[]).length,10000);
await writeFile('.sites-runtime/tests/graphic-preview.svg',layout.layoutSvg(layout.layoutPages(result)[0]));
console.log('PASS: layout approval gate, project isolation, idempotent archival, review revision/audit, escaped exact text and complete long copy');
