import {build} from 'esbuild';import {DatabaseSync} from 'node:sqlite';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE projects(id TEXT PRIMARY KEY,name TEXT,brand TEXT,school TEXT,goal TEXT,brief TEXT,source_note TEXT,revision INTEGER,updated_at TEXT);CREATE TABLE records(id TEXT PRIMARY KEY,project_id TEXT,type TEXT,data TEXT,revision INTEGER,created_at TEXT,updated_at TEXT)');db.prepare('INSERT INTO projects VALUES (?,?,?,?,?,?,?,?,?)').run('test','海报测试项目','Woo虎','示例大学','节庆海报','新创作；时间地点以表单为准','用户确认的创作简报',1,'2026-10-05');
const wrap=(sql,args=[])=>({bind(...v){return wrap(sql,v)},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){return {meta:{changes:Number(db.prepare(sql).run(...args).changes)}}}});const objects=new Map();globalThis.posterEnv={DB:{prepare:s=>wrap(s)},BUCKET:{async put(k,v){objects.set(k,v)},async get(k){const v=objects.get(k);return v?{json:async()=>JSON.parse(typeof v==='string'?v:new TextDecoder().decode(v)),arrayBuffer:async()=>v.buffer,body:v}:null}},DIFY_WORKFLOW_API_KEY:'test-secret'};
const plugin={name:'test-env',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export const env=globalThis.posterEnv;',loader:'js'}))}};await mkdir('.sites-runtime/tests',{recursive:true});for(const [name,entry] of Object.entries({start:'app/api/posters/route.ts',slot:'app/api/posters/[id]/route.ts',export:'app/api/posters/export/route.ts',contract:'lib/poster-contract.ts',canvas:'lib/poster-canvas.ts'}))await build({entryPoints:[entry],bundle:true,platform:'node',format:'esm',packages:'external',plugins:[plugin],outfile:'.sites-runtime/tests/poster-'+name+'.mjs'});
const start=await import('../.sites-runtime/tests/poster-start.mjs'),slot=await import('../.sites-runtime/tests/poster-slot.mjs'),exp=await import('../.sites-runtime/tests/poster-export.mjs'),contract=await import('../.sites-runtime/tests/poster-contract.mjs'),canvas=await import('../.sites-runtime/tests/poster-canvas.mjs');const req=(b)=>new Request('https://test.site/api/posters',{method:'POST',headers:{Origin:'https://test.site','Content-Type':'application/json'},body:JSON.stringify(b)});const b={project_id:'test',project_revision:1,request_id:crypto.randomUUID(),festival:'劳动节',prompt:'校园活力与劳动的快乐',headline:'五一，快乐动起来',time:'5月1日 14:00',place:'西校园6B小广场',contact:'咨询活动负责人',mandatory:'Woo虎！接住这一棒\n毕业接力，能量不停',style:'brand',ratio:'3:4',asset_id:'',consent:true};let planning=0,images=0,mode='ok';let professional;
globalThis.fetch=async(url,options)=>{if(url==='https://api.dify.ai/v1/workflows/run'){const q=JSON.parse(options.body);if(q.inputs.requirements.startsWith('能力类型：poster')){planning++;professional=JSON.parse(q.inputs.brief);const x=professional;return Response.json({workflow_run_id:'planner-test',data:{status:'succeeded',outputs:{content_result:[{result:{schema_version:'2.1',run_id:x.run_id,agent_key:'poster',agent_version:x.agent_version,execution_mode:'live',review_status:'awaiting_review',title:'劳动节海报设计',readable_text:'主视觉保留上下留白，正文精确叠加。',structured_output:{poster_spec:{size:'3:4',safe_area:'64px',grid:'四种构图',copy:b.headline,visual_direction:'校园活力',prompt:'校园运动场上的活力场景，主体居中，纯画面无文字'},image_asset_ids:[],qc_report:[],print_checklist:[],revision_notes:[]},evidence:[{source_id:'project:test',quote:'海报测试项目'}],assumptions:[],conflicts:[],next_action:'检查四张草稿',source_set:x.source_set,validation_errors:[]}}]}}})}images++;if(mode==='timeout')throw Error('unconfirmed');const r=JSON.parse(q.inputs.brief);assert.ok(/^poster-/.test(r.approved_run_id));assert.ok(r.prompt.includes('禁止生成任何文字'));return Response.json({workflow_run_id:'image-test-'+images,data:{status:'succeeded',outputs:{image_result:[{model:'doubao-seedream-5-0-pro-260628',data:[{url:'https://test.tos-cn-beijing.volces.com/test.png'}]}]}}})}return new Response(Uint8Array.from([137,80,78,71,13,10,26,10]));};
assert.equal((await start.POST(req({...b,consent:false}))).status,400);assert.equal(planning,0);assert.equal((await start.POST(req({...b,project_revision:2}))).status,409);let r=await start.POST(req(b));assert.equal(r.status,201);const batch=await r.json();assert.equal(batch.status,'ready');assert.equal(batch.plan.result.status,'awaiting_review');assert.equal(JSON.parse(db.prepare('SELECT data FROM records WHERE id=?').get(batch.id).data).review_status,'awaiting_review');assert.equal((await start.POST(req(b))).status,200);assert.equal(planning,1);assert.equal((await start.POST(req({...b,headline:'不同要求'}))).status,409);assert.equal(JSON.parse(db.prepare('SELECT data FROM records WHERE id=?').get(batch.id).data).status,'ready');
for(let n=0;n<4;n++){const body={project_id:'test',slot:n};r=await slot.POST(req(body),{params:Promise.resolve({id:batch.id})});assert.equal(r.status,201);const result=await r.json();assert.equal(result.status,'succeeded');assert.ok(result.asset_id);assert.equal(JSON.parse(db.prepare('SELECT data FROM records WHERE id=?').get(result.asset_id).data).review_status,'awaiting_review');await slot.POST(req(body),{params:Promise.resolve({id:batch.id})});assert.equal(images,n+1)}
assert.equal((await slot.POST(req({project_id:'other',slot:0}),{params:Promise.resolve({id:batch.id})})).status,404);assert.equal((await slot.POST(req({project_id:'test',slot:4}),{params:Promise.resolve({id:batch.id})})).status,400);const all=await (await slot.GET(new Request('https://test.site/api/posters/'+batch.id+'?project_id=test'),{params:Promise.resolve({id:batch.id})})).json();assert.equal(all.slots.length,4);assert.ok(all.slots.every(x=>x.asset_id));
const width={measureText:s=>({width:Array.from(s).length*10})};const original='必须保留ABC！🙂完整中文\n第二行';assert.equal(canvas.wrapText(width,original,40).join(''),original.replaceAll('\n',''));assert.equal(contract.posterInput.safeParse({...b,style:'unknown'}).success,false);
const png=Buffer.alloc(32);png.set([137,80,78,71,13,10,26,10]);png.writeUInt32BE(1080,16);png.writeUInt32BE(1440,20);const exportBody={project_id:'test',batch_id:batch.id,slot:0,brief:b,png:'data:image/png;base64,'+png.toString('base64')};const archived=await exp.POST(req(exportBody));assert.equal(archived.status,201);const archiveId=(await archived.json()).id;const asset=JSON.parse(db.prepare('SELECT data FROM records WHERE id=?').get(archiveId).data);assert.equal(asset.review_status,'awaiting_review');assert.equal(asset.copy.mandatory,b.mandatory);assert.equal((await exp.POST(req({...exportBody,project_id:'other'}))).status,404);assert.equal((await exp.POST(req({...exportBody,png:'data:image/png;base64,AAAA'}))).status,400);
await writeFile('/workspace/scratch/poster-ui-request.json',JSON.stringify(professional));
const uncertainBody={...b,request_id:crypto.randomUUID()};const uncertainBatch=await (await start.POST(req(uncertainBody))).json();mode='timeout';const beforeUnknown=images;assert.equal((await slot.POST(req({project_id:'test',slot:0}),{params:Promise.resolve({id:uncertainBatch.id})})).status,504);assert.equal((await slot.POST(req({project_id:'test',slot:0}),{params:Promise.resolve({id:uncertainBatch.id})})).status,200);assert.equal(images,beforeUnknown+1);assert.equal(JSON.parse(db.prepare('SELECT data FROM records WHERE id=?').get(uncertainBatch.id+'-0').data).status,'unknown');
assert.ok(contract.posterInstruction({...b,asset_id:'a'.repeat(200),festival:'节'.repeat(60),headline:'题'.repeat(60),prompt:'创'.repeat(1500),time:'时'.repeat(100),place:'地'.repeat(100),contact:'联'.repeat(100),mandatory:'字'.repeat(500)}).length<=3000);
console.log('PASS: planning + four slots, replay without regeneration, cross-project rejection, consent/revision/style checks, generated assets awaiting review, exact text wrap');
// Renderer contract: required Chinese text survives all supported export ratios.
const previousImage=globalThis.Image,previousDocument=globalThis.document;
globalThis.Image=class{width=1080;height=1440;async decode(){}};globalThis.document={fonts:{ready:Promise.resolve()}};
for(const ratio of ['3:4','9:16','1:1','16:9']){const drawn=[];const ctx={font:'',fillStyle:'',measureText(s){return {width:Array.from(s).length*(parseInt(this.font.match(/(\d+)px/)?.[1]||'30')*.65)}},drawImage(){},fillRect(){},fillText(s){drawn.push(s)}};const out={width:0,height:0,getContext:()=>ctx};await canvas.paintPoster(out,'https://fixture/image.png',{...b,ratio},0);assert.equal(drawn.join(''),b.headline+b.mandatory.replaceAll('\n','')+'时间：'+b.time+'地点：'+b.place+'联系：'+b.contact+'AI创作草稿 · 待审核');assert.ok(out.width>0&&out.height>0)}
globalThis.Image=previousImage;globalThis.document=previousDocument;
console.log('PASS: renderer keeps all required text at four aspect ratios; simulated canvas, not browser visual QA');
