import {build} from 'esbuild';
import {DatabaseSync} from 'node:sqlite';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE projects(id TEXT PRIMARY KEY,revision INTEGER); CREATE TABLE records(id TEXT PRIMARY KEY,project_id TEXT,type TEXT,data TEXT,revision INTEGER,created_at TEXT,updated_at TEXT);');db.prepare('INSERT INTO projects VALUES (?,?)').run('test',1);db.prepare('INSERT INTO projects VALUES (?,?)').run('other',1);
const wrap=(sql,args=[])=>({bind(...v){return wrap(sql,v)},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){const r=db.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}}}});
const objects=new Map();let failPut=false;globalThis.mediaTestEnv={DB:{prepare:sql=>wrap(sql)},BUCKET:{async get(k){const value=objects.get(k);return value?{json:async()=>JSON.parse(typeof value==='string'?value:new TextDecoder().decode(value)),arrayBuffer:async()=>value.buffer,body:value}:null},async put(k,v){if(failPut)throw Error('mock storage unavailable');objects.set(k,v)}}};
globalThis.mediaTestEnv.DIFY_WORKFLOW_API_KEY='test-dify-secret';
const plugin={name:'test',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export const env=globalThis.mediaTestEnv;',loader:'js'}))}};
await mkdir('.sites-runtime/tests',{recursive:true});for(const [name,entry] of Object.entries({config:'app/api/media/config/route.ts',generate:'app/api/media/generate/route.ts',poll:'app/api/media/[id]/route.ts',ark:'lib/ark.ts',ppt:'lib/ppt-export.ts'}))await build({entryPoints:[entry],bundle:true,platform:'node',format:'esm',outfile:`.sites-runtime/tests/media-${name}.mjs`,plugins:[plugin],packages:'external'});
const config=await import('../.sites-runtime/tests/media-config.mjs'),generate=await import('../.sites-runtime/tests/media-generate.mjs'),poll=await import('../.sites-runtime/tests/media-poll.mjs'),ark=await import('../.sites-runtime/tests/media-ark.mjs');
const req=(body,origin='https://test.site')=>new Request('https://test.site/api/media/generate',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
for(const [id,key] of [['reviewed-design','poster'],['reviewed-script','script'],['unreviewed-design','poster']])db.prepare('INSERT INTO records VALUES (?,?,?,?,?,?,?)').run(id,'test','run',JSON.stringify({key,review_status:id.startsWith('unreviewed')?'awaiting_review':'approved',result:{execution_mode:'live'}}),1,'','');
const body=kind=>({approved_run_id:kind==='image'?'reviewed-design':kind==='video'?'reviewed-script':'',project_id:'test',project_revision:1,request_id:crypto.randomUUID(),kind,prompt:'校园乐虎黄黑色海报设计',reference_id:'',ratio:'16:9',duration:5,consent:true});let calls=0,mode='ok';
globalThis.fetch=async(url,options)=>{calls++;if(url==='https://api.dify.ai/v1/workflows/run'){assert.equal(options.headers?.Authorization,'Bearer test-dify-secret');if(mode==='timeout')throw Error('timeout');const b=JSON.parse(options.body);if(b.inputs.requirements==='能力类型：media_video_submit'){const q=JSON.parse(b.inputs.brief);assert.equal(q.kind,'video');assert.equal(q.approved_run_id,'reviewed-script');return Response.json({workflow_run_id:'dify-submit-test',data:{status:'succeeded',outputs:{video_submit_result:[{id:'cgt-test-01'}]}}});}if(b.inputs.requirements==='能力类型：media_video_status'){const q=JSON.parse(b.inputs.brief);assert.equal(q.kind,'video_status');return Response.json({workflow_run_id:'dify-query-test',data:{status:'succeeded',outputs:{video_status_result:[{id:q.task_id,model:ark.defaults.video_model,status:'running'}]}}});}if(['能力类型：media_image','能力类型：media_reference_image'].includes(b.inputs.requirements)){const q=JSON.parse(b.inputs.brief);assert.equal(q.approved_run_id,'reviewed-design');return Response.json({workflow_run_id:'dify-image-test',data:{status:'succeeded',outputs:{[q.reference_image?'image_reference_result':'image_result']:[{model:ark.defaults.image_model,data:[{url:'https://foo.tos-cn-beijing.volces.com/image.png'}],usage:{generated_images:1}}]}}});}assert.equal(b.inputs.requirements,'能力类型：media_search');assert.equal(JSON.parse(b.inputs.brief).consent,true);return Response.json({workflow_run_id:'dify-search-test',data:{status:'succeeded',outputs:{media_result:[{id:'response-test',model:'doubao-seed-2-1-pro-260628',status:'completed',output:[{type:'message',content:[{type:'output_text',text:'官网公开人数待核对统计年份',annotations:[{type:'url_citation',title:'学校官网',url:'https://www.gxu.edu.cn/',publish_time:'2025-01-01'}]}]}]}]}}});}if(url==='https://foo.tos-cn-beijing.volces.com/image.png')return new Response(Uint8Array.from([137,80,78,71,13,10,26,10]),{headers:{'Content-Type':'image/png'}});assert.equal(options.headers?.Authorization,'Bearer test-ark-secret');if(mode==='timeout')throw Error('timeout');if(mode==='forbidden')return Response.json({error:'sensitive upstream details'},{status:403});if(url.endsWith('/responses')){const b=JSON.parse(options.body);assert.equal(b.tools[0].type,'web_search');return Response.json({id:'response-test',status:'completed',output:[{type:'message',content:[{type:'output_text',text:'官网公开人数待核对统计年份',annotations:[{type:'url_citation',title:'学校官网',url:'https://www.gxu.edu.cn/',publish_time:'2025-01-01'},{type:'url_citation',title:'非法链接',url:'javascript:alert(1)'}]}]}],usage:{tool_usage:{web_search:1}}})}if(url.endsWith('/images/generations')){const b=JSON.parse(options.body);assert.equal(b.response_format,'b64_json');return Response.json({data:[{b64_json:Buffer.from([137,80,78,71,13,10,26,10]).toString('base64')}],usage:{generated_images:1}})}if(options.method==='POST')return Response.json({id:'cgt-test-01'});return Response.json({status:'running'})};
delete globalThis.mediaTestEnv.DIFY_WORKFLOW_API_KEY;assert.equal((await generate.POST(req(body('image')))).status,503);assert.equal(calls,0);globalThis.mediaTestEnv.DIFY_WORKFLOW_API_KEY='test-dify-secret';
assert.equal((await config.POST(req({api_key:'test-ark-secret',image_model:ark.defaults.image_model,video_model:ark.defaults.video_model}))).status,503);
globalThis.mediaTestEnv.ARK_CREDENTIAL_ENCRYPTION_KEY=Buffer.alloc(32,11).toString('base64');let r=await config.POST(req({api_key:'test-ark-secret',image_model:ark.defaults.image_model,video_model:ark.defaults.video_model}));assert.equal(r.status,200);assert.equal(JSON.stringify(await r.json()).includes('test-ark-secret'),false);assert.equal(objects.get('_private/ark-config-v1').includes('test-ark-secret'),false);assert.equal((await ark.arkConfig()).key,'test-ark-secret');assert.equal((await config.POST(req({image_model:ark.defaults.image_model,video_model:ark.defaults.video_model}))).status,200);
const image=body('image');r=await generate.POST(req(image));assert.equal(r.status,201);const img=await r.json();assert.equal(img.status,'succeeded');assert.ok(img.asset_id);const count=calls;assert.equal((await generate.POST(req(image))).status,200);assert.equal(calls,count);assert.equal((await generate.POST(req({...image,prompt:'不同的提示词不能重用标识'}))).status,409);assert.equal((await generate.POST(req(body('image'),'https://evil.test'))).status,403);assert.equal((await generate.POST(req({...body('image'),consent:false}))).status,400);assert.equal((await generate.POST(req({...body('image'),project_revision:2}))).status,409);assert.equal(calls,count);
const refImage={...body('image'),reference_id:img.asset_id};const refResponse=await generate.POST(req(refImage));assert.equal(refResponse.status,400);assert.equal(db.prepare('SELECT id FROM records WHERE id=?').get('media-'+refImage.request_id),undefined);
const research=body('search');r=await generate.POST(req(research));assert.equal(r.status,201);const researchData=await r.json();assert.equal(researchData.status,'awaiting_review');assert.equal(researchData.provider,'dify-ark');assert.equal(researchData.workflow_run_id,'dify-search-test');assert.equal(researchData.sources.length,1);assert.equal(researchData.sources[0].url,'https://www.gxu.edu.cn/');assert.equal(ark.researchResult({output:[{type:'message',content:[{type:'output_text',text:'没有来源',annotations:[]}]}]}).status,'needs_sources');const researchCalls=calls;assert.equal((await generate.POST(req(research))).status,200);assert.equal(calls,researchCalls);
// A partial or wrong-model Dify result cannot become an accepted research record.
const searchFetch=globalThis.fetch;
for(const resultPatch of [{status:'incomplete'},{status:'completed',model:'unexpected-model'}]){
 let rejectedSearchCalls=0;
 globalThis.fetch=async()=>{rejectedSearchCalls++;return Response.json({data:{status:'succeeded',outputs:{media_result:[{id:'bad-search',model:ark.defaults.search_model,output:[],...resultPatch}]}}})};
 const invalid=body('search');const rejectedSearch=await generate.POST(req(invalid));assert.equal(rejectedSearch.status,502);
 const invalidRecord=JSON.parse(db.prepare('SELECT data FROM records WHERE id=?').get('media-'+invalid.request_id).data);assert.equal(invalidRecord.status,'unknown');assert.equal(invalidRecord.body,undefined);
 await generate.POST(req(invalid));assert.equal(rejectedSearchCalls,1);
}
globalThis.fetch=searchFetch;
// Reviewed upstream must belong to this project and match the media role.
const approvalCalls=calls;
for(const patch of [{approved_run_id:''},{approved_run_id:'unreviewed-design'},{approved_run_id:'reviewed-script'}])assert.equal((await generate.POST(req({...body('image'),...patch}))).status,400);
assert.equal((await generate.POST(req({...body('image'),project_id:'other'}))).status,404);assert.equal(calls,approvalCalls);
// Saving a generated image can fail; replay never pays for a second image.
const beforeArchiveFetch=globalThis.fetch;let imageGenerations=0,imageDownloads=0,allowImageDownload=false;
globalThis.fetch=async(url,options)=>{if(url==='https://api.dify.ai/v1/workflows/run'){imageGenerations++;return beforeArchiveFetch(url,options);}imageDownloads++;return allowImageDownload?new Response(Uint8Array.from([137,80,78,71,13,10,26,10])):new Response('temporary',{status:503})};
const imageRetryRequest=body('image');const pendingImage=await (await generate.POST(req(imageRetryRequest))).json();assert.equal(pendingImage.status,'download_pending');assert.equal(JSON.stringify(pendingImage).includes('https://foo'),false);
await generate.POST(req(imageRetryRequest));assert.equal(imageGenerations,1);assert.equal(imageDownloads,1);
allowImageDownload=true;const archivedImage=await (await poll.POST(req({project_id:'test'}),{params:Promise.resolve({id:pendingImage.id})})).json();assert.equal(archivedImage.status,'succeeded');assert.ok(archivedImage.asset_id);await poll.POST(req({project_id:'test'}),{params:Promise.resolve({id:pendingImage.id})});assert.equal(imageGenerations,1);assert.equal(imageDownloads,2);
globalThis.fetch=beforeArchiveFetch;
const unreviewedReference={...body('video'),reference_id:img.asset_id};assert.equal((await generate.POST(req(unreviewedReference))).status,400);const referenceAsset=JSON.parse(db.prepare('SELECT data FROM records WHERE id=?').get(img.asset_id).data);assert.equal(referenceAsset.review_status,'awaiting_review');db.prepare('UPDATE records SET data=? WHERE id=?').run(JSON.stringify({...referenceAsset,review_status:'approved'}),img.asset_id);
// Only an approved reference may use the released Dify reference-image route.
const approvedReferenceFetch=globalThis.fetch;let referenceImageChecked=false;
globalThis.fetch=async(url,options)=>{if(url==='https://api.dify.ai/v1/workflows/run'){const wrapper=JSON.parse(options.body);assert.equal(wrapper.inputs.requirements,'能力类型：media_reference_image');const payload=JSON.parse(wrapper.inputs.brief);assert.ok(payload.reference_image.startsWith('data:image/png;base64,'));referenceImageChecked=true;}return approvedReferenceFetch(url,options);};
const approvedReferenceRequest={...body('image'),reference_id:img.asset_id};const approvedReferenceResponse=await generate.POST(req(approvedReferenceRequest));assert.equal(approvedReferenceResponse.status,201);assert.equal((await approvedReferenceResponse.json()).status,'succeeded');assert.equal(referenceImageChecked,true);globalThis.fetch=approvedReferenceFetch;
const referenceVideo={...body('video'),reference_id:img.asset_id,ratio:'9:16'};const normalFetch=globalThis.fetch;let checkedFirstFrame=false;globalThis.fetch=async(url,options)=>{assert.equal(url,'https://api.dify.ai/v1/workflows/run');const wrapper=JSON.parse(options.body);assert.equal(wrapper.inputs.requirements,'能力类型：media_video_submit');const payload=JSON.parse(wrapper.inputs.brief);assert.equal(payload.ratio,'9:16');assert.ok(payload.reference_image.startsWith('data:image/png;base64,'));checkedFirstFrame=true;return Response.json({data:{status:'succeeded',outputs:{video_submit_result:[{id:'cgt-first-frame-test'}]}}})};const framed=await generate.POST(req(referenceVideo));assert.equal(framed.status,201);assert.equal((await framed.json()).ratio,'adaptive');assert.equal(checkedFirstFrame,true);globalThis.fetch=normalFetch;
const video=body('video');r=await generate.POST(req(video));assert.equal(r.status,201);const vid=await r.json();assert.equal(vid.status,'queued');r=await poll.POST(req({project_id:'test'}),{params:Promise.resolve({id:vid.id})});assert.equal(r.status,200);assert.equal((await r.json()).status,'running');assert.equal((await poll.POST(req({project_id:'other'}),{params:Promise.resolve({id:vid.id})})).status,404);
// Video submission rejects malformed task identifiers; no direct Ark fallback.
const normalSubmitFetch=globalThis.fetch;let invalidSubmissions=0;
globalThis.fetch=async(url)=>{assert.equal(url,'https://api.dify.ai/v1/workflows/run');invalidSubmissions++;return Response.json({data:{status:'succeeded',outputs:{video_submit_result:[{id:'https://invalid.test'}]}}})};
const malformedVideo=body('video');assert.equal((await generate.POST(req(malformedVideo))).status,502);assert.equal(JSON.parse(db.prepare('SELECT data FROM records WHERE id=?').get('media-'+malformedVideo.request_id).data).status,'unknown');await generate.POST(req(malformedVideo));assert.equal(invalidSubmissions,1);globalThis.fetch=normalSubmitFetch;
// Query mismatch, timeout, cross-project and archive retry remain distinct from generation.
const originalQueryFetch=globalThis.fetch;
for(const patch of [{id:'cgt-wrong-task'},{model:'wrong-model'},{status:'unknown-state'}]){
 globalThis.fetch=async(url)=>{assert.equal(url,'https://api.dify.ai/v1/workflows/run');return Response.json({data:{status:'succeeded',outputs:{video_status_result:[{id:vid.task_id,model:ark.defaults.video_model,status:'succeeded',...patch}]}}})};
 const badPoll=await poll.POST(req({project_id:'test'}),{params:Promise.resolve({id:vid.id})});assert.equal(badPoll.status,502);
 assert.equal(JSON.parse(db.prepare('SELECT data FROM records WHERE id=?').get(vid.id).data).status,'running');
}
globalThis.fetch=originalQueryFetch;
mode='timeout';const uncertain=body('image');assert.equal((await generate.POST(req(uncertain))).status,504);assert.equal(JSON.parse(db.prepare('SELECT data FROM records WHERE id=?').get('media-'+uncertain.request_id).data).status,'unknown');const timeoutCalls=calls;assert.equal((await generate.POST(req(uncertain))).status,200);assert.equal(calls,timeoutCalls);
assert.throws(()=>ark.trustedVideoUrl('http://example.com/a'));assert.throws(()=>ark.trustedVideoUrl('https://volces.com.evil.test/a'));assert.throws(()=>ark.trustedVideoUrl('https://user:pass@tos.volces.com/a'));assert.ok(ark.trustedVideoUrl('https://foo.tos-cn-beijing.volces.com/a.mp4'));
// Completing a video saves an independent asset; a replay never downloads again.
const mp4=Uint8Array.from([0,0,0,16,102,116,121,112,109,112,52,50,0,0,0,0]);let downloads=0;globalThis.fetch=async(url,options)=>url==='https://api.dify.ai/v1/workflows/run'?Response.json({workflow_run_id:'dify-query-success',data:{status:'succeeded',outputs:{video_status_result:[{id:vid.task_id,model:ark.defaults.video_model,status:'succeeded',content:{video_url:'https://foo.tos-cn-beijing.volces.com/movie.mp4'}}]}}}):(assert.equal(options.redirect,'manual'),downloads++,new Response(mp4,{headers:{'Content-Type':'video/mp4'}}));r=await poll.POST(req({project_id:'test'}),{params:Promise.resolve({id:vid.id})});assert.equal(r.status,200);assert.ok((await r.json()).asset_id);await poll.POST(req({project_id:'test'}),{params:Promise.resolve({id:vid.id})});assert.equal(downloads,1);
const oldFailedId='media-old-failed';const oldFailed={kind:'video',task_id:'cgt-previous-failed',model:ark.defaults.video_model,status:'failed',error:'通用错误'};db.prepare('INSERT INTO records VALUES (?,?,?,?,?,?,?)').run(oldFailedId,'test','media',JSON.stringify(oldFailed),1,'','');let failureQueries=0;globalThis.fetch=async()=>{failureQueries++;return Response.json({data:{status:'succeeded',outputs:{video_status_result:[{id:oldFailed.task_id,model:ark.defaults.video_model,status:'failed',error:{code:'SetLimitExceeded',message:'Limit paused. Bearer abcdef'}}]}}})};r=await poll.POST(req({project_id:'test'}),{params:Promise.resolve({id:oldFailedId})});const terminal=await r.json();assert.equal(terminal.provider_error_code,'SetLimitExceeded');assert.equal(terminal.error.includes('test-ark-secret'),false);assert.equal(terminal.status,'failed');await poll.POST(req({project_id:'test'}),{params:Promise.resolve({id:oldFailedId})});assert.equal(failureQueries,1);
mode='forbidden';globalThis.fetch=async()=>Response.json({error:{code:'InvalidEndpointOrModel.NotFound',message:'Model missing. test-ark-secret Bearer abcdef sk-verysecret',request_id:'safe-request-id'}},{status:404});const rejected=body('image');r=await generate.POST(req(rejected));assert.equal(r.status,502);const rejection=await r.json();assert.match(rejection.error,/Dify/);assert.equal(rejection.error.includes('test-ark-secret'),false);assert.equal(rejection.error.includes('sk-verysecret'),false);assert.equal(rejection.error.includes('abcdef'),false);const savedFailure=JSON.parse(db.prepare('SELECT data FROM records WHERE id=?').get('media-'+rejected.request_id).data);assert.equal(savedFailure.status,'unknown');assert.equal(savedFailure.provider_status,undefined);
const {paginate,buildPpt,loadPptImages}=await import('../.sites-runtime/tests/media-ppt.mjs');const text='完整保留中文和 ASCII 内容。'.repeat(180)+'\n来源：结案P11\n待确认：人数未去重';assert.equal(paginate(text).join('\n').replace(/\n/g,''),text.replace(/\n/g,''));const ppt=await buildPpt('乐虎项目测试',[{title:'结案复盘',body:text}]);await writeFile('.sites-runtime/tests/media-export-check.pptx',await ppt.write({outputType:'nodebuffer'}));assert.ok(ppt._slides.length>2);
const raster='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aD1sAAAAASUVORK5CYII=';
const illustrated=await buildPpt('含图工作稿',[{title:'可编辑正文',body:'保留正文与来源'}],[{title:'审核参考图片',data:raster,width:1,height:1,source:'用户上传，待审核'}]);assert.equal(illustrated._slides.length,3);await writeFile('.sites-runtime/tests/media-image-export-check.pptx',await illustrated.write({outputType:'nodebuffer'}));
await assert.rejects(loadPptImages('test',[{id:'foreign',project_id:'other',type:'asset',data:{mime:'image/png',size:100}}],['foreign']),/图片不存在/);
await assert.rejects(loadPptImages('test',[],Array(7).fill('a')),/最多选择6张/);
console.log('PASS: encrypted config/no key exposure, missing-key guard, consent/origin/revision, image and video persistence, replay safety, uncertain paid request, cross-project query rejection, trusted media URLs, source-cited search and missing-citation warning, full-text PPT pagination and valid PPTX generation. Provider mocked; no paid calls.');
