import {onlineSupplement} from '@/lib/production-online';
import {readBatch} from '@/lib/production-store';
import {budgetUsage,exportableArtifacts} from '@/lib/production-batch';
import {loadProductionArtifact} from '@/lib/production-server';
import {failure,HttpError,database,bucket} from '@/lib/server';
import {activityRecord} from '@/lib/activity-server';
import {briefPreflight,copyChecks} from '@/lib/production-plan';
import {validateArtifactDependencies} from '@/lib/production-edit';
export async function GET(req:Request,{params}:{params:Promise<{id:string}>}){try{const p=new URL(req.url).searchParams.get('project_id')||'',id=(await params).id,b=await readBatch(p,id),a=await activityRecord(p);if(a?.revision!==b.data.input.activity_revision)throw new HttpError(409,'活动事实已经更新，旧批准版本不能作为当前正式交付。');const preflight=briefPreflight(b.data.input.activity,true);if(!preflight.formal_ready)throw new HttpError(400,'正式导出缺少：'+preflight.critical.join('、')+'；请补足事实并建立改字版本。');const list=exportableArtifacts(b.data).filter(x=>/^(poster-[1-4]|copy-)/.test(x.slot));if(!list.length)throw new HttpError(400,'还没有审核通过的海报或文案。');const artifacts=[];for(const item of list){const loaded=await loadProductionArtifact(p,id,item.slot);await validateArtifactDependencies(p,id,loaded.artifact);const text=loaded.artifact.copy?{title:loaded.artifact.copy.title,body:loaded.artifact.copy.body}:loaded.artifact.layout?{title:loaded.artifact.layout.headline,body:loaded.artifact.layout.details.join('\n')}:null;if(text&&copyChecks(text,b.data.input.activity).length)throw new HttpError(409,'产物遗漏已确认活动事实，不能正式导出。');artifacts.push({...item,data:loaded.artifact,reviews:loaded.job.reviews||[]})}const execution=await database().prepare("SELECT id,type,revision,data FROM records WHERE project_id=? AND type IN ('execution_plan','procurement','task','budget') ORDER BY type,id").bind(p).all<any>(),lineage=await bucket().get('_private/production-lineage/'+id);return Response.json({schema_version:1,batch_id:id,input_hash:b.data.input_hash,input:b.data.input,workflow_version:b.data.input.workflow_version,preflight,configuration:b.data.input.configuration||null,usage:budgetUsage(b.data),lineage:lineage?await lineage.json():null,artifacts,execution_snapshot:execution.results.map(r=>({...r,data:JSON.parse(r.data)})),partial:artifacts.length<8,excluded:b.data.jobs.filter(j=>!j.slot.startsWith('vision')&&!list.some(x=>x.slot===j.slot)).map(j=>({slot:j.slot,state:j.state,review:j.review})),offline:{status:'blocked',reason:'本包为线上数字海报；送印尺寸、出血、分辨率与字体尚需另行核对。'},supplement:await onlineSupplement(p,b.data),exported_at:new Date().toISOString()},{headers:{'Cache-Control':'no-store'}})}catch(e){return failure(e)}}
